import type { Domain, WeaknessTag } from "./types";

export const DOMAINS: Record<Domain, { name: string; color: string; weight: number }> = {
  // --- 220-1201 Core 1 ---
  "1.0-mobile": { name: "Mobile Devices", color: "var(--color-domain-mobile)", weight: 13 },
  "2.0-networking": { name: "Networking", color: "var(--color-domain-networking)", weight: 23 },
  "3.0-hardware": { name: "Hardware", color: "var(--color-domain-hardware)", weight: 25 },
  "4.0-virtualization-cloud": { name: "Virtualization & Cloud", color: "var(--color-domain-virtualization)", weight: 11 },
  "5.0-troubleshooting": { name: "Hardware & Network Troubleshooting", color: "var(--color-domain-troubleshooting)", weight: 28 },
  // --- 220-1202 Core 2 ---
  "1.0-operating-systems": { name: "Operating Systems", color: "var(--color-domain-os)", weight: 27 },
  "2.0-security": { name: "Security", color: "var(--color-domain-security)", weight: 24 },
  "3.0-software-troubleshooting": { name: "Software Troubleshooting", color: "var(--color-domain-swts)", weight: 26 },
  "4.0-operational-procedures": { name: "Operational Procedures", color: "var(--color-domain-ops)", weight: 23 },
};

// Gilly's weakness rankings from BOTH practice exams
// Higher priority = more urgent to study
export const WEAKNESS_PRIORITIES: Record<WeaknessTag, { label: string; priority: number; note?: string }> = {
  "jitter-vs-latency":      { label: "Jitter vs Latency", priority: 10, note: "Missed on BOTH exams — top priority" },
  "fiber-connectors":       { label: "Fiber Connectors (ST/SC/LC)", priority: 10, note: "Missed on BOTH exams (different ways)" },
  "imaging-process":        { label: "Laser Printer Imaging Sequence", priority: 9 },
  "printer-components":     { label: "Printer Components", priority: 9 },
  "memory-types":           { label: "Memory Types (DIMM/SODIMM/ECC/Virtual)", priority: 9 },
  "motherboard-id":         { label: "Motherboard Component ID", priority: 9 },
  "cabling-faults":         { label: "Cable Faults (crosstalk, split pair)", priority: 8 },
  "raid-2-drives":          { label: "RAID Selection", priority: 8 },
  "ports":                  { label: "Common Ports", priority: 8 },
  "cache-hierarchy":        { label: "CPU Cache (L1/L2/L3)", priority: 7 },
  "form-factors":           { label: "Motherboard Form Factors", priority: 7 },
  "wiring-standards":       { label: "T-568A/B Wiring", priority: 7 },
  "wireless-standards":     { label: "802.11 Standards", priority: 7 },
  "wireless-channels":      { label: "Wireless Channels (1, 6, 11)", priority: 6 },
  "expansion-bus":          { label: "Expansion Bus (PCIe/PCI/AGP)", priority: 6 },
  "display-tech":           { label: "Display Tech (OLED/LCD/LED)", priority: 6 },
  "laptop-display":         { label: "Laptop Display Components", priority: 6 },
  "port-flapping":          { label: "Port Flapping Causes", priority: 6 },
  "boot-errors":            { label: "Boot Errors (MBR/OS not found)", priority: 6 },
  "ap-troubleshooting":     { label: "AP Troubleshooting", priority: 5 },
  "multitenancy":           { label: "Cloud Multitenancy", priority: 5 },
  "printer-sharing":        { label: "Printer Sharing Methods", priority: 5 },
  "mobile-pbq":             { label: "Mobile PBQs", priority: 3 },
  // --- New granular weak-area entries ---
  "crosstalk":              { label: "Crosstalk (NEXT/FEXT)", priority: 8, note: "Caused by untwisted pairs near each other" },
  "split-pair":             { label: "Split Pair Cable Fault", priority: 8, note: "Passes continuity but fails wire-map" },
  "attenuation":            { label: "Signal Attenuation / 100m Rule", priority: 7 },
  "emi-shielding":          { label: "EMI Shielding (STP vs UTP)", priority: 7 },
  "cat-ratings":            { label: "Cat Cable Ratings & Distances", priority: 8 },
  "ddr-compat":             { label: "DDR Compatibility / Notch Positions", priority: 9 },
  "ddr-generations":        { label: "DDR Generations (DDR1-5 specs)", priority: 8 },
  "ecc-servers":            { label: "ECC / RDIMM for Servers", priority: 8 },
  "virtual-memory":         { label: "Virtual Memory / Pagefile", priority: 8 },
  "memory-form-factors":    { label: "DIMM vs SODIMM vs LPDDR", priority: 9 },
  "dual-channel":           { label: "Dual-Channel Memory Mode", priority: 7 },
  "cache-access-times":     { label: "Cache Access Speed Hierarchy", priority: 7 },
  "m2-slots":               { label: "M.2 Form Factor Naming (2280 etc)", priority: 8 },
  "power-8pin":             { label: "8-pin EPS CPU Power Connector", priority: 8 },
  "power-24pin":            { label: "24-pin ATX Motherboard Power", priority: 7 },
  "smf-mmf":                { label: "Single-Mode vs Multi-Mode Fiber", priority: 9 },
  "t568a-568b-crossover":   { label: "T-568A/B Crossover Wiring", priority: 8 },
  "twisted-pair-theory":    { label: "Twisted Pair Crosstalk Cancellation", priority: 6 },
  "copper-tools":           { label: "Copper Cabling Tools (Crimper/Punchdown/Tone)", priority: 8 },
  "cable-testing-tools":    { label: "Cable Testing (Wire Map/Certifier/TDR/OTDR)", priority: 8 },
  "network-tap":            { label: "Network Taps (Passive vs Active)", priority: 7 },
  "coax-cabling":           { label: "Coaxial Cabling (RG-6/RG-59, BNC/F-type)", priority: 7 },
  // --- Section 2.1 ---
  "usb-standards":          { label: "USB Standards (2.0/3.x/4, Type-A/B/C)", priority: 8 },
  "display-cables":         { label: "Display Cables (HDMI, DisplayPort, DVI)", priority: 8 },
  "thunderbolt":            { label: "Thunderbolt / USB4 Interface", priority: 7 },
  "sata-interface":         { label: "SATA I/II/III, eSATA, Molex", priority: 7 },
  // --- Section 3.1 ---
  "psu-wattage":            { label: "PSU Wattage & 80 PLUS Ratings", priority: 8 },
  "psu-connectors":         { label: "PSU Connectors (24-pin, PCIe, SATA, Molex)", priority: 8 },
  "psu-types":              { label: "PSU Types (Modular, Redundant)", priority: 7 },
  "cooling-systems":        { label: "Cooling (Fans, Heat Sinks, Liquid Cooling)", priority: 7 },
  // --- Section 4.2 ---
  "psu-troubleshoot":       { label: "PSU Troubleshooting (Dead, Overheating)", priority: 9 },
  "post-codes":             { label: "POST Beep Codes & LED Indicators", priority: 9 },
  "boot-sequence":          { label: "Boot Order & UEFI Boot Configuration", priority: 8 },
  "bsod-codes":             { label: "BSOD Stop Codes & Memory Dumps", priority: 9 },
  "drive-health":           { label: "Drive Health (S.M.A.R.T., Bad Sectors)", priority: 9 },
  "raid-rebuild":           { label: "RAID Degraded Mode & Rebuild", priority: 8 },
  // --- Section 5.4 ---
  "wifi-80211-standards":   { label: "Wi-Fi 802.11 Standards (a/b/g/n/ac/ax/be)", priority: 9 },
  "wifi-frequency":         { label: "Wi-Fi Frequency Bands (2.4/5/6 GHz)", priority: 8 },
  "wifi-6-ax":              { label: "Wi-Fi 6/6E (OFDMA, MU-MIMO, BSS Coloring)", priority: 8 },
  "wifi-7-be":              { label: "Wi-Fi 7 (802.11be, MLO, 320 MHz)", priority: 7 },
  "short-range-wireless":   { label: "Bluetooth, RFID, NFC", priority: 8 },
  // --- Section 6.1 ---
  "internet-conn-types":    { label: "Internet Connection Types (DSL/Cable/Fiber)", priority: 8 },
  "dsl-types":              { label: "DSL Types (ADSL, SDSL, VDSL)", priority: 7 },
  "docsis":                 { label: "DOCSIS / Cable Modem Technology", priority: 7 },
  "fiber-isp-types":        { label: "Fiber ISP Types (FTTC, FTTP, FTTH, ONT)", priority: 8 },
  "cellular-data":          { label: "Cellular Data (4G LTE vs 5G NR)", priority: 7 },
  // --- Section 6.4 ---
  "dhcp-process":           { label: "DHCP DORA Process & Scopes", priority: 9 },
  "dns-records":            { label: "DNS Record Types (A, AAAA, CNAME, MX, TXT, PTR)", priority: 9 },
  "dns-hierarchy":          { label: "DNS Hierarchy (Root, TLD, Authoritative)", priority: 8 },
  "vlan-config":            { label: "VLAN 802.1Q Tagging & Trunking", priority: 9 },
  "vpn-types":              { label: "VPN Types (Site-to-Site, Remote Access, IPsec, SSL)", priority: 8 },
  // --- Section 7.2 ---
  "proxy-server":           { label: "Proxy Servers (Forward vs Reverse)", priority: 8 },
  "utm-spam-gateway":       { label: "UTM / Spam Gateway / NGFW", priority: 8 },
  "load-balancer":          { label: "Load Balancers (Algorithms, Sticky Sessions)", priority: 7 },
  "embedded-scada":         { label: "SCADA / ICS / Embedded Systems", priority: 8 },
  "iot-security":           { label: "IoT Security & Segmentation", priority: 8 },
  // --- Section 7.3 ---
  "wired-tshooting":        { label: "Wired Network Troubleshooting", priority: 9 },
  "network-speed-tshooting":{ label: "Network Speed Issues (Duplex Mismatch)", priority: 8 },
  "wireless-tshooting":     { label: "Wireless Troubleshooting (RSSI, Interference)", priority: 9 },
  "voip-tshooting":         { label: "VoIP Troubleshooting (Jitter, QoS)", priority: 8 },
  // --- Section 10.2 ---
  "laser-imaging":          { label: "Laser Printer 7-Step Imaging Process", priority: 9 },
  "laser-maintenance":      { label: "Laser Printer Maintenance (Fuser, Drum, Toner)", priority: 8 },
  "inkjet-thermal-impact":  { label: "Inkjet, Thermal & Impact Printer Types", priority: 7 },
  // --- Section 10.3 ---
  "print-quality-issues":   { label: "Print Quality Issues (Ghosting, Streaks, Smear)", priority: 9 },
  "print-feed-issues":      { label: "Print Feed Issues (Jams, Misfeeds, Double Feed)", priority: 8 },
  "printer-connectivity":   { label: "Printer Connectivity Troubleshooting", priority: 8 },
  // --- Port & Protocol Numbers ---
  "port-numbers":            { label: "Port & Protocol Numbers", priority: 9 },
  // --- RAID Levels ---
  "raid-levels":             { label: "RAID 0/1/5/6/10 Configurations", priority: 9 },
  // --- Cloud Computing ---
  "cloud-models":            { label: "Cloud Models (IaaS/SaaS/PaaS, Public/Private/Hybrid)", priority: 9 },
  "cloud-characteristics":   { label: "Cloud Characteristics (Elasticity, Multitenancy)", priority: 8 },
  // --- Virtualization ---
  "hypervisors":             { label: "Hypervisors (Type 1 vs Type 2)", priority: 9 },
  "virtualization-types":    { label: "Virtualization Types (VMs, Containers, VDI, Sandbox)", priority: 8 },
  // ================================================================
  // === 220-1202 Core 2 weakness priorities ========================
  // ================================================================
  // --- 1.0 Operating Systems ---
  "os-types":               { label: "OS Comparison (Windows/Linux/macOS/ChromeOS)", priority: 8 },
  "file-systems":           { label: "File Systems (NTFS/FAT32/ext4/APFS/exFAT)", priority: 9 },
  "os-install":             { label: "OS Installation Methods & Types", priority: 8 },
  "windows-editions":       { label: "Windows Editions (Home/Pro/Enterprise)", priority: 9 },
  "windows-tools":          { label: "Windows Admin Tools (Task Mgr/MMC/msconfig)", priority: 9 },
  "windows-cli":            { label: "Windows CLI Tools (ipconfig/sfc/chkdsk/diskpart)", priority: 9 },
  "windows-settings":       { label: "Windows Settings & Control Panel", priority: 7 },
  "windows-networking":     { label: "Windows Networking (domain/workgroup/drives)", priority: 8 },
  "macos-features":         { label: "macOS Features (FileVault/Time Machine/Keychain)", priority: 8 },
  "linux-commands":         { label: "Linux Commands (ls/chmod/sudo/apt/grep)", priority: 9 },
  // --- 2.0 Security ---
  "physical-security":      { label: "Physical Security Controls", priority: 8 },
  "logical-security":       { label: "Logical Security (MFA/Zero Trust/ACLs)", priority: 9 },
  "windows-security":       { label: "Windows Security (UAC/BitLocker/AD/EFS)", priority: 9 },
  "wireless-security":      { label: "Wireless Security (WPA3/RADIUS/TACACS+)", priority: 9 },
  "malware-types":          { label: "Malware Types (trojan/rootkit/ransomware)", priority: 10, note: "High-frequency exam topic" },
  "malware-removal":        { label: "10-Step Malware Removal Process", priority: 10, note: "Must know every step in order" },
  "social-engineering":     { label: "Social Engineering (phishing/vishing/smishing)", priority: 9 },
  "attack-types":           { label: "Attack Types (DoS/XSS/SQLi/on-path)", priority: 9 },
  "security-hardening":     { label: "Security Hardening (passwords/lockout/patching)", priority: 8 },
  "mobile-security":        { label: "Mobile Security (MDM/BYOD/remote wipe)", priority: 8 },
  "data-destruction":       { label: "Data Destruction Methods", priority: 8 },
  "soho-security":          { label: "SOHO Network Security", priority: 8 },
  "browser-security":       { label: "Browser Security (certs/extensions/private mode)", priority: 7 },
  // --- 3.0 Software Troubleshooting ---
  "windows-tshooting":      { label: "Windows Troubleshooting (BSOD/startup/crashes)", priority: 9 },
  "mobile-app-tshooting":   { label: "Mobile App Troubleshooting", priority: 8 },
  "mobile-sec-tshooting":   { label: "Mobile Security Troubleshooting", priority: 8 },
  "pc-sec-tshooting":       { label: "PC Security Troubleshooting (ransomware/redirects)", priority: 9 },
  // --- 4.0 Operational Procedures ---
  "ticketing-systems":      { label: "Ticketing & Documentation Systems", priority: 8 },
  "change-management":      { label: "Change Management (CAB/rollback/sandbox)", priority: 9 },
  "backup-recovery":        { label: "Backup & Recovery (full/incremental/3-2-1 rule)", priority: 9 },
  "safety-esd":             { label: "ESD Safety & Antistatic Procedures", priority: 8 },
  "environmental":          { label: "Environmental Procedures (UPS/SDS/humidity)", priority: 7 },
  "privacy-licensing":      { label: "Privacy, Licensing & Policies (PII/EULA/NDA)", priority: 8 },
  "scripting":              { label: "Scripting (.ps1/.py/.sh/.bat use cases)", priority: 8 },
  "remote-access":          { label: "Remote Access Tools (RDP/VNC/SSH/VPN)", priority: 8 },
  "ai-management":          { label: "AI Management (bias/hallucinations/public AI)", priority: 7 },
};
