$file = "c:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$trimmed = $content.TrimEnd().Substring(0, $content.TrimEnd().LastIndexOf('];'))
$newQuestions = @'

  // -- 7.2 Internet and Embedded Appliances ------------------------------------
  {
    id: "ia-72-01", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the difference between a forward proxy and a reverse proxy?",
    choices: [
      { id: "a", text: "Forward proxy filters inbound web traffic; reverse proxy filters outbound traffic", correct: false },
      { id: "b", text: "Forward proxy sits between clients and the internet (client-side); reverse proxy sits between the internet and web servers (server-side)", correct: true },
      { id: "c", text: "Forward proxy requires authentication; reverse proxy does not", correct: false },
      { id: "d", text: "Reverse proxy is only used for email filtering; forward proxy is for web only", correct: false },
    ],
    explanation: "Forward proxy: sits between internal clients and the internet. Clients are configured to send traffic through it. Use cases: content filtering (block social media), caching (bandwidth savings), anonymization, and monitoring user web activity. Transparent proxy: same as forward proxy but clients don't need configuration (traffic is intercepted). Reverse proxy: sits in front of web servers, receives traffic from the internet. Use cases: load balancing, SSL termination, caching, application firewall. Clients don't know about the backend servers.",
    triggerPhrase: "Forward proxy = client-side (filters/monitors outbound internet); Reverse proxy = server-side (balances/protects web servers)",
    weaknessTags: ["proxy-server"],
  },
  {
    id: "ia-72-02", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "A transparent proxy intercepts web traffic without requiring any client configuration. How does this work?",
    choices: [
      { id: "a", text: "It uses a VPN to redirect traffic without client software", correct: false },
      { id: "b", text: "Network infrastructure (router or firewall) redirects HTTP/HTTPS traffic to the proxy via port redirection or policy routing", correct: true },
      { id: "c", text: "It modifies DNS responses to redirect clients to the proxy", correct: false },
      { id: "d", text: "Each client automatically detects the proxy via the DHCP options field", correct: false },
    ],
    explanation: "A transparent (intercepting) proxy works by having the network infrastructure redirect traffic to the proxy server without the client's knowledge or configuration. Typically implemented via: router ACL/policy-based routing redirecting port 80/443, firewall DNAT (destination NAT), or a WCCP (Web Cache Communication Protocol) redirect from a Cisco router. The proxy handles the connection on the client's behalf. SSL inspection (HTTPS inspection) requires installing a CA certificate on clients to decrypt HTTPS traffic.",
    triggerPhrase: "Transparent proxy = network redirects traffic to proxy; clients need no config; uses port redirect or policy routing",
    weaknessTags: ["proxy-server"],
  },
  {
    id: "ia-72-03", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A UTM (Unified Threat Management) appliance combines multiple security functions. Which combination BEST describes a UTM?",
    choices: [
      { id: "a", text: "Router + switch + wireless access point in one device", correct: false },
      { id: "b", text: "Firewall + intrusion detection/prevention + antivirus + content filtering + VPN in a single appliance", correct: true },
      { id: "c", text: "Load balancer + application delivery controller + web cache in one device", correct: false },
      { id: "d", text: "DNS server + DHCP server + NTP server combined in one hardware appliance", correct: false },
    ],
    explanation: "UTM (Unified Threat Management) appliances consolidate multiple security technologies: stateful firewall, IDS/IPS (intrusion detection/prevention), gateway antivirus, anti-spam, URL/content filtering, VPN gateway, and sometimes application awareness. Benefits: single vendor management, reduced complexity. Tradeoff: performance bottleneck (all traffic inspected by one box). Next-Generation Firewalls (NGFW) are similar but focus more on application-layer inspection and user identity. Common UTM vendors: Fortinet, SonicWall, Sophos.",
    triggerPhrase: "UTM = firewall + IDS/IPS + antivirus + spam filter + VPN in one box; NGFW adds application awareness",
    weaknessTags: ["utm-spam-gateway"],
  },
  {
    id: "ia-72-04", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "A spam gateway sits at the edge of an email system. What is its PRIMARY function?",
    choices: [
      { id: "a", text: "It routes email to the correct internal mailboxes based on the recipients list", correct: false },
      { id: "b", text: "It filters inbound email for spam, phishing, and malware before delivering to the mail server", correct: true },
      { id: "c", text: "It backs up all email to a secondary server in real time", correct: false },
      { id: "d", text: "It encrypts all outbound email using S/MIME certificates", correct: false },
    ],
    explanation: "An email/spam gateway (also called a mail security gateway or secure email gateway) sits in front of the organization's mail server, receiving all inbound email first. It applies: spam scoring algorithms, IP/domain reputation checks, phishing link detection, attachment scanning for malware, SPF/DKIM/DMARC validation, and content filtering. Legitimate email passes through to the mail server; spam/malware is quarantined or rejected. Examples: Proofpoint, Barracuda, Cisco IronPort, Mimecast.",
    triggerPhrase: "Spam/email gateway = filters spam/phishing/malware BEFORE email reaches internal mail server",
    weaknessTags: ["utm-spam-gateway"],
  },
  {
    id: "ia-72-05", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A web server farm needs to distribute incoming HTTP requests evenly across 4 servers. Which device handles this and what is the most common distribution algorithm?",
    choices: [
      { id: "a", text: "Router using OSPF equal-cost load sharing", correct: false },
      { id: "b", text: "Load balancer using round-robin algorithm (rotating requests through servers in sequence)", correct: true },
      { id: "c", text: "Proxy server using DNS round-robin", correct: false },
      { id: "d", text: "Content delivery network using anycast routing", correct: false },
    ],
    explanation: "Load balancers distribute incoming connections across multiple servers. Common algorithms: Round-robin: each request goes to the next server in rotation (equal distribution). Least connections: send to whichever server has the fewest active connections (better for varying request duration). IP hash: same client IP always goes to same server (session persistence without cookies). Sticky sessions (session persistence): ensures a user's requests go to the same server during a session (important for stateful apps). Load balancers also perform health checks and remove failed servers.",
    triggerPhrase: "Load balancer: round-robin = rotate equally; least-connections = send to least-busy; sticky sessions = same client to same server",
    weaknessTags: ["load-balancer"],
  },
  {
    id: "ia-72-06", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Why are legacy systems (older OS/software that no longer receives security patches) a significant security risk in a network?",
    choices: [
      { id: "a", text: "Legacy systems use older hardware that transmits data more slowly, creating network congestion", correct: false },
      { id: "b", text: "Known vulnerabilities are publicly documented but unpatched, making legacy systems easily exploitable by attackers", correct: true },
      { id: "c", text: "Legacy systems cannot support VLAN tagging, making network segmentation impossible", correct: false },
      { id: "d", text: "Legacy systems always use cleartext protocols that are easily readable on the network", correct: false },
    ],
    explanation: "When a vendor ends support for a product (End of Life/End of Support), no more security patches are released. Security researchers continue finding vulnerabilities; attackers know these systems are permanently vulnerable. The vulnerabilities get published (CVE database) and exploit code is released. Examples: Windows XP (support ended 2014) is still attacked by EternalBlue/WannaCry-style exploits. Mitigation: network segmentation/isolation, additional compensating controls (WAF, IPS), and migration planning.",
    triggerPhrase: "Legacy systems = unpatched CVEs permanently exploitable; mitigate with segmentation, IPS, and migration",
    weaknessTags: ["embedded-scada"],
  },
  {
    id: "ia-72-07", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is an embedded operating system, and what is a key difference from a general-purpose OS?",
    choices: [
      { id: "a", text: "An embedded OS runs on standard x86 hardware but with a smaller GUI", correct: false },
      { id: "b", text: "An embedded OS is purpose-built for specific hardware to perform a dedicated function, often with no user interface and resource constraints", correct: true },
      { id: "c", text: "An embedded OS is a virtual machine running inside another OS", correct: false },
      { id: "d", text: "An embedded OS requires more RAM than Windows to operate correctly", correct: false },
    ],
    explanation: "Embedded operating systems are designed for specific hardware with a single purpose: routers, smart TVs, printers, medical devices, industrial controllers, ATMs, and smart appliances. Key characteristics: minimal resource requirements (small CPU, little RAM), no general-purpose computing, often real-time (RTOS), no user-installable applications, designed for long-term reliability. Examples: VxWorks, QNX (used in cars/medical), Embedded Linux, ThreadX. Updates are infrequent and require vendor-specific firmware updates.",
    triggerPhrase: "Embedded OS = purpose-built for one function, resource-constrained, minimal UI; RTOS for real-time requirements",
    weaknessTags: ["embedded-scada"],
  },
  {
    id: "ia-72-08", domain: "2.0-networking", difficulty: "hard", type: "single", source: "drill",
    prompt: "What is SCADA (Supervisory Control and Data Acquisition) and in what environments is it found?",
    choices: [
      { id: "a", text: "SCADA is a security scanning tool used by network administrators", correct: false },
      { id: "b", text: "SCADA is a system that monitors and controls physical industrial processes such as power grids, water treatment, pipelines, and manufacturing", correct: true },
      { id: "c", text: "SCADA is a type of cloud storage system for industrial data", correct: false },
      { id: "d", text: "SCADA refers to software-defined networking controllers for enterprise networks", correct: false },
    ],
    explanation: "SCADA (Supervisory Control and Data Acquisition) systems monitor and control distributed industrial processes in real time: electrical grids, water/wastewater treatment, oil/gas pipelines, manufacturing plants, HVAC for large buildings. Components: PLCs (Programmable Logic Controllers) — physical controllers at the process level; RTUs (Remote Terminal Units) — gather sensor data; HMI (Human-Machine Interface) — operator view. ICS (Industrial Control Systems) is the broader category. Connecting these to IT networks creates major security risks.",
    triggerPhrase: "SCADA = monitors/controls industrial processes (power, water, pipelines); uses PLCs, RTUs, HMI; critical infrastructure",
    weaknessTags: ["embedded-scada"],
  },
  {
    id: "ia-72-09", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "IoT (Internet of Things) devices present unique security challenges. Which measure BEST reduces the risk posed by IoT devices?",
    choices: [
      { id: "a", text: "Replace all IoT devices with mobile smartphones which are more secure", correct: false },
      { id: "b", text: "Place IoT devices on a separate VLAN/network segment isolated from the main corporate network", correct: true },
      { id: "c", text: "Disable the internet connection for all IoT devices so they function only locally", correct: false },
      { id: "d", text: "Use only IoT devices from the same manufacturer to simplify security management", correct: false },
    ],
    explanation: "IoT security problems: many devices have default/hardcoded credentials, rarely receive firmware updates, run embedded OSes with unpatched vulnerabilities, and can't run security agents. Best practice: IoT segmentation/isolation — place all IoT devices on a dedicated VLAN with a firewall restricting inter-VLAN communication. The IoT VLAN should have internet access (for device function/updates) but NO access to servers, workstations, or sensitive data. Additional measures: change default passwords, disable unused services, monitor for abnormal traffic.",
    triggerPhrase: "IoT security: isolate to dedicated VLAN, change default passwords, no access to main network, monitor traffic",
    weaknessTags: ["iot-security"],
  },
  {
    id: "ia-72-10", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is a PLC (Programmable Logic Controller) and in what context does it appear on the CompTIA A+ exam?",
    choices: [
      { id: "a", text: "PLC is a type of low-power laptop designed for industrial fieldwork", correct: false },
      { id: "b", text: "PLC is a ruggedized digital computer used to control industrial machinery; relevant to embedded systems, SCADA, and IoT security", correct: true },
      { id: "c", text: "PLC stands for Printed Logic Circuit, which is the motherboard in embedded devices", correct: false },
      { id: "d", text: "PLC is a power line communication standard for smart home devices", correct: false },
    ],
    explanation: "A PLC (Programmable Logic Controller) is a ruggedized industrial computer designed to automate electromechanical processes: assembly lines, robotic equipment, conveyor systems, traffic lights, and amusement rides. It reads inputs (sensors, switches) and controls outputs (motors, valves, lights) based on programmed logic. PLCs are key components in ICS/SCADA systems. For A+ purposes: understanding that PLCs are embedded systems with security implications when connected to networks is important.",
    triggerPhrase: "PLC = industrial computer for automation (sensors/motors); part of ICS/SCADA; security risk when networked",
    weaknessTags: ["embedded-scada"],
  },
  {
    id: "ia-72-11", domain: "2.0-networking", difficulty: "hard", type: "single", source: "drill",
    prompt: "What is an air-gapped system and why is it used for critical infrastructure?",
    choices: [
      { id: "a", text: "A system that uses air cooling instead of liquid cooling for safety", correct: false },
      { id: "b", text: "A system physically isolated from unsecured networks (no wired or wireless network connection), preventing remote attacks", correct: true },
      { id: "c", text: "A system with extra physical space between components to prevent overheating", correct: false },
      { id: "d", text: "A virtualization technology that isolates VMs from each other", correct: false },
    ],
    explanation: "Air-gapped systems have no network connection to outside networks — not even indirectly. Used for: nuclear control systems, classified military systems, SCADA for critical infrastructure, certain financial systems. Attacks must be physical (USB drops, insider threats). Stuxnet famously crossed an air gap via infected USB drives to attack Iranian centrifuge PLCs. Air gap maintenance challenges: software updates require physical media, monitoring is difficult, and insider threats are the primary attack vector.",
    triggerPhrase: "Air-gapped = no network connection (physical isolation); prevents remote attacks; Stuxnet crossed air gap via USB",
    weaknessTags: ["embedded-scada", "iot-security"],
  },
  {
    id: "ia-72-12", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A load balancer uses 'sticky sessions' (session persistence). What problem does this solve?",
    choices: [
      { id: "a", text: "It ensures servers don't become overloaded by sticking to a maximum connection limit", correct: false },
      { id: "b", text: "It ensures a user's requests always go to the same server, preventing session data loss when applications store state on a specific server", correct: true },
      { id: "c", text: "It prevents servers from going offline by keeping their connections active", correct: false },
      { id: "d", text: "It allows the load balancer to cache responses and stick to the cached version", correct: false },
    ],
    explanation: "Sticky sessions (session affinity): Many web applications store session data in memory on the server (shopping cart, login state). If a load balancer sends subsequent requests to a different server, the user appears logged out or their cart is empty. Sticky sessions solve this by: tracking the client's IP or setting a cookie, then always routing that client to the same server for the session duration. Limitation: a server failure drops all its sticky sessions. Modern solution: store session data in a shared cache (Redis, Memcached) and allow true stateless load balancing.",
    triggerPhrase: "Sticky sessions = client always goes to same server; prevents session loss in stateful apps; tracked by IP or cookie",
    weaknessTags: ["load-balancer"],
  },
  {
    id: "ia-72-13", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the PRIMARY security concern with connecting IoT devices that have default factory credentials to a network?",
    choices: [
      { id: "a", text: "Default credentials cause slower network speeds due to authentication overhead", correct: false },
      { id: "b", text: "Attackers can use publicly known default credentials to compromise IoT devices and use them in botnets or as network pivots", correct: true },
      { id: "c", text: "Factory credentials are too complex for users to remember, causing lockouts", correct: false },
      { id: "d", text: "Default credentials prevent the device from receiving firmware updates", correct: false },
    ],
    explanation: "Default credentials (admin/admin, admin/password, etc.) are publicly documented by device manufacturers. The Mirai botnet (2016) compromised hundreds of thousands of IoT devices (cameras, DVRs, routers) using a list of 61 default username/password combinations, then used them to launch a 1.1 Tbps DDoS attack. Always change default credentials immediately upon deployment. Some modern devices (per legislation in California, UK) now require unique per-device passwords from the factory.",
    triggerPhrase: "IoT default credentials = publicly known; Mirai botnet used defaults to compromise 100k+ devices for DDoS",
    weaknessTags: ["iot-security"],
  },
  {
    id: "ia-72-14", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What network security device inspects traffic and can actively block malicious packets in real time (not just alert)?",
    choices: [
      { id: "a", text: "IDS (Intrusion Detection System)", correct: false },
      { id: "b", text: "IPS (Intrusion Prevention System)", correct: true },
      { id: "c", text: "Network tap (SPAN port)", correct: false },
      { id: "d", text: "Packet sniffer (Wireshark)", correct: false },
    ],
    explanation: "IDS vs IPS: IDS (Intrusion Detection System): monitors traffic and ALERTS on suspicious activity — passive, inline or out-of-band (SPAN port). Does not block traffic. IPS (Intrusion Prevention System): sits inline in the traffic path and can BLOCK or DROP malicious packets in real time based on signatures, anomalies, or behavior. False positives can block legitimate traffic, requiring tuning. Modern NGFWs incorporate IPS functionality. SPAN (mirror) ports are used for out-of-band monitoring only.",
    triggerPhrase: "IDS = detect + alert only (passive); IPS = detect + block in real time (inline); false positives need tuning",
    weaknessTags: ["utm-spam-gateway"],
  },
  {
    id: "ia-72-15", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A SCADA system controls a city's water treatment plant. A cybersecurity consultant recommends it should NEVER be connected to the corporate IT network. Why?",
    choices: [
      { id: "a", text: "SCADA systems use proprietary protocols that are incompatible with TCP/IP networks", correct: false },
      { id: "b", text: "Connecting SCADA to a corporate network exposes critical infrastructure to cyberattacks that could physically damage equipment or affect public safety", correct: true },
      { id: "c", text: "SCADA systems would slow down the corporate network with high bandwidth usage", correct: false },
      { id: "d", text: "Corporate IT policies prohibit connecting any embedded system to the network", correct: false },
    ],
    explanation: "ICS/SCADA systems were traditionally isolated (air-gapped), but IT/OT (Operational Technology) convergence has connected many for remote monitoring. This creates critical risks: an attacker who compromises the IT network can pivot to SCADA; cyber attacks can cause physical consequences — Stuxnet destroyed centrifuges, the 2021 Oldsmar water plant attack attempted to increase sodium hydroxide to dangerous levels via remote access. NIST and ICS-CERT recommend strict network segmentation between IT and OT networks with one-way data diodes if monitoring is needed.",
    triggerPhrase: "SCADA + IT network = risk of cyberattacks causing physical damage; Oldsmar water plant attacked; keep IT/OT separated",
    weaknessTags: ["embedded-scada", "iot-security"],
  },

  // -- 7.3 Troubleshoot Networks -----------------------------------------------
  {
    id: "tn-73-01", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "When troubleshooting a computer with no network connectivity, which physical check should come FIRST?",
    choices: [
      { id: "a", text: "Run ipconfig /release and /renew to refresh the IP address", correct: false },
      { id: "b", text: "Check that the network cable is plugged in and the link light (LED) on the NIC and switch is lit", correct: true },
      { id: "c", text: "Ping the default gateway to test routing", correct: false },
      { id: "d", text: "Check Windows Device Manager for NIC driver errors", correct: false },
    ],
    explanation: "Start troubleshooting at Layer 1 (Physical): verify the Ethernet cable is seated in both the NIC and the switch port. Look for the link light — a solid green LED on both ends confirms a physical link is established. No link light = cable unplugged, bad cable, wrong port, or dead NIC/switch port. Try a different cable and different switch port. Only move to Layer 2/3 (IP, routing) troubleshooting after confirming Layer 1 is working. This follows the OSI bottom-up troubleshooting model.",
    triggerPhrase: "No network = check link light first (Layer 1); no light = bad cable/port; then work up OSI layers",
    weaknessTags: ["wired-tshooting"],
  },
  {
    id: "tn-73-02", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A Windows computer shows an IP address of 169.254.x.x. What does this indicate?",
    choices: [
      { id: "a", text: "The computer has been assigned a valid IP address from the DHCP server", correct: false },
      { id: "b", text: "The computer could not reach a DHCP server and has self-assigned an APIPA address (Automatic Private IP Addressing)", correct: true },
      { id: "c", text: "The IP address is a private IPv6 address in dot notation", correct: false },
      { id: "d", text: "The router has assigned a reserved diagnostic IP to the computer", correct: false },
    ],
    explanation: "APIPA (Automatic Private IP Addressing): When a Windows device cannot reach a DHCP server after repeated attempts, it self-assigns an IP in the 169.254.0.1-169.254.255.254 range (subnet mask /16). This is a link-local address. The device can communicate with other APIPA devices on the same segment but has NO internet access, NO default gateway, and NO DNS. Causes: DHCP server down, cable disconnected, DHCP scope exhausted, VLAN misconfiguration. Fix: restore DHCP connectivity, then run ipconfig /release /renew.",
    triggerPhrase: "169.254.x.x = APIPA; means DHCP server unreachable; no internet/gateway access; fix DHCP then /release /renew",
    weaknessTags: ["wired-tshooting", "dhcp-process"],
  },
  {
    id: "tn-73-03", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "What does pinging 127.0.0.1 test, and what does it confirm if successful?",
    choices: [
      { id: "a", text: "Tests connectivity to the default gateway; confirms routing is working", correct: false },
      { id: "b", text: "Tests the local TCP/IP stack (loopback); confirms IP networking is installed and functioning on the local machine", correct: true },
      { id: "c", text: "Tests the DNS server; confirms name resolution is working", correct: false },
      { id: "d", text: "Tests connectivity to the ISP; confirms internet access is available", correct: false },
    ],
    explanation: "127.0.0.1 is the loopback address (also accessible as localhost). Pinging 127.0.0.1 sends packets to the local TCP/IP stack without going out to the network. Successful response = the TCP/IP stack is installed, loaded, and functional. Failed response = TCP/IP is broken or the network driver has a major fault (very unusual on modern systems). Troubleshooting sequence: ping 127.0.0.1 > ping own IP > ping default gateway > ping external IP > ping by DNS name.",
    triggerPhrase: "Ping 127.0.0.1 = loopback test; confirms local TCP/IP stack works; then own IP > gateway > internet IP > DNS name",
    weaknessTags: ["wired-tshooting"],
  },
  {
    id: "tn-73-04", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A workstation can ping its own IP and 127.0.0.1, but cannot ping the default gateway. What layer is the problem likely on?",
    choices: [
      { id: "a", text: "Layer 1 (Physical) — bad cable or link light issue", correct: false },
      { id: "b", text: "Layer 2/3 — network connectivity between the workstation and the gateway is broken (switch, VLAN, cable, or gateway)", correct: true },
      { id: "c", text: "Layer 7 (Application) — web browser configuration issue", correct: false },
      { id: "d", text: "Layer 4 (Transport) — TCP/UDP port blocked by firewall", correct: false },
    ],
    explanation: "Troubleshooting by elimination: Can ping 127.0.0.1 = TCP/IP stack is fine. Can ping own IP = NIC is working. Cannot ping default gateway = the path between the workstation and the gateway is broken. This points to Layer 1/2/3 between the two: bad cable or switch port, wrong VLAN, switch loop, gateway down, or a firewall on the gateway blocking ICMP. Check cable and switch link light (L1), then check VLAN assignment (L2), then check gateway status (L3).",
    triggerPhrase: "Ping 127.0.0.1 + own IP works, gateway fails = Layer 1/2/3 issue between workstation and gateway; check cable/VLAN/gateway",
    weaknessTags: ["wired-tshooting"],
  },
  {
    id: "tn-73-05", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "Two computers connected to the same switch are experiencing slow network speeds between them. The NIC on one computer is set to 1000 Mbps Full Duplex, but the switch port auto-negotiated to 100 Mbps Half Duplex. What is this called?",
    choices: [
      { id: "a", text: "VLAN mismatch", correct: false },
      { id: "b", text: "Duplex mismatch", correct: true },
      { id: "c", text: "MTU mismatch", correct: false },
      { id: "d", text: "Bandwidth throttling", correct: false },
    ],
    explanation: "A duplex mismatch occurs when two connected network devices negotiate different duplex settings: one is Full Duplex (sends and receives simultaneously), the other is Half Duplex (alternates between sending and receiving). Result: the full-duplex side transmits while the half-duplex side tries to prevent collisions (CSMA/CD), causing excessive late collisions, poor throughput (typically drops to 10-30% of capacity), and high error rates visible in interface statistics. Fix: force both ends to the same speed and duplex, or ensure both sides auto-negotiate successfully.",
    triggerPhrase: "Duplex mismatch = one end full-duplex, other half-duplex; causes collisions, slow speeds, high errors; fix by matching both ends",
    weaknessTags: ["wired-tshooting", "network-speed-tshooting"],
  },
  {
    id: "tn-73-06", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A user connects their laptop to a known Wi-Fi network but cannot connect. They verify the signal strength is good. What should be checked next?",
    choices: [
      { id: "a", text: "Replace the wireless access point", correct: false },
      { id: "b", text: "Verify the SSID name is correct and the Wi-Fi password (passphrase) is entered correctly", correct: true },
      { id: "c", text: "Check if the DNS server is responsive", correct: false },
      { id: "d", text: "Reinstall the wireless NIC driver", correct: false },
    ],
    explanation: "Wi-Fi connection failure with good signal: verify the correct SSID is selected (many networks have similar names) and the passphrase is correct (check caps lock, special characters). 'Authentication failed' or 'Incorrect password' errors confirm credential issues. Hidden SSIDs require manual entry of the exact name. If passphrase is confirmed correct: check if the AP's MAC filter is blocking the device, try forgetting and rejoining the network, check if the security type (WPA2/WPA3) matches, and verify the client supports the AP's security mode.",
    triggerPhrase: "Wi-Fi won't connect with good signal: check SSID name and passphrase first; then MAC filter, forget/rejoin, security type",
    weaknessTags: ["wireless-tshooting"],
  },
  {
    id: "tn-73-07", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A wireless client receives a valid IP address but cannot access the internet. Other wired clients on the same network work fine. What should be investigated FIRST?",
    choices: [
      { id: "a", text: "The ISP connection is down", correct: false },
      { id: "b", text: "DNS and DHCP are not working on the wireless network segment or the wireless client is on the wrong VLAN", correct: true },
      { id: "c", text: "The wireless adapter needs a driver update", correct: false },
      { id: "d", text: "The AP needs to be rebooted immediately", correct: false },
    ],
    explanation: "Wireless gets IP but no internet, wired works: the problem is between the wireless client and the internet. Check: Is the IP valid (not APIPA 169.254.x.x)? Is the default gateway correct? Can the wireless client ping the gateway? Can it ping an external IP (8.8.8.8)? If ping by IP works but DNS names fail, it's a DNS issue. If wireless client is on wrong VLAN, gateway may not route to internet. Also check if the AP has internet access from its own management IP, and if a captive portal is blocking access.",
    triggerPhrase: "Wireless gets IP but no internet, wired works: check gateway reachability, DNS, VLAN assignment, AP routing",
    weaknessTags: ["wireless-tshooting"],
  },
  {
    id: "tn-73-08", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "VoIP calls between an office and a remote site are consistently choppy and users hear robotic voice distortion. What metric and solution should the technician focus on?",
    choices: [
      { id: "a", text: "Bandwidth — increase the internet connection speed", correct: false },
      { id: "b", text: "Jitter — implement QoS to prioritize voice traffic with low-latency queuing", correct: true },
      { id: "c", text: "Packet loss — replace all network cables with fiber", correct: false },
      { id: "d", text: "DNS latency — configure a faster DNS server", correct: false },
    ],
    explanation: "VoIP quality metrics: Latency: one-way delay >150 ms causes noticeable delay; >400 ms is unacceptable. Jitter: variation in packet arrival times; causes choppy/robotic audio. Packet loss: >1-3% causes dropped syllables. Choppy/robotic audio is the classic symptom of jitter or packet loss. Solution: QoS (Quality of Service) — mark voice packets with DSCP EF (Expedited Forwarding) and configure low-latency queuing (LLQ) on routers/switches to prioritize voice packets. Bandwidth alone won't fix jitter.",
    triggerPhrase: "VoIP choppy/robotic = jitter (variable delay); fix with QoS, DSCP EF, low-latency queuing to prioritize voice packets",
    weaknessTags: ["voip-tshooting"],
  },
  {
    id: "tn-73-09", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "During a VoIP call, the user can hear the remote party but the remote party cannot hear the user (one-way audio). What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The user's microphone is physically broken", correct: false },
      { id: "b", text: "A NAT/firewall issue preventing the RTP audio stream in one direction from passing through", correct: true },
      { id: "c", text: "The DNS server is not resolving the VoIP server name", correct: false },
      { id: "d", text: "The VoIP phone has an outdated firmware version", correct: false },
    ],
    explanation: "One-way VoIP audio: the SIP signaling established the call, but RTP (Real-time Transport Protocol) audio packets are only flowing one direction. Common cause: NAT/firewall asymmetry — the firewall allows outbound RTP but blocks inbound RTP on the dynamic port range. Solutions: enable SIP ALG (Application Layer Gateway) on the router/firewall to handle NAT for SIP/RTP, configure a STUN server for NAT traversal, or use a VoIP-aware firewall. Also check if RTP port range (usually 10000-20000 UDP) is open in firewall rules.",
    triggerPhrase: "VoIP one-way audio = NAT/firewall blocking RTP in one direction; fix with SIP ALG, STUN, or firewall RTP port rules",
    weaknessTags: ["voip-tshooting"],
  },
  {
    id: "tn-73-10", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A network technician suspects bandwidth saturation is causing slow performance. What tool would they use to monitor network utilization in real time?",
    choices: [
      { id: "a", text: "CHKDSK", correct: false },
      { id: "b", text: "Network monitoring tool (SNMP-based), switch interface statistics, or packet capture (Wireshark)", correct: true },
      { id: "c", text: "Device Manager", correct: false },
      { id: "d", text: "BIOS POST diagnostics", correct: false },
    ],
    explanation: "Bandwidth saturation troubleshooting tools: Switch interface statistics (show interfaces on Cisco): check input/output rates, error counters, and drops. SNMP monitoring tools (PRTG, SolarWinds, Nagios): graph historical utilization trends. Wireshark/packet capture: identify top talkers consuming bandwidth. NetFlow/sFlow: traffic accounting and application identification. Windows Task Manager > Performance > Ethernet: quick check on a single host. Identify which device or application is saturating the link, then apply QoS, rate limiting, or upgrade bandwidth.",
    triggerPhrase: "Bandwidth saturation: use switch interface stats, SNMP tools (PRTG), Wireshark, or NetFlow to find top talkers",
    weaknessTags: ["network-speed-tshooting"],
  },
  {
    id: "tn-73-11", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "Wireless clients in a busy office complain of slow speeds despite strong signal. A Wi-Fi analyzer shows many SSIDs on the same channel. What is this problem called and how is it resolved?",
    choices: [
      { id: "a", text: "Hidden SSID collision — enable SSID broadcast on all APs", correct: false },
      { id: "b", text: "Co-channel interference — change to a non-overlapping channel (or switch to 5 GHz)", correct: true },
      { id: "c", text: "MAC address conflict — assign static IPs to all wireless clients", correct: false },
      { id: "d", text: "DHCP scope exhaustion — expand the IP address pool", correct: false },
    ],
    explanation: "Co-channel interference (CCI): multiple APs and neighboring networks using the same channel compete for airtime using CSMA/CA — each device must wait for the channel to be clear before transmitting. More devices = more waiting = slower throughput even with excellent signal strength. Symptoms: slow throughput despite -50 to -65 dBm signal. Fix: change the AP to a non-overlapping channel (1, 6, or 11 on 2.4 GHz). Better: migrate to 5 GHz (23+ non-overlapping channels, fewer neighbors). Conduct a site survey to find the least congested channel.",
    triggerPhrase: "Slow Wi-Fi despite good signal + many SSIDs on same channel = co-channel interference; switch to uncrowded channel or 5 GHz",
    weaknessTags: ["wireless-tshooting", "wifi-frequency"],
  },
  {
    id: "tn-73-12", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "What does the tracert (traceroute) command reveal about a network connection?",
    choices: [
      { id: "a", text: "It shows all devices connected to the local switch", correct: false },
      { id: "b", text: "It shows each router hop along the path to a destination, with the round-trip time to each hop", correct: true },
      { id: "c", text: "It shows the DNS records for a domain name", correct: false },
      { id: "d", text: "It tests whether a specific TCP port is open on a remote host", correct: false },
    ],
    explanation: "Tracert (Windows) / traceroute (Linux/Mac) sends packets with incrementing TTL (Time to Live) values. Each router decrements TTL and replies with an ICMP Time Exceeded when TTL reaches 0, revealing the router's IP and RTT. Output: hop number, IP address, three RTT measurements. Use cases: identify where a connection is slow (high latency at a specific hop), identify where packets are dropped (request timed out after a hop), map the network path. * * * at every hop = router not responding to ICMP (firewall), not necessarily a problem.",
    triggerPhrase: "tracert = shows each router hop + latency to each hop; find where slowness or packet loss begins",
    weaknessTags: ["wired-tshooting", "network-speed-tshooting"],
  },
  {
    id: "tn-73-13", domain: "5.0-troubleshooting", difficulty: "hard", type: "single", source: "drill",
    prompt: "When troubleshooting network problems using the OSI model bottom-up approach, what is the correct order to check layers?",
    choices: [
      { id: "a", text: "Application > Transport > Network > Data Link > Physical", correct: false },
      { id: "b", text: "Physical > Data Link > Network > Transport > Session > Presentation > Application", correct: true },
      { id: "c", text: "Network > Physical > Application > Transport > Data Link", correct: false },
      { id: "d", text: "Transport > Network > Physical > Application > Data Link", correct: false },
    ],
    explanation: "Bottom-up OSI troubleshooting: L1 Physical: cable, link light, NIC, power. L2 Data Link: MAC address, switch, VLAN, duplex, CRC errors. L3 Network: IP address, subnet mask, default gateway, routing, ping. L4 Transport: TCP/UDP ports, firewall rules, telnet/nc port test. L5-7 Session/Presentation/Application: application config, authentication, certificates, browser, protocol. Start at L1 and only move up when the current layer is confirmed working. Most problems are found at L1-L3.",
    triggerPhrase: "OSI bottom-up: Physical > Data Link > Network > Transport > Application; confirm each layer before moving up",
    weaknessTags: ["wired-tshooting"],
  },
  {
    id: "tn-73-14", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A user cannot connect to a website by name (www.example.com) but CAN successfully ping the website's IP address (93.184.216.34). What is the problem?",
    choices: [
      { id: "a", text: "The website's server is down", correct: false },
      { id: "b", text: "DNS resolution is failing — the client cannot resolve the hostname to an IP address", correct: true },
      { id: "c", text: "The user's firewall is blocking HTTP traffic", correct: false },
      { id: "d", text: "The network cable has a physical fault", correct: false },
    ],
    explanation: "If ping by IP works but ping/browse by name fails, DNS is the problem — the network path is fine. Troubleshoot: run nslookup www.example.com to see if DNS returns an answer. Check ipconfig /all to verify the DNS server IP is correct. Try an alternate DNS server (8.8.8.8 or 1.1.1.1). Run ipconfig /flushdns to clear the local DNS cache. Check if the DNS server is reachable (ping the DNS IP). On Windows, hosts file (C:\Windows\System32\drivers\etc\hosts) overrides DNS — check for malicious entries.",
    triggerPhrase: "Ping IP works, ping name fails = DNS problem; run nslookup, check DNS IP in ipconfig, try 8.8.8.8, flush DNS cache",
    weaknessTags: ["wired-tshooting", "dns-records"],
  },
  {
    id: "tn-73-15", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A wireless laptop shows 'Limited connectivity' after connecting to Wi-Fi, and ipconfig shows 169.254.x.x. Other wireless clients on the same AP work fine. What is the MOST likely issue?",
    choices: [
      { id: "a", text: "The AP does not have internet access from the ISP", correct: false },
      { id: "b", text: "The laptop's DHCP client is not functioning correctly, or the DHCP scope is exhausted for that segment", correct: true },
      { id: "c", text: "The Wi-Fi password was entered incorrectly", correct: false },
      { id: "d", text: "The AP is using the wrong wireless channel", correct: false },
    ],
    explanation: "169.254.x.x with 'Limited connectivity' means DHCP failed for this specific client. Since other clients work fine: the AP and DHCP server are functioning. Possible causes: DHCP scope exhausted (all IPs leased — check DHCP server lease count); DHCP client service on the laptop is stopped (services.msc > DHCP Client); laptop's MAC address is blocked by MAC filtering; corrupted TCP/IP stack. Fix: restart DHCP Client service, run netsh winsock reset, run netsh int ip reset, or check DHCP scope for available leases.",
    triggerPhrase: "169.254 on one client while others work = DHCP scope full OR client DHCP service stopped OR MAC filter",
    weaknessTags: ["wireless-tshooting", "dhcp-process"],
  },
];
'@
$result = $trimmed + $newQuestions
[System.IO.File]::WriteAllText($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Batch D done. Total lines: $((Get-Content $file).Count)"
