$file = "c:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$trimmed = $content.TrimEnd().Substring(0, $content.TrimEnd().LastIndexOf('];'))
$newQuestions = @'

  // -- 2.1 Cables and Connectors -----------------------------------------------
  {
    id: "cc-21-01", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the maximum data transfer speed of USB 2.0?",
    choices: [
      { id: "a", text: "12 Mbps", correct: false },
      { id: "b", text: "480 Mbps", correct: true },
      { id: "c", text: "5 Gbps", correct: false },
      { id: "d", text: "1.5 Mbps", correct: false },
    ],
    explanation: "USB 2.0 (High Speed) operates at 480 Mbps. USB 1.1 Low Speed = 1.5 Mbps; Full Speed = 12 Mbps. USB 3.0 (SuperSpeed) = 5 Gbps. USB 3.1 Gen 2 = 10 Gbps. USB 3.2 Gen 2x2 = 20 Gbps. USB4 = 40 Gbps. The 480 Mbps figure is heavily tested on the A+ exam.",
    triggerPhrase: "USB 2.0 = 480 Mbps (High Speed); USB 3.0 = 5 Gbps; USB 3.1 Gen 2 = 10 Gbps",
    weaknessTags: ["usb-standards"],
  },
  {
    id: "cc-21-02", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the maximum transfer speed of USB 3.0 (also called USB 3.2 Gen 1)?",
    choices: [
      { id: "a", text: "480 Mbps", correct: false },
      { id: "b", text: "5 Gbps", correct: true },
      { id: "c", text: "10 Gbps", correct: false },
      { id: "d", text: "40 Gbps", correct: false },
    ],
    explanation: "USB 3.0 was rebranded USB 3.2 Gen 1 (SuperSpeed) = 5 Gbps. USB 3.1 Gen 2 = 10 Gbps (SuperSpeed+). USB 3.2 Gen 2x2 = 20 Gbps. USB4 = 40 Gbps. The blue color on Type-A ports typically indicates USB 3.x. Speeds apply regardless of connector type (Type-A, Type-B, or Type-C).",
    triggerPhrase: "USB 3.0 = 5 Gbps (blue port); USB 3.1 Gen 2 = 10 Gbps; USB4 = 40 Gbps",
    weaknessTags: ["usb-standards"],
  },
  {
    id: "cc-21-03", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which USB connector type is ALWAYS reversible (can be inserted either way) and also supports Power Delivery and video output via Alt Mode?",
    choices: [
      { id: "a", text: "USB Type-A", correct: false },
      { id: "b", text: "USB Type-B", correct: false },
      { id: "c", text: "USB Type-C", correct: true },
      { id: "d", text: "USB Micro-B", correct: false },
    ],
    explanation: "USB Type-C is the 24-pin oval reversible connector. It supports USB Power Delivery (up to 240W in USB PD 3.1), DisplayPort Alt Mode, HDMI Alt Mode, and Thunderbolt 3/4. Type-A is the flat rectangular USB-A connector (not reversible). Type-B is the square connector used on printers and older peripherals. Micro-B is used on older Android phones. Type-C is now the universal standard.",
    triggerPhrase: "USB Type-C = reversible + Power Delivery + Alt Mode (DP/HDMI) + TB3/TB4",
    weaknessTags: ["usb-standards"],
  },
  {
    id: "cc-21-04", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "A technician needs to connect a new laser printer to a computer. The printer uses a square-shaped USB port. Which USB connector type does the printer use?",
    choices: [
      { id: "a", text: "USB Type-A", correct: false },
      { id: "b", text: "USB Type-B", correct: true },
      { id: "c", text: "USB Type-C", correct: false },
      { id: "d", text: "USB Mini-B", correct: false },
    ],
    explanation: "USB Type-B has a square/trapezoidal shape and is used on the device side of printers, scanners, and some audio interfaces. The computer side uses Type-A. USB Type-B 3.0 has an extra 5-pin block on top for SuperSpeed. Mini-B (5-pin) was used on cameras and older devices. Micro-B (5-pin, thin) was used on older Android phones. Type-B on printer = square connector.",
    triggerPhrase: "USB Type-B (square) = printer/scanner device-side port",
    weaknessTags: ["usb-standards"],
  },
  {
    id: "cc-21-05", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which display connector standard supports daisy-chaining multiple monitors from a single port using Multi-Stream Transport (MST)?",
    choices: [
      { id: "a", text: "HDMI 2.0", correct: false },
      { id: "b", text: "DVI-D", correct: false },
      { id: "c", text: "DisplayPort", correct: true },
      { id: "d", text: "VGA", correct: false },
    ],
    explanation: "DisplayPort's Multi-Stream Transport (MST) allows multiple monitors to be daisy-chained from one DisplayPort output, with each display receiving its own independent video stream. HDMI does not support MST. DVI and VGA cannot daisy-chain. DisplayPort also supports higher resolutions and refresh rates — DP 1.4 supports 8K@60Hz and 4K@144Hz. Mini DisplayPort (Thunderbolt) uses the same signal.",
    triggerPhrase: "DisplayPort MST = daisy-chain multiple monitors from one port; HDMI cannot do this",
    weaknessTags: ["display-cables"],
  },
  {
    id: "cc-21-06", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the difference between DVI-D and DVI-I connectors?",
    choices: [
      { id: "a", text: "DVI-D supports dual-link; DVI-I supports only single-link", correct: false },
      { id: "b", text: "DVI-D carries only digital signal; DVI-I carries both digital and analog signal", correct: true },
      { id: "c", text: "DVI-D is for monitors; DVI-I is for projectors", correct: false },
      { id: "d", text: "They are functionally identical", correct: false },
    ],
    explanation: "DVI-D (Digital) carries only a digital signal. DVI-I (Integrated) carries both digital and analog signals — you can use a DVI-I to VGA adapter. DVI-A carries only analog. Dual-link variants of both DVI-D and DVI-I exist, doubling bandwidth (supports up to 2560x1600). The physical difference: DVI-I has 4 extra analog pins (the cross shape) around the flat blade pin that DVI-D lacks.",
    triggerPhrase: "DVI-D = digital only; DVI-I = digital + analog (has 4 extra pins); DVI-A = analog only",
    weaknessTags: ["display-cables"],
  },
  {
    id: "cc-21-07", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Thunderbolt 3 and Thunderbolt 4 both use which connector type and what is their maximum bandwidth?",
    choices: [
      { id: "a", text: "USB Type-A, 20 Gbps", correct: false },
      { id: "b", text: "USB Type-C, 40 Gbps", correct: true },
      { id: "c", text: "Mini DisplayPort, 40 Gbps", correct: false },
      { id: "d", text: "USB Type-C, 20 Gbps", correct: false },
    ],
    explanation: "Both Thunderbolt 3 and Thunderbolt 4 use the USB Type-C connector and support 40 Gbps bidirectional bandwidth. Thunderbolt 4 tightens minimum requirements: two 4K displays or one 8K, PCIe 3.0 x4, 100W USB PD charging. TB4 is backward compatible with TB3. USB4 (also USB-C, 40 Gbps) is based on TB3 specs and is interoperable. Earlier Thunderbolt 1 and 2 used Mini DisplayPort.",
    triggerPhrase: "Thunderbolt 3 & 4 = USB-C connector, 40 Gbps; TB4 requires stricter feature minimums than TB3",
    weaknessTags: ["thunderbolt"],
  },
  {
    id: "cc-21-08", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the maximum theoretical speed of SATA III (the current standard SATA revision)?",
    choices: [
      { id: "a", text: "1.5 Gbps", correct: false },
      { id: "b", text: "3.0 Gbps", correct: false },
      { id: "c", text: "6.0 Gbps", correct: true },
      { id: "d", text: "10 Gbps", correct: false },
    ],
    explanation: "SATA revision progression: SATA I = 1.5 Gbps; SATA II = 3.0 Gbps; SATA III = 6.0 Gbps (real-world ~550 MB/s for SSDs). All revisions use the same 7-pin data connector and 15-pin power connector and are backward compatible. NVMe over PCIe is the successor — PCIe 3.0 x4 = ~3,500 MB/s, far exceeding SATA III.",
    triggerPhrase: "SATA I=1.5 Gbps, SATA II=3 Gbps, SATA III=6 Gbps; NVMe/PCIe is ~7x faster",
    weaknessTags: ["sata-interface"],
  },
  {
    id: "cc-21-09", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is eSATA and what advantage does it have over USB 2.0 for external storage?",
    choices: [
      { id: "a", text: "eSATA is a wireless SATA standard with 10 Gbps speeds", correct: false },
      { id: "b", text: "eSATA extends SATA to external devices at full SATA speeds (up to 6 Gbps), with no protocol overhead unlike USB", correct: true },
      { id: "c", text: "eSATA adds encryption to standard SATA connections", correct: false },
      { id: "d", text: "eSATA is an older standard limited to 1.5 Gbps", correct: false },
    ],
    explanation: "eSATA (External SATA) uses a shielded, more robust connector to extend SATA to external drives at native SATA speeds (up to 6 Gbps with SATA III). It doesn't include power delivery (a separate cable is needed) unlike USB. eSATAp (Power over eSATA) adds 5V/12V power. eSATA was popular before USB 3.0 became widespread. It supports hot-swapping when the controller enables it.",
    triggerPhrase: "eSATA = external SATA, no protocol overhead, no power delivery, full SATA speed",
    weaknessTags: ["sata-interface"],
  },
  {
    id: "cc-21-10", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "A Molex connector provides which voltages and what type of devices does it commonly power?",
    choices: [
      { id: "a", text: "3.3V and 5V; used for RAM modules", correct: false },
      { id: "b", text: "5V and 12V; used for older HDDs, optical drives, and case fans", correct: true },
      { id: "c", text: "12V only; used exclusively for GPU power", correct: false },
      { id: "d", text: "5V only; used for low-power USB accessories", correct: false },
    ],
    explanation: "The Molex 4-pin connector (also called Molex LP4) provides +5V (red wire) and +12V (yellow wire) with two ground wires (black). It was the standard HDD and optical drive power connector before SATA power replaced it. Still found on case fans, LED strips, fan controllers, and some older peripherals. A 4-pin Molex to SATA power adapter is common. SATA power connector (15-pin) also provides 3.3V.",
    triggerPhrase: "Molex 4-pin = 5V + 12V; used for older HDDs, optical drives, fans",
    weaknessTags: ["sata-interface"],
  },
  {
    id: "cc-21-11", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which display cable standard supports 4K resolution at 120Hz or higher refresh rates AND carries audio without an adapter?",
    choices: [
      { id: "a", text: "DVI-D Dual Link", correct: false },
      { id: "b", text: "HDMI 2.1", correct: true },
      { id: "c", text: "VGA", correct: false },
      { id: "d", text: "DisplayPort 1.0", correct: false },
    ],
    explanation: "HDMI 2.1 supports 4K at up to 144Hz (10K at 120Hz max), eARC for audio, VRR (variable refresh rate), and ALLM. HDMI 2.0 supports 4K@60Hz. DVI-D Dual Link can push 2560x1600@60Hz but carries no audio. VGA is analog with no audio. DisplayPort 1.4 supports 4K@144Hz and audio. The key distinction: HDMI 2.1 is needed for 4K gaming monitors at 120/144Hz over HDMI.",
    triggerPhrase: "HDMI 2.1 = 4K@144Hz + audio; HDMI 2.0 = 4K@60Hz; DVI = no audio",
    weaknessTags: ["display-cables"],
  },
  {
    id: "cc-21-12", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "Apple's proprietary 8-pin reversible connector used on iPhones and iPads before the USB-C transition is called:",
    choices: [
      { id: "a", text: "USB Micro-B", correct: false },
      { id: "b", text: "Thunderbolt 1", correct: false },
      { id: "c", text: "Lightning", correct: true },
      { id: "d", text: "USB Mini-B", correct: false },
    ],
    explanation: "Lightning is Apple's proprietary 8-pin reversible connector introduced in 2012, replacing the 30-pin dock connector. It supports USB 2.0 speeds (480 Mbps) and can carry audio via adapters. Apple transitioned to USB Type-C starting with the iPhone 15 (2023) following EU regulations. Lightning is still found on older iPhones, AirPods, and accessories. Not compatible with USB standards without an adapter.",
    triggerPhrase: "Lightning = Apple's 8-pin reversible connector (pre-iPhone 15); USB 2.0 speed only",
    weaknessTags: ["usb-standards"],
  },
  {
    id: "cc-21-13", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "How many pins does a standard SATA data cable have, and how many does a SATA power cable have?",
    choices: [
      { id: "a", text: "Data: 4 pins; Power: 7 pins", correct: false },
      { id: "b", text: "Data: 7 pins; Power: 15 pins", correct: true },
      { id: "c", text: "Data: 9 pins; Power: 4 pins", correct: false },
      { id: "d", text: "Both use 15-pin connectors", correct: false },
    ],
    explanation: "SATA data cable: 7 pins (3 ground + 4 signal), L-shaped latch, max 1 meter. SATA power cable: 15 pins providing 3.3V (orange), 5V (red), and 12V (yellow) with associated ground wires. The L-shape on both connectors ensures correct orientation (keyed). SATA power replaced the older 4-pin Molex for drives. Some SSDs only need 5V and 3.3V; the 12V pins may not be present on smaller SATA power connectors.",
    triggerPhrase: "SATA data = 7-pin; SATA power = 15-pin (3.3V/5V/12V)",
    weaknessTags: ["sata-interface"],
  },
  {
    id: "cc-21-14", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A user wants to connect an external NVMe SSD enclosure for the fastest possible transfer speeds. Which interface should the enclosure use?",
    choices: [
      { id: "a", text: "USB 2.0 Type-A", correct: false },
      { id: "b", text: "SATA III via eSATA", correct: false },
      { id: "c", text: "USB4 / Thunderbolt 4 via USB Type-C", correct: true },
      { id: "d", text: "USB 3.0 Type-A", correct: false },
    ],
    explanation: "USB4/Thunderbolt 4 via USB-C provides 40 Gbps bandwidth, which is sufficient to fully utilize NVMe SSD speeds (typically up to 7,000 MB/s for PCIe 4.0). USB 3.0 at 5 Gbps and eSATA at 6 Gbps would bottleneck the NVMe drive. USB 3.2 Gen 2x2 at 20 Gbps is better but still limiting for top-end NVMe. TB3/TB4 and USB4 40 Gbps enclosures are the current standard for high-performance external NVMe storage.",
    triggerPhrase: "Fastest external NVMe = USB4/Thunderbolt 4 (40 Gbps via USB-C)",
    weaknessTags: ["thunderbolt", "usb-standards"],
  },
  {
    id: "cc-21-15", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A monitor's HDMI 2.0 port is connected to a PC's GPU. The maximum resolution and refresh rate achievable over HDMI 2.0 is:",
    choices: [
      { id: "a", text: "1080p at 60Hz", correct: false },
      { id: "b", text: "4K at 60Hz", correct: true },
      { id: "c", text: "4K at 144Hz", correct: false },
      { id: "d", text: "8K at 60Hz", correct: false },
    ],
    explanation: "HDMI 2.0 supports 4K (3840x2160) at 60Hz with 18 Gbps bandwidth. For 4K at 144Hz you need HDMI 2.1 (48 Gbps) or DisplayPort 1.4. HDMI 1.4 supports 4K at 30Hz. Many gaming monitors and TVs marketed as '4K 144Hz' require HDMI 2.1 or DP 1.4 — verify the port version on both the GPU and display when purchasing.",
    triggerPhrase: "HDMI 2.0 = 4K@60Hz max; HDMI 2.1 = 4K@144Hz; DP 1.4 = 4K@144Hz",
    weaknessTags: ["display-cables"],
  },

  // -- 3.1 Power Supplies and Cooling ------------------------------------------
  {
    id: "ps-31-01", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What does the '80 PLUS' certification on a power supply indicate?",
    choices: [
      { id: "a", text: "The PSU can deliver 80% of its rated wattage continuously", correct: false },
      { id: "b", text: "The PSU operates at 80% or greater electrical efficiency at 20%, 50%, and 100% load", correct: true },
      { id: "c", text: "The PSU has 80 watts of headroom above its rated capacity", correct: false },
      { id: "d", text: "The PSU can withstand 80-degree Celsius operating temperatures", correct: false },
    ],
    explanation: "80 PLUS certification means the PSU converts AC to DC at 80% efficiency or better at three load points (20%, 50%, 100%). A 500W 80+ PSU wastes at most 20% of power as heat — so it draws 625W from the wall to deliver 500W. Tiers: 80 PLUS (80%), Bronze (82-85%), Silver (85-88%), Gold (87-92%), Platinum (90-92%), Titanium (92-94%). Higher efficiency = lower electricity cost + less heat.",
    triggerPhrase: "80 PLUS = at least 80% efficiency; tiers Bronze/Silver/Gold/Platinum/Titanium go up from there",
    weaknessTags: ["psu-wattage"],
  },
  {
    id: "ps-31-02", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "When calculating the minimum PSU wattage for a new build, a technician should add together the power draw of all components and then:",
    choices: [
      { id: "a", text: "Use that exact number as the PSU rating", correct: false },
      { id: "b", text: "Add 20-30% headroom for efficiency loss and future upgrades", correct: true },
      { id: "c", text: "Divide by 0.8 and subtract 50 watts", correct: false },
      { id: "d", text: "Double the total to ensure reliability", correct: false },
    ],
    explanation: "After summing component TDPs (CPU + GPU being the largest consumers), add 20-30% headroom. This accounts for: PSU efficiency loss (even an 80+ Gold wastes some power), peak/transient loads (GPU boost states can spike), future upgrades, and capacitor aging reducing effective wattage over time. A system drawing 400W in practice should use a 500-550W PSU minimum. Online PSU calculators from PCPartPicker or OuterVision are useful for this.",
    triggerPhrase: "PSU wattage = sum of all component TDPs + 20-30% headroom",
    weaknessTags: ["psu-wattage"],
  },
  {
    id: "ps-31-03", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "Which connector provides the primary power to the motherboard in an ATX system?",
    choices: [
      { id: "a", text: "8-pin EPS connector", correct: false },
      { id: "b", text: "6-pin PCIe connector", correct: false },
      { id: "c", text: "24-pin ATX connector", correct: true },
      { id: "d", text: "4-pin Molex connector", correct: false },
    ],
    explanation: "The 24-pin ATX main power connector (20+4 pin on most PSUs for backward compatibility with older 20-pin motherboards) delivers 3.3V, 5V, 12V, 5VSB (standby), and power-good signal. It's the primary power source for the motherboard. An older 20-pin connector omits 4 pins; 20-pin PSUs cannot power modern motherboards. The 24-pin was standardized in ATX12V 2.x.",
    triggerPhrase: "24-pin ATX = main motherboard power (provides 3.3V, 5V, 12V to board)",
    weaknessTags: ["psu-connectors"],
  },
  {
    id: "ps-31-04", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the purpose of the 8-pin EPS12V connector (sometimes split as 4+4) on modern motherboards?",
    choices: [
      { id: "a", text: "Provides power to the PCIe x16 GPU slot", correct: false },
      { id: "b", text: "Provides dedicated 12V power to the CPU voltage regulator module", correct: true },
      { id: "c", text: "Powers the 24-pin ATX rail as a supplement", correct: false },
      { id: "d", text: "Connects to the case front-panel power button", correct: false },
    ],
    explanation: "The 8-pin EPS12V (or 4+4 pin CPU power) connector supplies dedicated +12V current to the CPU's Voltage Regulator Module (VRM) on the motherboard. High-end motherboards may require two 8-pin connectors (for overclocking). Without it, the system won't POST (or in some cases will beep repeatedly). The 4+4 split design allows compatibility with older 4-pin CPU power motherboards.",
    triggerPhrase: "8-pin EPS (4+4) = CPU power; 24-pin = motherboard power — both required for POST",
    weaknessTags: ["psu-connectors"],
  },
  {
    id: "ps-31-05", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A high-end discrete GPU requires an 8-pin PCIe power connector. How much power can an 8-pin PCIe connector deliver?",
    choices: [
      { id: "a", text: "75 watts", correct: false },
      { id: "b", text: "150 watts", correct: true },
      { id: "c", text: "225 watts", correct: false },
      { id: "d", text: "300 watts", correct: false },
    ],
    explanation: "PCIe power connector ratings: 6-pin = 75W; 8-pin (6+2) = 150W. The PCIe slot itself provides an additional 75W, so a GPU with one 8-pin connector can receive up to 225W total from slot + connector. Dual 8-pin = 300W + 75W slot = 375W total. Some GPUs use a 16-pin (12VHPWR) connector for up to 600W. The 6+2 pin design means the 8-pin PCIe can also mate with 6-pin ports.",
    triggerPhrase: "PCIe 6-pin = 75W; PCIe 8-pin = 150W; GPU slot = 75W; add together for total GPU power",
    weaknessTags: ["psu-connectors"],
  },
  {
    id: "ps-31-06", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the main advantage of a fully modular PSU over a non-modular PSU?",
    choices: [
      { id: "a", text: "Modular PSUs are always more efficient", correct: false },
      { id: "b", text: "Modular PSUs have higher wattage ratings", correct: false },
      { id: "c", text: "Modular PSUs allow unused cables to be removed, improving airflow and cable management", correct: true },
      { id: "d", text: "Modular PSUs do not require grounding", correct: false },
    ],
    explanation: "A fully modular PSU has all cables detachable — only connect what is needed. This eliminates cable clutter, improves airflow inside the case, and makes builds cleaner. Semi-modular PSUs have the essential cables (24-pin, CPU power) hardwired with others detachable. Non-modular (fixed) PSUs have all cables permanently attached. Efficiency rating is determined by the 80 PLUS tier, not whether the PSU is modular.",
    triggerPhrase: "Modular PSU = detachable cables, better airflow; efficiency is from 80 PLUS rating, not modularity",
    weaknessTags: ["psu-types"],
  },
  {
    id: "ps-31-07", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A server is configured with two power supplies for redundancy. If one PSU fails, the server continues operating. What type of redundancy configuration is this?",
    choices: [
      { id: "a", text: "Load balancing with failover", correct: false },
      { id: "b", text: "N+1 redundant PSU (hot-swappable)", correct: true },
      { id: "c", text: "RAID 1 power configuration", correct: false },
      { id: "d", text: "Passive standby", correct: false },
    ],
    explanation: "N+1 PSU redundancy means N PSUs are needed to run the server + 1 spare. Both PSUs share the load during normal operation; if one fails, the other takes full load without interruption. Hot-swappable design allows the failed PSU to be replaced without powering off the server. This is standard in enterprise servers. Some configurations use 2N (fully redundant separate power paths), which is even more fault-tolerant.",
    triggerPhrase: "Redundant PSU = N+1 hot-swap; both share load; one failure = no downtime",
    weaknessTags: ["psu-types"],
  },
  {
    id: "ps-31-08", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Thermal paste should be applied between the CPU and heat sink. What is the PRIMARY purpose of thermal paste (thermal interface material)?",
    choices: [
      { id: "a", text: "It bonds the heat sink permanently to the CPU IHS", correct: false },
      { id: "b", text: "It fills microscopic air gaps between the CPU and heat sink surface to maximize heat transfer", correct: true },
      { id: "c", text: "It provides electrical insulation between the CPU and heat sink", correct: false },
      { id: "d", text: "It increases the thermal mass of the CPU package", correct: false },
    ],
    explanation: "Both the CPU Integrated Heat Spreader (IHS) and heat sink base appear smooth but have microscopic surface irregularities. Air in these gaps is a poor thermal conductor. Thermal paste (TIM) fills these gaps with a conductive compound (silicone with metal oxide or liquid metal) to maximize heat transfer from CPU to heat sink. Too little = hot spots; too much = can spread over socket pins. A small pea-sized dot in center is the standard method.",
    triggerPhrase: "Thermal paste fills microscopic air gaps between CPU IHS and heat sink for better heat transfer",
    weaknessTags: ["cooling-systems"],
  },
  {
    id: "ps-31-09", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What are the main components of a closed-loop AIO (All-In-One) liquid cooling system?",
    choices: [
      { id: "a", text: "Pump, water block, reservoir, radiator, and fans", correct: true },
      { id: "b", text: "Compressor, evaporator, condenser, and refrigerant lines", correct: false },
      { id: "c", text: "Phase-change unit, heat pipes, and vapor chamber", correct: false },
      { id: "d", text: "Peltier element, cold plate, and heat sink", correct: false },
    ],
    explanation: "An AIO liquid cooler contains: CPU water block (absorbs CPU heat into liquid), pump (circulates coolant), radiator (dissipates heat to air), fans (push air through radiator), and pre-filled tubing. Custom/open loops add a separate reservoir for coolant capacity and add-fill convenience. Phase-change cooling uses refrigerants like an air conditioner. AIOs are simpler to install than custom loops but less upgradable.",
    triggerPhrase: "AIO liquid cooling: water block + pump + radiator + fans (closed loop, no user-filled reservoir)",
    weaknessTags: ["cooling-systems"],
  },
  {
    id: "ps-31-10", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "For optimal airflow in a PC case, which fan placement strategy is considered best practice?",
    choices: [
      { id: "a", text: "All fans blowing outward (exhaust) to create negative pressure", correct: false },
      { id: "b", text: "All fans blowing inward (intake) to create positive pressure", correct: false },
      { id: "c", text: "Front/bottom as intake, rear/top as exhaust, creating a front-to-back airflow path", correct: true },
      { id: "d", text: "Random placement for equal pressure in all directions", correct: false },
    ],
    explanation: "Best practice: cool air enters from front/bottom (intake) and exits through rear/top (exhaust), creating a linear front-to-back flow path through the case. This moves heat away from CPU, GPU, and storage. Slight positive pressure (more intake than exhaust CFM) reduces dust ingress through gaps. Negative pressure creates more turbulence and pulls dust through unfiltered gaps. Match fan rotational direction to its intended intake/exhaust role.",
    triggerPhrase: "Case airflow: front/bottom = intake, rear/top = exhaust; front-to-back flow path",
    weaknessTags: ["cooling-systems"],
  },
  {
    id: "ps-31-11", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is TDP (Thermal Design Power) in the context of CPUs and cooling?",
    choices: [
      { id: "a", text: "The absolute maximum power a CPU will ever consume", correct: false },
      { id: "b", text: "The amount of heat (in watts) a cooling solution must be able to dissipate for stable operation at base clock speeds", correct: true },
      { id: "c", text: "The total power draw of the entire computer system", correct: false },
      { id: "d", text: "The wattage required for the CPU voltage regulator", correct: false },
    ],
    explanation: "TDP (Thermal Design Power) is the maximum sustained heat output a cooling solution must handle, measured in watts, when the CPU runs at its base (non-boost) frequency under a sustained workload. A cooler's TDP rating must equal or exceed the CPU's TDP. Note: modern CPUs can exceed their TDP significantly during boost states, so higher-rated coolers provide safety margin. TDP also serves as a rough approximation for power consumption.",
    triggerPhrase: "TDP = heat output cooling system must handle (watts); cooler TDP rating must meet or exceed CPU TDP",
    weaknessTags: ["cooling-systems"],
  },
  {
    id: "ps-31-12", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the difference between a PWM fan and a DC fan in terms of speed control?",
    choices: [
      { id: "a", text: "PWM fans use 3-pin connectors; DC fans use 4-pin connectors", correct: false },
      { id: "b", text: "PWM controls fan speed by varying the duty cycle of a fixed-voltage signal; DC controls speed by varying the voltage", correct: true },
      { id: "c", text: "PWM fans are always louder than DC fans", correct: false },
      { id: "d", text: "There is no functional difference; the terms are interchangeable", correct: false },
    ],
    explanation: "PWM (Pulse Width Modulation) fans use a 4-pin connector. Speed is controlled by a separate PWM signal pin that varies the duty cycle (percentage of time power is on) at 25 kHz while voltage stays constant at 12V. This gives precise, low-speed control without the fan stalling. DC fans use a 3-pin connector; speed is controlled by changing the voltage (7V to 12V). PWM offers smoother control at low speeds and is preferred for modern systems.",
    triggerPhrase: "PWM (4-pin) = duty-cycle speed control at fixed voltage; DC (3-pin) = variable voltage speed control",
    weaknessTags: ["cooling-systems"],
  },
  {
    id: "ps-31-13", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "A user reports their PC immediately shuts off after being used for about 20 minutes and then works fine after sitting for a while. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The power supply is underpowered for the components", correct: false },
      { id: "b", text: "Thermal shutdown due to CPU or GPU overheating", correct: true },
      { id: "c", text: "A failing hard drive causing OS crashes", correct: false },
      { id: "d", text: "RAM errors causing random reboots", correct: false },
    ],
    explanation: "The pattern of working fine at first, then shutting down after warming up, then recovering after cooling — is a classic thermal shutdown signature. CPUs and GPUs have thermal protection that forces an emergency shutdown to prevent permanent damage. Causes: dried thermal paste, blocked/failed CPU fan or case fan, heatsink not properly seated, dust-clogged heatsink fins, or fan failure. Check temperatures using HWMonitor or Core Temp while running.",
    triggerPhrase: "Works then shuts down after 20 min + recovers after cooling = thermal shutdown (check fans and thermal paste)",
    weaknessTags: ["cooling-systems", "psu-troubleshoot"],
  },
  {
    id: "ps-31-14", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A PSU is rated at 650W with 80 PLUS Gold efficiency (typically 90% at 50% load). When the system draws 325W, approximately how much power does the PSU draw from the wall outlet?",
    choices: [
      { id: "a", text: "325W", correct: false },
      { id: "b", text: "360W", correct: true },
      { id: "c", text: "500W", correct: false },
      { id: "d", text: "650W", correct: false },
    ],
    explanation: "At 90% efficiency, the PSU must draw 325W / 0.90 = ~361W from the wall to deliver 325W to the system (the other ~36W is lost as heat). The 650W rating is its maximum delivery capacity, not its constant draw. This is why 80 PLUS matters: a Bronze PSU at the same load might be 85% efficient, drawing 382W. The 10% difference in efficiency means less heat inside the PSU and lower electricity costs.",
    triggerPhrase: "Wall draw = system load / efficiency (325W / 0.90 = 361W from wall at 90% Gold efficiency)",
    weaknessTags: ["psu-wattage"],
  },
  {
    id: "ps-31-15", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "A server data center requires that power supplies be replaceable while the server is running, without any downtime. Which PSU feature enables this?",
    choices: [
      { id: "a", text: "80 PLUS Platinum efficiency rating", correct: false },
      { id: "b", text: "Fully modular cable design", correct: false },
      { id: "c", text: "Hot-swappable redundant power supply", correct: true },
      { id: "d", text: "High-wattage capacity (2000W+)", correct: false },
    ],
    explanation: "Hot-swappable PSUs can be removed and replaced while the server remains powered on, because the second redundant PSU takes the full load during the swap. This is a critical feature for enterprise servers that cannot tolerate downtime. Hot-swap requires: redundant N+1 configuration, PSUs sharing load via parallel connectors, and a backplane design that safely disconnects one PSU while the other continues operating. Modular cable design and efficiency ratings are independent features.",
    triggerPhrase: "Hot-swap redundant PSU = replace while server is running; requires N+1 redundant design",
    weaknessTags: ["psu-types"],
  },
];
'@
$result = $trimmed + $newQuestions
[System.IO.File]::WriteAllText($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Batch A done. Total lines: $((Get-Content $file).Count)"
