$file = "c:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$trimmed = $content.TrimEnd().Substring(0, $content.TrimEnd().LastIndexOf('];'))
$newQuestions = @'

  // -- 6.1 Internet Connection Types -------------------------------------------
  {
    id: "ic-61-01", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the key difference between ADSL and SDSL?",
    choices: [
      { id: "a", text: "ADSL uses fiber; SDSL uses copper phone lines", correct: false },
      { id: "b", text: "ADSL provides asymmetric speeds (faster download than upload); SDSL provides equal upload and download speeds", correct: true },
      { id: "c", text: "ADSL requires a cable modem; SDSL uses a DSL modem", correct: false },
      { id: "d", text: "SDSL is newer and completely replaced ADSL", correct: false },
    ],
    explanation: "DSL types: ADSL (Asymmetric DSL): download faster than upload (e.g., 24 Mbps down / 3 Mbps up). Ideal for residential users who download more than they upload. SDSL (Symmetric DSL): equal upload and download speeds. More expensive, targeted at businesses that need to host servers or upload large files regularly. VDSL (Very-high-speed DSL) is asymmetric with much higher speeds but requires being close to the central office (CO) or a fiber node.",
    triggerPhrase: "ADSL = asymmetric (faster down than up, residential); SDSL = symmetric (equal up/down, business)",
    weaknessTags: ["dsl-types", "internet-conn-types"],
  },
  {
    id: "ic-61-02", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Cable internet uses which technology standard to deliver data over the same coaxial cable as TV signals?",
    choices: [
      { id: "a", text: "PPPoE", correct: false },
      { id: "b", text: "DOCSIS", correct: true },
      { id: "c", text: "ATM over DSL", correct: false },
      { id: "d", text: "FTTH with ONT", correct: false },
    ],
    explanation: "DOCSIS (Data Over Cable Service Interface Specification) defines how data is transmitted over the same HFC (Hybrid Fiber-Coaxial) network used for cable TV. DOCSIS 3.0: 1.2 Gbps down / 200 Mbps up. DOCSIS 3.1 (current standard): 10 Gbps down / 1-2 Gbps up using OFDM. DOCSIS 4.0 (emerging): 10 Gbps symmetrical. Cable internet is shared — subscribers in the same neighborhood share bandwidth from the node, unlike dedicated DSL.",
    triggerPhrase: "Cable internet = DOCSIS over HFC (coax + fiber); DOCSIS 3.1 = 10 Gbps down; bandwidth is shared",
    weaknessTags: ["docsis", "internet-conn-types"],
  },
  {
    id: "ic-61-03", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is FTTC (Fiber to the Curb) and how does it differ from FTTP (Fiber to the Premises)?",
    choices: [
      { id: "a", text: "FTTC uses fiber all the way to the customer; FTTP uses copper for the last mile", correct: false },
      { id: "b", text: "FTTC runs fiber to a street cabinet and then copper for the final connection; FTTP runs fiber all the way to the customer building", correct: true },
      { id: "c", text: "FTTC and FTTP are identical technologies with different marketing names", correct: false },
      { id: "d", text: "FTTC is for commercial buildings; FTTP is for residential only", correct: false },
    ],
    explanation: "Fiber ISP deployment types: FTTC (Fiber to the Curb): fiber to a street cabinet (within ~300m of homes), then copper (VDSL2) for the final drop. Speeds limited by the copper section. FTTN (Fiber to the Node): fiber to a neighborhood cabinet (up to 1.5 km from homes), even more copper, lower speeds. FTTB (Fiber to the Building): fiber to the building, then Ethernet in-building. FTTP/FTTH (Fiber to the Premises/Home): fiber all the way, requires an ONT. Fastest and most future-proof.",
    triggerPhrase: "FTTC = fiber to curb + copper last drop; FTTP/FTTH = fiber all the way; FTTC is faster than FTTN",
    weaknessTags: ["fiber-isp-types"],
  },
  {
    id: "ic-61-04", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "When a home is connected via fiber-to-the-premises (FTTP), what device at the customer's location converts the fiber optical signal into an Ethernet connection?",
    choices: [
      { id: "a", text: "Cable modem", correct: false },
      { id: "b", text: "DSL modem", correct: false },
      { id: "c", text: "ONT (Optical Network Terminal)", correct: true },
      { id: "d", text: "DOCSIS splitter", correct: false },
    ],
    explanation: "An ONT (Optical Network Terminal) — also called an ONU (Optical Network Unit) — is the fiber equivalent of a modem. It terminates the fiber optic cable at the customer premises and converts the optical signal to electrical Ethernet (RJ-45) for the customer's router. ISPs that use fiber (like Verizon FiOS, Google Fiber, or AT&T Fiber) install an ONT on the side of the house or inside. The router then connects to the ONT's Ethernet port.",
    triggerPhrase: "ONT = fiber modem; converts optical signal to Ethernet at customer premises (required for FTTP/FTTH)",
    weaknessTags: ["fiber-isp-types"],
  },
  {
    id: "ic-61-05", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A customer in a rural area with no wired ISP options wants broadband internet. Fixed wireless internet is available. What is a key requirement for fixed wireless to work?",
    choices: [
      { id: "a", text: "The customer must have an existing cable TV subscription", correct: false },
      { id: "b", text: "Line-of-sight (or near-line-of-sight) between the customer's antenna and the tower", correct: true },
      { id: "c", text: "A fiber ONT must be installed at the building", correct: false },
      { id: "d", text: "The customer must be within 500 feet of a DSL central office", correct: false },
    ],
    explanation: "Fixed wireless internet uses licensed or unlicensed radio frequencies (often 5 GHz, 3.65 GHz, or CBRS) to connect a tower to a directional antenna mounted on the customer's building. Unlike cellular (omnidirectional), fixed wireless typically requires line-of-sight (LOS) or near-LOS to function effectively — trees, buildings, and terrain block the signal. Typical speeds: 25-100+ Mbps. Popular in rural and suburban areas without fiber or cable infrastructure.",
    triggerPhrase: "Fixed wireless = directional antenna, requires LOS to tower; common where cable/fiber not available",
    weaknessTags: ["internet-conn-types"],
  },
  {
    id: "ic-61-06", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "Traditional geostationary (GEO) satellite internet has a major disadvantage compared to terrestrial ISPs. What is it?",
    choices: [
      { id: "a", text: "It cannot support more than 1 Mbps download speed", correct: false },
      { id: "b", text: "Very high latency (550-600 ms round-trip) due to the 35,786 km altitude of GEO satellites", correct: true },
      { id: "c", text: "It requires an annual satellite phone subscription", correct: false },
      { id: "d", text: "It only works when it is clear weather outdoors", correct: false },
    ],
    explanation: "GEO satellites orbit at 35,786 km above Earth (geostationary). The round-trip signal travel time alone causes 550-600 ms latency, making real-time applications (VoIP, gaming, video calls) poor. Low Earth Orbit (LEO) satellite services like Starlink (SpaceX) orbit at ~550 km, achieving 25-40 ms latency — similar to terrestrial broadband. GEO satellite is still useful for remote areas where no other option exists. Rain fade (signal loss in heavy rain) also affects satellite services.",
    triggerPhrase: "GEO satellite = 550-600 ms latency (35,786 km altitude); LEO satellites (Starlink) = 25-40 ms",
    weaknessTags: ["internet-conn-types"],
  },
  {
    id: "ic-61-07", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the key technical difference between 4G LTE and 5G NR (New Radio) for mobile internet?",
    choices: [
      { id: "a", text: "5G uses the same frequencies as 4G but with better compression algorithms", correct: false },
      { id: "b", text: "5G uses higher frequencies (including millimeter wave) enabling much higher speeds but shorter range, while also using sub-6 GHz for broader coverage", correct: true },
      { id: "c", text: "4G supports video; 5G only supports voice and text", correct: false },
      { id: "d", text: "5G requires a wired backhaul connection to function", correct: false },
    ],
    explanation: "5G NR uses two frequency ranges: Sub-6 GHz (similar coverage to 4G LTE, 100-900 Mbps) and mmWave / millimeter wave (24-100 GHz): extremely fast (10+ Gbps) but very short range (~200m), blocked by buildings and windows. 4G LTE: 150-300 Mbps typical. 5G sub-6 is what most users experience. 5G also introduces network slicing, massive MIMO, and ultra-low latency (1-5 ms for network slice use cases like autonomous vehicles).",
    triggerPhrase: "5G NR: sub-6 GHz (wide coverage, 100-900 Mbps) + mmWave (ultra-fast, short range, blocked by walls)",
    weaknessTags: ["cellular-data"],
  },
  {
    id: "ic-61-08", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the purpose of a DSL filter (microfilter) installed on telephone line splitters?",
    choices: [
      { id: "a", text: "Boosts the DSL signal for longer cable runs", correct: false },
      { id: "b", text: "Separates the voice telephone frequencies from the DSL data frequencies on the same phone line", correct: true },
      { id: "c", text: "Encrypts the DSL data stream for security", correct: false },
      { id: "d", text: "Converts the analog phone signal to digital for DSL transmission", correct: false },
    ],
    explanation: "A DSL filter (or splitter) is placed on every telephone jack that has a phone or non-DSL device connected to it. It separates the voice band (0-4 kHz) from the DSL data band (25 kHz - 1.1 MHz) on the same physical copper pair. Without filters, DSL data signals would cause audible noise (hiss) on phone calls, and phone devices could interfere with DSL performance. The DSL modem line does NOT need a filter. Central splitters can handle all lines from one location.",
    triggerPhrase: "DSL filter = separates voice (0-4 kHz) from DSL data frequencies on phone line; install on every phone/device",
    weaknessTags: ["dsl-types"],
  },
  {
    id: "ic-61-09", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is PPPoE (Point-to-Point Protocol over Ethernet) and when is it used?",
    choices: [
      { id: "a", text: "PPPoE is a wireless encryption protocol for securing Wi-Fi connections", correct: false },
      { id: "b", text: "PPPoE is an authentication protocol used by DSL (and some fiber) ISPs that requires the router to log in with a username and password", correct: true },
      { id: "c", text: "PPPoE is a cable modem technology that replaced DOCSIS", correct: false },
      { id: "d", text: "PPPoE is a VPN protocol for site-to-site connections", correct: false },
    ],
    explanation: "PPPoE (Point-to-Point Protocol over Ethernet) encapsulates PPP frames within Ethernet frames, allowing the PPP authentication framework (username/password) to work over broadband. Many DSL providers (AT&T, CenturyLink, etc.) use PPPoE so customers must authenticate. Some fiber ISPs also use it. The DSL router is configured with the PPPoE credentials. Signs of PPPoE: router WAN type is set to PPPoE; DSL modem by itself won't connect without credentials.",
    triggerPhrase: "PPPoE = login protocol for DSL (username/password); router WAN mode set to PPPoE",
    weaknessTags: ["dsl-types"],
  },
  {
    id: "ic-61-10", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the fundamental difference between a modem and a router?",
    choices: [
      { id: "a", text: "A modem is wireless; a router is wired", correct: false },
      { id: "b", text: "A modem converts the ISP's signal (coax, phone line, fiber) to Ethernet; a router shares one internet connection among multiple devices via NAT", correct: true },
      { id: "c", text: "A router connects to the ISP directly; a modem is only for local networks", correct: false },
      { id: "d", text: "They are different names for the same device", correct: false },
    ],
    explanation: "Modem (modulator-demodulator): converts the ISP's physical signal — cable modem converts DOCSIS/coax, DSL modem converts phone-line signals, ONT converts fiber — to Ethernet. The modem talks to the ISP. Router: takes the single public IP from the modem and shares it among all home devices using NAT (Network Address Translation), and runs DHCP for private IP assignment. Most home users have a combined modem-router (gateway) from their ISP. In enterprise, these are always separate devices.",
    triggerPhrase: "Modem = converts ISP signal to Ethernet; Router = shares internet via NAT; ISP gateway = both in one",
    weaknessTags: ["internet-conn-types"],
  },
  {
    id: "ic-61-11", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What type of firewall inspects the state of network connections and allows or denies packets based on connection state, not just port/IP rules?",
    choices: [
      { id: "a", text: "Packet filter firewall", correct: false },
      { id: "b", text: "Stateful inspection firewall", correct: true },
      { id: "c", text: "Application layer firewall (proxy firewall)", correct: false },
      { id: "d", text: "Unified Threat Management (UTM) appliance", correct: false },
    ],
    explanation: "Firewall generations: Packet filter (1st gen): inspects individual packets by IP/port rules only; stateless. Stateful inspection (2nd gen): tracks TCP connection state table; allows return traffic from established connections automatically; blocks unsolicited inbound. Application layer / proxy firewall (3rd gen): inspects actual application payload (HTTP, FTP content); understands protocols. Next-Gen Firewall (NGFW): combines stateful + application inspection + IPS + user identity. Most modern firewalls are stateful at minimum.",
    triggerPhrase: "Stateful firewall = tracks connection state; allows established connection return traffic; blocks unsolicited inbound",
    weaknessTags: ["internet-conn-types"],
  },
  {
    id: "ic-61-12", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Cable internet bandwidth is described as 'shared.' What does this mean for users?",
    choices: [
      { id: "a", text: "Multiple users share the same username and password for internet access", correct: false },
      { id: "b", text: "Neighbors in the same node area share available bandwidth from the cable node, so speeds can slow during peak usage times", correct: true },
      { id: "c", text: "The cable modem shares bandwidth between upload and download equally", correct: false },
      { id: "d", text: "Each cable subscriber gets exactly 1/100th of the node's total capacity", correct: false },
    ],
    explanation: "Cable internet uses an HFC (Hybrid Fiber-Coaxial) network where a neighborhood node connects multiple homes. All subscribers in the same node share the node's bandwidth capacity. During peak hours (evening, weekends) when many neighbors are streaming simultaneously, speeds can drop significantly. DSL is dedicated (each subscriber gets their own pair from CO to home). Fiber ISPs typically offer dedicated bandwidth per subscriber. DOCSIS 3.1 nodes support multi-gigabit to help with sharing.",
    triggerPhrase: "Cable internet = shared neighborhood bandwidth from node; can slow during peak hours; DSL/fiber = dedicated",
    weaknessTags: ["docsis", "internet-conn-types"],
  },
  {
    id: "ic-61-13", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is tethering and which devices support it?",
    choices: [
      { id: "a", text: "Tethering is connecting two computers with a serial cable for file transfer", correct: false },
      { id: "b", text: "Tethering is using a smartphone's cellular data connection as an internet hotspot for other devices via Wi-Fi, USB, or Bluetooth", correct: true },
      { id: "c", text: "Tethering is a type of Bluetooth low-energy connection for IoT devices", correct: false },
      { id: "d", text: "Tethering is the process of bonding two ISP connections for increased bandwidth", correct: false },
    ],
    explanation: "Mobile tethering uses a smartphone's cellular data plan to provide internet access to other devices. Three methods: (1) Wi-Fi hotspot: phone acts as an AP; (2) USB tethering: phone connects via USB cable, appears as a network adapter; (3) Bluetooth tethering: slower, shorter range. Tethering may be restricted or have separate data limits depending on the carrier plan. 5G smartphones can provide very fast tethering speeds where 5G is available.",
    triggerPhrase: "Tethering = phone shares cellular data via Wi-Fi hotspot, USB, or Bluetooth to other devices",
    weaknessTags: ["cellular-data"],
  },
  {
    id: "ic-61-14", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "VDSL2 (Very-high-speed DSL 2) can achieve speeds up to 100 Mbps download, but performance depends heavily on which factor?",
    choices: [
      { id: "a", text: "The cable TV plan the customer subscribes to", correct: false },
      { id: "b", text: "Distance from the customer to the DSLAM (DSL Access Multiplexer) or fiber node", correct: true },
      { id: "c", text: "The number of devices connected to the DSL modem", correct: false },
      { id: "d", text: "Whether the customer has a 32-bit or 64-bit router", correct: false },
    ],
    explanation: "DSL speed is highly distance-sensitive due to signal attenuation on copper wire. VDSL2 at 100 Mbps requires being within ~300 meters of a DSLAM (often in a fiber-fed street cabinet). At 1 km, speeds drop to ~50 Mbps; at 1.5 km, ~25 Mbps; at 2+ km, performance degrades significantly. ADSL is more distance-tolerant (works up to ~5.5 km) but slower. ISPs with hybrid fiber-copper (FTTC) deployments use VDSL2 for the last few hundred meters.",
    triggerPhrase: "VDSL2 speed = highly distance-sensitive; best at under 300m from DSLAM; degrades fast with distance",
    weaknessTags: ["dsl-types"],
  },
  {
    id: "ic-61-15", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "A technician needs to configure a DSL router. The ISP provides a username and password. Which WAN connection type should be set in the router?",
    choices: [
      { id: "a", text: "Static IP", correct: false },
      { id: "b", text: "DHCP", correct: false },
      { id: "c", text: "PPPoE", correct: true },
      { id: "d", text: "Bridge mode", correct: false },
    ],
    explanation: "When an ISP provides a username and password for internet access, the WAN connection type in the router must be set to PPPoE (Point-to-Point Protocol over Ethernet). The router uses these credentials to authenticate with the ISP's BRAS (Broadband Remote Access Server). Static IP is used when the ISP assigns a fixed public IP without authentication. DHCP is used for cable internet where the modem automatically receives an IP. Bridge mode passes the PPPoE session through to a router.",
    triggerPhrase: "ISP gives username/password = set router WAN to PPPoE; DHCP = cable internet; Static = fixed IP",
    weaknessTags: ["dsl-types", "internet-conn-types"],
  },

  // -- 6.4 Network Configuration Concepts --------------------------------------
  {
    id: "nc-64-01", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What are the four steps of the DHCP DORA process in the correct order?",
    choices: [
      { id: "a", text: "Discover, Offer, Request, Acknowledge", correct: true },
      { id: "b", text: "Discover, Request, Offer, Acknowledge", correct: false },
      { id: "c", text: "Offer, Discover, Acknowledge, Request", correct: false },
      { id: "d", text: "Request, Discover, Offer, Acknowledge", correct: false },
    ],
    explanation: "DHCP DORA: (1) DISCOVER: Client broadcasts to find DHCP servers (src: 0.0.0.0, dst: 255.255.255.255). (2) OFFER: Server unicasts an IP address offer to the client's MAC. (3) REQUEST: Client broadcasts which offer it accepts (client may receive multiple offers). (4) ACKNOWLEDGE: Server confirms the lease. Client then uses the IP. Renewal happens at 50% of lease time (unicast to original server) and 87.5% (broadcast if server unreachable).",
    triggerPhrase: "DHCP DORA: Discover (broadcast) > Offer (unicast) > Request (broadcast) > Acknowledge (unicast)",
    weaknessTags: ["dhcp-process"],
  },
  {
    id: "nc-64-02", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A DHCP reservation ensures that a specific device always receives the same IP address. What information is used to create a DHCP reservation?",
    choices: [
      { id: "a", text: "The device's hostname", correct: false },
      { id: "b", text: "The device's MAC address", correct: true },
      { id: "c", text: "The device's operating system version", correct: false },
      { id: "d", text: "The device's current IP address", correct: false },
    ],
    explanation: "DHCP reservations (also called static DHCP or DHCP binding) link a specific MAC address to a specific IP address within the DHCP scope. When the device with that MAC sends a DISCOVER, the DHCP server always offers that specific reserved IP. This gives the appearance of a static IP (always same address) with the convenience of DHCP management. Used for printers, servers, IP cameras — devices that need predictable IPs but managed centrally.",
    triggerPhrase: "DHCP reservation = MAC address bound to specific IP; device always gets same IP via DHCP",
    weaknessTags: ["dhcp-process"],
  },
  {
    id: "nc-64-03", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "What does a DNS A record do?",
    choices: [
      { id: "a", text: "Maps a hostname to an IPv6 address", correct: false },
      { id: "b", text: "Maps a hostname to an IPv4 address", correct: true },
      { id: "c", text: "Defines the mail server for a domain", correct: false },
      { id: "d", text: "Creates an alias from one hostname to another", correct: false },
    ],
    explanation: "DNS A record: maps a Fully Qualified Domain Name (FQDN) to an IPv4 address. Example: www.example.com IN A 93.184.216.34. AAAA record: maps to IPv6 (4x the size of A record = AAAA). CNAME (Canonical Name): alias from one name to another. MX (Mail Exchanger): specifies mail servers. PTR: reverse lookup (IP to hostname). TXT: arbitrary text, used for SPF/DKIM/DMARC. The A record is the most fundamental DNS record type.",
    triggerPhrase: "DNS A record = hostname to IPv4; AAAA = hostname to IPv6 (4x larger); CNAME = alias",
    weaknessTags: ["dns-records"],
  },
  {
    id: "nc-64-04", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A company's mail server is mail.example.com. Which DNS record type directs email for @example.com addresses to that server?",
    choices: [
      { id: "a", text: "A record", correct: false },
      { id: "b", text: "CNAME record", correct: false },
      { id: "c", text: "MX record", correct: true },
      { id: "d", text: "PTR record", correct: false },
    ],
    explanation: "MX (Mail Exchanger) records specify the mail server(s) responsible for accepting email for a domain. Example: example.com IN MX 10 mail.example.com. The number (10) is the priority — lower number = higher priority. Multiple MX records provide redundancy (primary + backup mail servers). Sending mail servers perform an MX lookup for the recipient's domain, then connect to the listed mail server. An MX record must point to an A record (not a CNAME) per RFC.",
    triggerPhrase: "MX record = specifies mail server for domain; lower priority number = higher priority (10 wins over 20)",
    weaknessTags: ["dns-records"],
  },
  {
    id: "nc-64-05", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is a DNS CNAME record and what is an important limitation when using it?",
    choices: [
      { id: "a", text: "CNAME maps a hostname to an IP; limitation is it only works with IPv4", correct: false },
      { id: "b", text: "CNAME creates an alias from one name to another hostname; limitation is it cannot be used at the zone apex (root domain)", correct: true },
      { id: "c", text: "CNAME is used for reverse DNS; limitation is it requires a PTR record", correct: false },
      { id: "d", text: "CNAME defines email routing; limitation is only one allowed per domain", correct: false },
    ],
    explanation: "CNAME (Canonical Name): creates an alias. Example: www.example.com IN CNAME example.com. When a client resolves www.example.com, DNS returns 'look up example.com instead.' Key limitation: CNAME cannot be used at the zone apex (e.g., example.com itself) because the zone apex also needs SOA and NS records, which can't coexist with CNAME. Many CDNs and services require CNAME for their domains. ALIAS/ANAME records are a workaround for apex CNAMEs.",
    triggerPhrase: "CNAME = alias (name to name, not name to IP); cannot be used at zone apex (root domain)",
    weaknessTags: ["dns-records"],
  },
  {
    id: "nc-64-06", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is a DNS TXT record used for, and name two common email security uses?",
    choices: [
      { id: "a", text: "TXT stores the physical address of the domain owner; used for billing and legal purposes", correct: false },
      { id: "b", text: "TXT stores arbitrary text; commonly used for SPF (authorized mail senders) and DKIM (email cryptographic signatures)", correct: true },
      { id: "c", text: "TXT is used only for domain ownership verification with web hosting", correct: false },
      { id: "d", text: "TXT stores website content for fast DNS-based delivery", correct: false },
    ],
    explanation: "DNS TXT records store arbitrary human-readable or machine-readable text. Key email security uses: SPF (Sender Policy Framework): lists IP addresses authorized to send email for the domain, preventing spoofing. DKIM (DomainKeys Identified Mail): stores the public key used to verify cryptographic email signatures. DMARC: policy for what to do with emails failing SPF/DKIM (quarantine, reject). Domain ownership verification: Google, Microsoft, and others have you add a TXT record to prove domain control.",
    triggerPhrase: "DNS TXT = arbitrary text; email security: SPF (authorized senders), DKIM (public key), DMARC (policy)",
    weaknessTags: ["dns-records"],
  },
  {
    id: "nc-64-07", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is a DNS PTR record and what type of query uses it?",
    choices: [
      { id: "a", text: "PTR maps a hostname to multiple IP addresses for load balancing", correct: false },
      { id: "b", text: "PTR maps an IP address back to a hostname and is used in reverse DNS lookups", correct: true },
      { id: "c", text: "PTR records define the primary nameserver for a domain", correct: false },
      { id: "d", text: "PTR records store the public key for DNSSEC validation", correct: false },
    ],
    explanation: "PTR (Pointer) records provide reverse DNS lookup — mapping an IP address to a hostname, the opposite of an A record. They are stored in the in-addr.arpa zone. Example: 34.216.184.93.in-addr.arpa IN PTR www.example.com. Uses: email spam filtering (mail servers check PTR to verify sending server hostname matches), security logs (human-readable IPs), and network troubleshooting. PTR records are managed by the IP address owner (usually the ISP), not the domain owner.",
    triggerPhrase: "PTR record = reverse DNS (IP to hostname); stored in in-addr.arpa; used for email verification and logs",
    weaknessTags: ["dns-records", "dns-hierarchy"],
  },
  {
    id: "nc-64-08", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is 802.1Q VLAN tagging and where is it used?",
    choices: [
      { id: "a", text: "802.1Q encrypts VLAN traffic between switches; used on access ports", correct: false },
      { id: "b", text: "802.1Q inserts a 4-byte tag into Ethernet frames to identify the VLAN; used on trunk ports between switches and to routers", correct: true },
      { id: "c", text: "802.1Q is a wireless standard for VLAN segmentation in Wi-Fi 6 networks", correct: false },
      { id: "d", text: "802.1Q adds a 12-byte header that contains both the VLAN ID and the destination IP", correct: false },
    ],
    explanation: "IEEE 802.1Q inserts a 4-byte tag into the Ethernet frame header: 2 bytes TPID (0x8100) + 2 bytes TCI (which contains 3-bit PCP for QoS priority and 12-bit VLAN ID, supporting VLANs 1-4094). Tagged frames are sent on trunk ports, which carry multiple VLANs simultaneously. Access ports carry only one VLAN (untagged). Native VLAN frames are typically sent untagged on trunk ports. The tag is added by the switch and removed before delivery to end devices.",
    triggerPhrase: "802.1Q = 4-byte VLAN tag in frame (VLAN ID 1-4094); trunk ports carry tagged frames for multiple VLANs",
    weaknessTags: ["vlan-config"],
  },
  {
    id: "nc-64-09", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the difference between a switch access port and a trunk port in VLAN configuration?",
    choices: [
      { id: "a", text: "Access ports are faster; trunk ports are used for long distances", correct: false },
      { id: "b", text: "Access ports carry a single VLAN (untagged) for end devices; trunk ports carry multiple VLANs (tagged with 802.1Q) between switches and routers", correct: true },
      { id: "c", text: "Trunk ports are used for uplinks to the internet; access ports for local devices", correct: false },
      { id: "d", text: "Access ports use fiber; trunk ports use copper", correct: false },
    ],
    explanation: "Access port: configured for a single VLAN; sends and receives untagged frames; connects end devices (PCs, printers, phones). The device doesn't know it's on a VLAN. Trunk port: carries multiple VLANs simultaneously using 802.1Q tags; connects switches to switches, switches to routers, or switches to APs with multiple SSIDs. The switch adds 802.1Q tags when sending and strips them when receiving on access ports. Inter-VLAN routing requires a router or Layer 3 switch connected via trunk port (router-on-a-stick).",
    triggerPhrase: "Access port = one VLAN, untagged, for end devices; Trunk port = multiple VLANs, 802.1Q tagged, between devices",
    weaknessTags: ["vlan-config"],
  },
  {
    id: "nc-64-10", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the difference between a site-to-site VPN and a remote access VPN?",
    choices: [
      { id: "a", text: "Site-to-site VPNs use IPsec; remote access VPNs use only PPTP", correct: false },
      { id: "b", text: "Site-to-site VPN connects two networks permanently (e.g., branch to HQ); remote access VPN allows individual users to connect from anywhere to the corporate network", correct: true },
      { id: "c", text: "Remote access VPNs are faster; site-to-site VPNs are more secure", correct: false },
      { id: "d", text: "Site-to-site VPNs require a client on every device; remote access VPNs are clientless", correct: false },
    ],
    explanation: "Site-to-site VPN: connects two entire networks (e.g., branch office to headquarters) through VPN gateways/firewalls at each end. Users on either network can communicate transparently without individual VPN clients. Always-on tunnel. Remote access VPN: individual users connect to the corporate network from anywhere (home, hotel). Requires VPN client software (like Cisco AnyConnect, GlobalProtect) or a clientless browser-based SSL VPN. Session is per-user, initiated on-demand.",
    triggerPhrase: "Site-to-site VPN = network-to-network, always-on tunnel between gateways; Remote access = user dials in with client",
    weaknessTags: ["vpn-types"],
  },
  {
    id: "nc-64-11", domain: "2.0-networking", difficulty: "hard", type: "single", source: "drill",
    prompt: "IPsec can operate in Transport Mode or Tunnel Mode. What is the key difference?",
    choices: [
      { id: "a", text: "Transport Mode encrypts the entire IP packet including headers; Tunnel Mode only encrypts the payload", correct: false },
      { id: "b", text: "Transport Mode encrypts only the payload (leaving original IP headers); Tunnel Mode encapsulates the entire original packet inside a new IP packet", correct: true },
      { id: "c", text: "Transport Mode uses AES; Tunnel Mode uses 3DES only", correct: false },
      { id: "d", text: "Transport Mode is for remote access; Tunnel Mode is for site-to-site only", correct: false },
    ],
    explanation: "IPsec modes: Transport Mode: encrypts only the Layer 4+ payload (TCP/UDP segment); original IP header is unchanged. Used between two hosts communicating directly (host-to-host). Tunnel Mode: encrypts the entire original IP packet (including its headers) and adds a new outer IP header. This hides the original source/destination. Used for site-to-site VPNs between gateways. IPsec uses AH (Authentication Header, provides integrity but no encryption) and/or ESP (Encapsulating Security Payload, provides both encryption and integrity).",
    triggerPhrase: "IPsec Transport Mode = encrypt payload only (host-to-host); Tunnel Mode = encrypt whole packet + new header (gateway VPN)",
    weaknessTags: ["vpn-types"],
  },
  {
    id: "nc-64-12", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Why is SSL/TLS VPN often easier to deploy for remote access than IPsec VPN?",
    choices: [
      { id: "a", text: "SSL VPN is faster and more secure than IPsec in all scenarios", correct: false },
      { id: "b", text: "SSL VPN uses port 443 (HTTPS), which is rarely blocked by firewalls, and can work through web browsers without dedicated client software", correct: true },
      { id: "c", text: "SSL VPN does not require authentication, making it simpler to configure", correct: false },
      { id: "d", text: "SSL VPN works only over Wi-Fi, while IPsec requires wired connections", correct: false },
    ],
    explanation: "SSL/TLS VPN advantages for remote access: (1) Uses HTTPS (port 443) — almost never blocked by firewalls, NAT-friendly. (2) Clientless mode: works via web browser without installed software — useful for unmanaged devices. (3) Client mode (like Cisco AnyConnect): thin client, easier than full IPsec client configuration. (4) User-friendly authentication (username/password, MFA, SSO integration). IPsec is still preferred for site-to-site due to performance and broader protocol support.",
    triggerPhrase: "SSL/TLS VPN = port 443 (rarely blocked), works via browser, easier for remote users; IPsec = better for site-to-site",
    weaknessTags: ["vpn-types"],
  },
  {
    id: "nc-64-13", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A company has multiple office buildings, each on a different subnet. DHCP is only on the main server in building 1. How do clients in building 2 receive DHCP leases?",
    choices: [
      { id: "a", text: "They cannot; each building must have its own DHCP server", correct: false },
      { id: "b", text: "A DHCP relay agent on the building 2 router forwards DHCP broadcast requests to the DHCP server's unicast address", correct: true },
      { id: "c", text: "Clients in building 2 automatically get static IPs instead of DHCP", correct: false },
      { id: "d", text: "The switch in building 2 proxies DHCP requests over the trunk link", correct: false },
    ],
    explanation: "DHCP broadcasts don't cross router boundaries by default. A DHCP relay agent (ip helper-address command on Cisco routers) intercepts DHCP broadcasts from clients, converts them to unicast packets, and forwards them to the DHCP server's IP across the routed network. The server responds with an offer, which the relay forwards back to the client. This allows a single DHCP server to serve multiple subnets. Windows Server also has the DHCP relay agent role.",
    triggerPhrase: "DHCP relay agent (ip helper-address) = forwards DHCP broadcasts across routers to central DHCP server",
    weaknessTags: ["dhcp-process"],
  },
  {
    id: "nc-64-14", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the DNS hierarchy from most specific to most general?",
    choices: [
      { id: "a", text: "Root zone > TLD > Second-level domain > Subdomain", correct: false },
      { id: "b", text: "Subdomain > Second-level domain > TLD > Root zone (.)", correct: true },
      { id: "c", text: "IP address > MAC address > Domain > Root", correct: false },
      { id: "d", text: "DHCP server > DNS server > Root > TLD", correct: false },
    ],
    explanation: "DNS hierarchy (most specific to most general): subdomain.second-level.TLD. (trailing dot = root). Example: www.example.com. = www (subdomain) > example (second-level domain) > com (TLD) > . (root). Resolution process: recursive resolver asks root servers for .com TLD servers; TLD servers direct to example.com authoritative servers; authoritative server returns the A record for www. Caching at each level reduces lookups. The 13 root server clusters handle queries for unknown TLDs.",
    triggerPhrase: "DNS hierarchy: subdomain > SLD > TLD > Root (trailing dot); resolution flows from root down to authoritative",
    weaknessTags: ["dns-hierarchy"],
  },
  {
    id: "nc-64-15", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "A Voice over IP phone needs to be on a dedicated VLAN separate from data traffic. What is the PRIMARY reason for this configuration?",
    choices: [
      { id: "a", text: "To prevent VoIP phones from accessing file servers", correct: false },
      { id: "b", text: "To apply QoS priority to voice traffic, ensuring low latency and jitter for call quality", correct: true },
      { id: "c", text: "To give VoIP phones a different subnet for billing purposes", correct: false },
      { id: "d", text: "To prevent VoIP phones from receiving DHCP addresses", correct: false },
    ],
    explanation: "Voice VLANs (also called auxiliary VLANs) serve two main purposes: (1) QoS prioritization — voice traffic is tagged with DSCP EF (Expedited Forwarding) or 802.1p priority 5/6, ensuring it is queued and transmitted before data traffic (preventing choppy/dropped calls). (2) Security segmentation — separates phone traffic from PC data traffic, limiting what phones can access. Cisco switches can automatically place IP phones on a voice VLAN while the PC on the same port stays in the data VLAN.",
    triggerPhrase: "Voice VLAN = QoS priority for low-latency VoIP + security segmentation from data traffic",
    weaknessTags: ["vlan-config", "voip-tshooting"],
  },
];
'@
$result = $trimmed + $newQuestions
[System.IO.File]::WriteAllText($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Batch C done. Total lines: $((Get-Content $file).Count)"
