// append-ext8.js — 18 port/protocol questions referencing 12_ports_protocols.svg
const fs = require('fs');

const newQuestions = `
  // ── PORT / PROTOCOL NUMBERS (ext8-q01 to ext8-q18) ── image: /diagrams/12_ports_protocols.svg ──
  {
    id: "ext8-q01",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port number does SSH use for encrypted remote access?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "21", correct: false },
      { id: "b", text: "22", correct: true },
      { id: "c", text: "23", correct: false },
      { id: "d", text: "25", correct: false },
    ],
    explanation: "SSH (Secure Shell) uses port 22. It replaced Telnet (port 23) as the standard for encrypted remote login. Remember: 22 = Secure Shell, 23 = Telnet (one higher, less secure).",
    triggerPhrase: "SSH port encrypted remote",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q02",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does RDP (Remote Desktop Protocol) use by default?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "22", correct: false },
      { id: "b", text: "443", correct: false },
      { id: "c", text: "3389", correct: true },
      { id: "d", text: "3306", correct: false },
    ],
    explanation: "RDP uses port 3389. It is used by Windows Remote Desktop to stream a graphical desktop session over the network. The large port number (3389) is a key differentiator from other remote access protocols.",
    triggerPhrase: "RDP remote desktop protocol port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q03",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does HTTPS use for encrypted web traffic?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "80", correct: false },
      { id: "b", text: "8080", correct: false },
      { id: "c", text: "8443", correct: false },
      { id: "d", text: "443", correct: true },
    ],
    explanation: "HTTPS uses port 443. HTTP (unencrypted) uses port 80. HTTPS wraps HTTP in TLS/SSL encryption, and the port 443 is the standard for secure web browsing.",
    triggerPhrase: "HTTPS encrypted web port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q04",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does standard HTTP (unencrypted web traffic) use?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "443", correct: false },
      { id: "b", text: "8080", correct: false },
      { id: "c", text: "21", correct: false },
      { id: "d", text: "80", correct: true },
    ],
    explanation: "HTTP uses port 80. HTTPS uses port 443. A simple way to remember: 80 = HTTP (no lock), 443 = HTTPS (locked/secure).",
    triggerPhrase: "HTTP unencrypted web port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q05",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does SMTP use to send outgoing email?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "110", correct: false },
      { id: "b", text: "143", correct: false },
      { id: "c", text: "993", correct: false },
      { id: "d", text: "25", correct: true },
    ],
    explanation: "SMTP (Simple Mail Transfer Protocol) uses port 25 to send email between mail servers. POP3 (port 110) and IMAP (port 143) are for receiving email, not sending it.",
    triggerPhrase: "SMTP send email port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q06",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A technician configures a mail client to download email and delete it from the server. Which port is this protocol using?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "25", correct: false },
      { id: "b", text: "110", correct: true },
      { id: "c", text: "143", correct: false },
      { id: "d", text: "993", correct: false },
    ],
    explanation: "POP3 (Post Office Protocol v3) uses port 110 and downloads email from the server, typically deleting it from the server afterward. IMAP (port 143) keeps email on the server and syncs it across devices.",
    triggerPhrase: "POP3 download delete email port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q07",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does IMAP use to sync email across multiple devices?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "110", correct: false },
      { id: "b", text: "25", correct: false },
      { id: "c", text: "993", correct: false },
      { id: "d", text: "143", correct: true },
    ],
    explanation: "IMAP (Internet Message Access Protocol) uses port 143 and keeps email on the server, allowing synchronization across multiple devices (phone, laptop, desktop). Unlike POP3 (110), email is not deleted after download.",
    triggerPhrase: "IMAP sync email multiple devices port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q08",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does DNS use to resolve domain names to IP addresses?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "67", correct: false },
      { id: "b", text: "123", correct: false },
      { id: "c", text: "161", correct: false },
      { id: "d", text: "53", correct: true },
    ],
    explanation: "DNS (Domain Name System) uses port 53, typically over UDP for queries and TCP for zone transfers. Memory trick: DNS = 53, just remember '53' as the lookup service.",
    triggerPhrase: "DNS domain name resolution port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q09",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does a DHCP server listen on to assign IP addresses to clients?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "68", correct: false },
      { id: "b", text: "69", correct: false },
      { id: "c", text: "53", correct: false },
      { id: "d", text: "67", correct: true },
    ],
    explanation: "DHCP servers listen on port 67. DHCP clients send requests from port 68. The DORA process (Discover, Offer, Request, Acknowledge) uses both: client broadcasts on 68, server responds from 67. Memory: 67 = server, 68 = client.",
    triggerPhrase: "DHCP server port assign IP",
    weaknessTags: ["port-numbers", "dhcp-process"],
  },
  {
    id: "ext8-q10",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does FTP use for the control connection (commands)?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "20", correct: false },
      { id: "b", text: "22", correct: false },
      { id: "c", text: "23", correct: false },
      { id: "d", text: "21", correct: true },
    ],
    explanation: "FTP uses two ports: port 21 for the control connection (commands like LIST, RETR, STOR) and port 20 for the actual data transfer. Remember: 21 = control, 20 = data (lower number = data flowing).",
    triggerPhrase: "FTP control connection commands port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q11",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A file is actively being transferred over FTP. Which port carries the data stream?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "21", correct: false },
      { id: "b", text: "22", correct: false },
      { id: "c", text: "25", correct: false },
      { id: "d", text: "20", correct: true },
    ],
    explanation: "FTP uses port 20 for data transfer and port 21 for control/commands. When a file is actively being transferred, it flows over port 20. Port 21 stays open for commands throughout the session.",
    triggerPhrase: "FTP data transfer port number",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q12",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does Telnet use? Why is it considered a security risk?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "22 — because it encrypts credentials", correct: false },
      { id: "b", text: "23 — because it sends data in plaintext", correct: true },
      { id: "c", text: "21 — because it allows anonymous access", correct: false },
      { id: "d", text: "25 — because it relays email externally", correct: false },
    ],
    explanation: "Telnet uses port 23 and sends all data including usernames and passwords in plaintext, making it easy for attackers to capture credentials. SSH (port 22) is its secure replacement.",
    triggerPhrase: "Telnet port security plaintext",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q13",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does NTP use to synchronize system clocks across a network?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "110", correct: false },
      { id: "b", text: "67", correct: false },
      { id: "c", text: "161", correct: false },
      { id: "d", text: "123", correct: true },
    ],
    explanation: "NTP (Network Time Protocol) uses port 123 over UDP. Accurate time synchronization is critical for authentication protocols (like Kerberos) and log analysis.",
    triggerPhrase: "NTP network time protocol port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q14",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A network monitoring system polls routers and switches for performance data. Which port does it use for queries?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "162", correct: false },
      { id: "b", text: "163", correct: false },
      { id: "c", text: "53", correct: false },
      { id: "d", text: "161", correct: true },
    ],
    explanation: "SNMP (Simple Network Management Protocol) uses port 161 for polling queries (manager asks devices for data). Port 162 is used for SNMP traps (devices send unsolicited alerts to the manager).",
    triggerPhrase: "SNMP polling queries port network monitoring",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q15",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "SNMP trap messages are sent from a device to the management station. Which port receives these traps?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "161", correct: false },
      { id: "b", text: "163", correct: false },
      { id: "c", text: "53", correct: false },
      { id: "d", text: "162", correct: true },
    ],
    explanation: "SNMP traps (unsolicited alerts from managed devices to the management station) use port 162. Queries go to port 161. Memory trick: 161 = poll (ask), 162 = trap (tell).",
    triggerPhrase: "SNMP trap port device alert",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q16",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does LDAP use to query directory services such as Active Directory?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "443", correct: false },
      { id: "b", text: "636", correct: false },
      { id: "c", text: "88", correct: false },
      { id: "d", text: "389", correct: true },
    ],
    explanation: "LDAP (Lightweight Directory Access Protocol) uses port 389. LDAPS (LDAP over SSL/TLS) uses port 636. LDAP is commonly used to authenticate users against Active Directory in enterprise environments.",
    triggerPhrase: "LDAP directory active directory port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q17",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which port does SMB use for Windows file and printer sharing?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "139", correct: false },
      { id: "b", text: "137", correct: false },
      { id: "c", text: "548", correct: false },
      { id: "d", text: "445", correct: true },
    ],
    explanation: "SMB (Server Message Block) uses port 445 for direct TCP/IP file sharing. Legacy NetBIOS-based SMB used ports 137-139. Modern Windows file sharing uses port 445 exclusively.",
    triggerPhrase: "SMB Windows file sharing port",
    weaknessTags: ["port-numbers"],
  },
  {
    id: "ext8-q18",
    domain: "2.0-networking",
    difficulty: "hard",
    type: "single",
    source: "concept-builder",
    prompt: "A macOS client connects to a file server using the Apple Filing Protocol. Which port does AFP use?",
    image: "/diagrams/12_ports_protocols.svg",
    imageAlt: "CompTIA A+ port numbers quick reference table",
    choices: [
      { id: "a", text: "445", correct: false },
      { id: "b", text: "139", correct: false },
      { id: "c", text: "548", correct: true },
      { id: "d", text: "389", correct: false },
    ],
    explanation: "AFP (Apple Filing Protocol) uses port 548. It was the native file sharing protocol for macOS before SMB became the default. AFP is now largely deprecated in favor of SMB, but 548 is still on the CompTIA A+ exam.",
    triggerPhrase: "AFP Apple Filing Protocol macOS port",
    weaknessTags: ["port-numbers"],
  },`;

const filePath = 'data/questions/index.ts';
const content = fs.readFileSync(filePath, 'utf8');
const insertAt = content.lastIndexOf('];');
if (insertAt === -1) { console.error('Could not find "];". Aborting.'); process.exit(1); }
const updated = content.substring(0, insertAt) + newQuestions + '\n];';
fs.writeFileSync(filePath, updated, 'utf8');
const lineCount = updated.split('\n').length;
console.log('Done! File now has', lineCount, 'lines. Appended 18 questions (ext8-q01 through ext8-q18).');
