$file = "C:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$insertAt = $content.LastIndexOf('];')

$newQuestions = @'

  // === External Practice Questions Set 3 ===
  {
    id: "ext3-q01",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A user notices that their laser printer is not working and is causing an error. When the technician looks at the printer, they notice that the user was using thick paper, causing a part of the printer to overheat. Which part of the printer has overheated?",
    choices: [
      { id: "a", text: "Developer roller", correct: false },
      { id: "b", text: "Pickup roller", correct: false },
      { id: "c", text: "Transfer roller", correct: false },
      { id: "d", text: "Fuser unit", correct: true },
    ],
    explanation: "The fuser unit uses heat and pressure to bond toner to paper. Thick paper requires more time and heat to pass through the fuser assembly, which causes the fuser to overheat. The pickup roller feeds paper from the input tray. The transfer roller moves toner from the drum to the paper. The developer roller applies toner to the photosensitive drum.",
    triggerPhrase: "Thick paper + overheat = Fuser unit",
    weaknessTags: ["printer-components", "imaging-process"],
  },
  {
    id: "ext3-q02",
    domain: "4.0-virtualization-cloud",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A holiday decor store typically runs its cloud infrastructure privately, but its servers get bogged down by transactions during the peak holiday season. To mitigate any revenue losses, the store must outsource processing power to an outside cloud service provider to help support the increased sales volume. What cloud deployment model does the holiday decor store utilize?",
    choices: [
      { id: "a", text: "Public cloud", correct: false },
      { id: "b", text: "Private cloud", correct: false },
      { id: "c", text: "Community cloud", correct: false },
      { id: "d", text: "Hybrid cloud", correct: true },
    ],
    explanation: "A hybrid cloud combines private and public cloud resources. The store maintains its own private cloud for normal operations but bursts out to a public cloud provider during peak holiday demand. A purely public cloud is hosted entirely by a provider with no private infrastructure. A private cloud is wholly owned/operated by one organization. A community cloud is shared among organizations with common interests.",
    triggerPhrase: "Private infra + outside provider when busy = Hybrid cloud",
    weaknessTags: ["multitenancy"],
  },
  {
    id: "ext3-q03",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "multi",
    source: "concept-builder",
    prompt: "What are the main components of authentication, authorization, and accounting (AAA) that securely and adequately connect devices to a network? (Select three.)",
    choices: [
      { id: "a", text: "DHCP server", correct: false },
      { id: "b", text: "Supplicant", correct: true },
      { id: "c", text: "AAA server", correct: true },
      { id: "d", text: "Network access server/point", correct: true },
    ],
    explanation: "The three AAA components are: (1) Supplicant - the device requesting network access (e.g., a PC or laptop); (2) Network Access Server/Point (NAS/NAP) - the network appliance (switch, AP, VPN gateway) that acts as an AAA client/authenticator; (3) AAA Server - the central authentication server (e.g., RADIUS) that validates credentials. DHCP assigns IP addresses and is not part of the AAA authentication process.",
    triggerPhrase: "AAA = Supplicant + Network Access Server + AAA Server (not DHCP)",
    weaknessTags: ["vlan-config", "vpn-types"],
  },
  {
    id: "ext3-q04",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "multi",
    source: "concept-builder",
    prompt: "An IPv6 address is composed of which two main parts? (Select two.)",
    choices: [
      { id: "a", text: "Dynamic address", correct: false },
      { id: "b", text: "Network ID", correct: true },
      { id: "c", text: "Static address", correct: false },
      { id: "d", text: "Interface ID", correct: true },
    ],
    explanation: "An IPv6 address (128 bits total) consists of two equal 64-bit halves: the Network ID (first 64 bits, identifying the network prefix) and the Interface ID (last 64 bits, identifying the specific host on that network). Dynamic and static refer to how addresses are assigned (via DHCP vs manual), not to structural parts of the IPv6 address itself.",
    triggerPhrase: "IPv6 = Network ID (first 64 bits) + Interface ID (last 64 bits)",
    weaknessTags: ["dhcp-process", "dns-records"],
  },
  {
    id: "ext3-q05",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which of the following causes the ink in an inkjet printer to break up into small pumps, which give an electrical charge when they leave the print head and can either stick to the paper or fall off?",
    choices: [
      { id: "a", text: "Thermal method", correct: false },
      { id: "b", text: "Epson design", correct: true },
      { id: "c", text: "Transfer roller", correct: false },
      { id: "d", text: "Imaging drum", correct: false },
    ],
    explanation: "Epson's piezoelectric inkjet design uses a piezoelectric element that changes shape when voltage is applied, pumping ink droplets through the nozzle. Droplets are electrically charged as they leave the print head and are directed to the paper or recycled. The thermal method (HP design) heats ink to create a steam bubble that ejects a droplet. The transfer roller and imaging drum are laser printer components, not inkjet.",
    triggerPhrase: "Piezoelectric / charged ink droplets = Epson design",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "ext3-q06",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A technician is using a printer that uses Adobe's device-independent language for text-to-raster conversion. Which of the following is this?",
    choices: [
      { id: "a", text: "Infrastructure mode", correct: false },
      { id: "b", text: "PDL", correct: false },
      { id: "c", text: "PCL", correct: false },
      { id: "d", text: "PostScript", correct: true },
    ],
    explanation: "PostScript is Adobe's device-independent page description language (PDL) used for text-to-raster conversion, widely used in professional desktop publishing. PDL is the broad category name, not the specific Adobe product. PCL (Printer Control Language) is HP's device-dependent printer language. Infrastructure mode is a Wi-Fi network topology, not a printer language.",
    triggerPhrase: "Adobe + device-independent PDL = PostScript (PCL = HP, device-dependent)",
    weaknessTags: ["printer-connectivity", "inkjet-thermal-impact"],
  },
  {
    id: "ext3-q07",
    domain: "1.0-mobile",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A display manufacturing company is evolving its current model line to offer a new model of display that does not require a backlight as each individual pixel is self-illuminating. What technology does not require a backlight because each individual pixel is self-illuminating?",
    choices: [
      { id: "a", text: "Light-emitting diodes", correct: false },
      { id: "b", text: "Thin film transistor", correct: false },
      { id: "c", text: "Liquid crystal display", correct: false },
      { id: "d", text: "Organic LED", correct: true },
    ],
    explanation: "OLED (Organic LED) displays are self-illuminating - each pixel contains an organic compound that emits its own light, so no backlight is needed. LCD and TFT displays require a separate backlight (typically LEDs) to illuminate their liquid crystals. LEDs themselves are used as the backlight source inside LED-backlit LCD monitors, not as the self-illuminating pixels.",
    triggerPhrase: "No backlight + self-illuminating pixels = OLED (not LED, not LCD)",
    weaknessTags: ["display-tech", "laptop-display"],
  },
  {
    id: "ext3-q08",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A technician replaced a failed drive in a RAID array and noticed a severely degraded performance. What is the problem?",
    choices: [
      { id: "a", text: "Rebuilding the array consumes many resources", correct: true },
      { id: "b", text: "There is a cable problem", correct: false },
      { id: "c", text: "There is a faulty disk", correct: false },
      { id: "d", text: "The controller is failing", correct: false },
    ],
    explanation: "After replacing a failed drive, the RAID controller must rebuild the array by writing several gigabytes of parity/mirror data to the new disk. This rebuild process heavily consumes disk I/O and CPU resources, causing temporary but severe performance degradation. A cable problem would prevent the new drive from being detected at all. If the controller were failing, the array would not have been accessible to begin the replacement.",
    triggerPhrase: "RAID slow right after drive replacement = normal rebuild process consuming resources",
    weaknessTags: ["raid-rebuild", "raid-2-drives"],
  },
  {
    id: "ext3-q09",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A technician has tested a computer with extended read/write times and found it to have IOPS reduced from vendor baselines. What should the technician do next?",
    choices: [
      { id: "a", text: "Make data backups", correct: true },
      { id: "b", text: "Replace the drive", correct: false },
      { id: "c", text: "Change the power cord", correct: false },
      { id: "d", text: "Change the PSU", correct: false },
    ],
    explanation: "Extended read/write times and reduced IOPS indicate the drive is failing. However, since the drive has not completely failed yet, the first priority is to back up all data before it becomes unrecoverable. Replacing the drive immediately without backing up first would result in total data loss. Power components are not implicated when SMART/performance metrics point directly to the drive.",
    triggerPhrase: "Failing drive signs = back up data FIRST, then replace",
    weaknessTags: ["drive-health", "bsod-codes"],
  },
  {
    id: "ext3-q10",
    domain: "3.0-hardware",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which mechanism has performance ratings of 5,400 rpm, 7,200 rpm, 10,000 rpm, and 15,000 rpm?",
    choices: [
      { id: "a", text: "SSD", correct: false },
      { id: "b", text: "mSATA", correct: false },
      { id: "c", text: "HDD", correct: true },
      { id: "d", text: "RAID", correct: false },
    ],
    explanation: "RPM (rotations per minute) measures how fast the magnetic platters spin inside a hard disk drive (HDD). Common HDD speeds: 5,400 rpm (laptop/low-power), 7,200 rpm (standard desktop), 10,000 and 15,000 rpm (enterprise/high-performance). SSDs have no moving parts and no RPM rating. mSATA is a physical form factor for SSDs. RAID is a drive array configuration, not a mechanism type.",
    triggerPhrase: "RPM ratings = HDD only (SSDs have no moving parts)",
    weaknessTags: ["drive-health", "sata-interface"],
  },
  {
    id: "ext3-q11",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A vast majority of rural residents in the United States still use this internet connection type that utilizes the public switched telephone network (PSTN).",
    choices: [
      { id: "a", text: "Satellite", correct: false },
      { id: "b", text: "DSL", correct: true },
      { id: "c", text: "WISP", correct: false },
      { id: "d", text: "Wi-Fi", correct: false },
    ],
    explanation: "DSL (Digital Subscriber Line) transmits broadband internet data over existing copper telephone lines (the PSTN). It is common in rural areas that have telephone infrastructure but no cable or fiber. Satellite internet uses orbiting satellites, not telephone lines. A WISP (Wireless Internet Service Provider) uses fixed wireless radio towers. Wi-Fi is a local area wireless standard, not a WAN connection type.",
    triggerPhrase: "PSTN + internet access = DSL",
    weaknessTags: ["internet-conn-types", "dsl-types"],
  },
  {
    id: "ext3-q12",
    domain: "5.0-troubleshooting",
    difficulty: "hard",
    type: "single",
    source: "concept-builder",
    prompt: "After running a SMART (Self-Monitoring, Analysis, and Reporting Technology) diagnosis on a computer with extended read/write times, the IOPS matches the vendor's baseline. What could be the problem?",
    choices: [
      { id: "a", text: "No power", correct: false },
      { id: "b", text: "Limited hard drive capacity", correct: true },
      { id: "c", text: "Disk failure", correct: false },
      { id: "d", text: "Hard drive unavailable", correct: false },
    ],
    explanation: "When SMART reports IOPS at the vendor baseline (the drive hardware is functioning correctly) but read/write times are still slow, the drive is not failing - instead it is nearly full. A nearly-full drive forces the file system to scatter writes across fragmented free space, extending the time per operation even though the raw I/O rate is normal. Disk failure or no power would cause SMART errors and IOPS below baseline.",
    triggerPhrase: "SMART OK + IOPS OK + slow = full drive causing fragmentation",
    weaknessTags: ["drive-health"],
  },
  {
    id: "ext3-q13",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A developer asks that any network requests made to the hostname dev23.company.net get directed to a specific IP address of 10.130.25.15. What type of DNS record will the developer need to create?",
    choices: [
      { id: "a", text: "(TXT) record", correct: false },
      { id: "b", text: "(MX) record", correct: false },
      { id: "c", text: "(AAAA) record", correct: false },
      { id: "d", text: "(A) record", correct: true },
    ],
    explanation: "An A record maps a hostname to an IPv4 address. Since 10.130.25.15 uses four octets (dotted-decimal notation), it is an IPv4 address, requiring an A record. An AAAA record maps to an IPv6 address (128-bit hexadecimal). MX records specify mail server hostnames for a domain. TXT records store arbitrary text data (SPF, DKIM, domain verification).",
    triggerPhrase: "Hostname to IPv4 = A record; IPv6 = AAAA record",
    weaknessTags: ["dns-records"],
  },
'@

$newContent = $content.Substring(0, $insertAt) + $newQuestions + "`n];"
[System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Ext3 done. Total lines: $($newContent.Split("`n").Length)"
