$file = "c:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$trimmed = $content.TrimEnd().Substring(0, $content.TrimEnd().LastIndexOf('];'))
$newQuestions = @'

  // -- 4.2 Power and Disk Issues ------------------------------------------------
  {
    id: "pd-42-01", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A technician presses the power button on a desktop PC and nothing happens — no lights, no fans, no beeps. What should be checked FIRST?",
    choices: [
      { id: "a", text: "Replace the motherboard", correct: false },
      { id: "b", text: "Verify the outlet has power, check the power cord, and confirm the PSU rear switch is ON", correct: true },
      { id: "c", text: "Remove and reseat all RAM", correct: false },
      { id: "d", text: "Disconnect the hard drive and retry", correct: false },
    ],
    explanation: "Always start at the power source: confirm the outlet works (test with another device), the power cord is seated firmly at both ends, and the PSU rocker switch on the back is in the ON position (I = ON, O = OFF). Next check the front-panel power switch connector on the motherboard header. A completely dead system with no reaction is almost always external power, PSU switch, or a dead PSU — not a motherboard or RAM problem.",
    triggerPhrase: "No power at all: outlet > cord > PSU rear switch > PSU itself > front panel header",
    weaknessTags: ["psu-troubleshoot"],
  },
  {
    id: "pd-42-02", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A PC powers on for 2-3 seconds then immediately shuts off, repeatedly. No beeps are heard. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "Bad RAM causing an immediate crash loop", correct: false },
      { id: "b", text: "PSU failing under initial load or CPU protection triggering due to missing CPU power connector", correct: true },
      { id: "c", text: "Corrupt operating system", correct: false },
      { id: "d", text: "Failing hard drive detected during POST", correct: false },
    ],
    explanation: "Instant shutdown 2-3 seconds after powering on (before POST completes) typically indicates: PSU failing when components draw current, missing or loose CPU power connector (8-pin EPS), CPU/motherboard incompatibility, or CPU thermal protection triggering if no heatsink is seated. It's too early for OS or drive issues. Check PSU under load (PSU tester), verify the EPS CPU power connector is seated, and confirm the heatsink is mounted with thermal paste.",
    triggerPhrase: "Powers on then shuts off in 2-3 sec = PSU failure under load or missing CPU 8-pin power connector",
    weaknessTags: ["psu-troubleshoot"],
  },
  {
    id: "pd-42-03", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "During POST, a desktop emits one long beep followed by two short beeps (AMI BIOS). What does this indicate?",
    choices: [
      { id: "a", text: "RAM failure", correct: false },
      { id: "b", text: "Video card / GPU error", correct: true },
      { id: "c", text: "CPU overheating", correct: false },
      { id: "d", text: "Successful POST", correct: false },
    ],
    explanation: "AMI (American Megatrends Inc.) BIOS beep codes: 1 long + 2 short = video card error (GPU not detected or failed). 1 long + 3 short = video memory failure. 3 long = keyboard error. Continuous beeping = RAM failure or no RAM detected. 1 short (Award BIOS) = successful POST. BIOS beep codes vary by manufacturer — always consult the motherboard manual. Today many boards use diagnostic LED codes instead of beeps.",
    triggerPhrase: "AMI BIOS: 1 long + 2 short = GPU/video error; continuous/repeating beeps = RAM failure",
    weaknessTags: ["post-codes"],
  },
  {
    id: "pd-42-04", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A PC's clock and BIOS settings reset to defaults every time it is powered off. What component has failed?",
    choices: [
      { id: "a", text: "The power supply voltage regulator", correct: false },
      { id: "b", text: "The CMOS battery (CR2032)", correct: true },
      { id: "c", text: "The RAM (BIOS stores settings in RAM)", correct: false },
      { id: "d", text: "The hard drive storing the BIOS configuration file", correct: false },
    ],
    explanation: "The CMOS battery (typically a CR2032 lithium coin cell) provides power to the CMOS RAM chip that retains BIOS settings and the real-time clock (RTC) when the PC is off. When it dies (typically after 5-10 years), BIOS settings revert to defaults and the clock resets to a date in the past. Replacement is cheap and easy. Some symptoms: BIOS date shows 1/1/2000, boot device order resets, custom fan curves lost.",
    triggerPhrase: "BIOS settings reset + clock loses time = dead CMOS battery (CR2032 coin cell)",
    weaknessTags: ["post-codes", "boot-sequence"],
  },
  {
    id: "pd-42-05", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A Windows PC displays a blue screen with stop code 0x0000007B (INACCESSIBLE_BOOT_DEVICE) immediately on startup. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "Bad RAM module", correct: false },
      { id: "b", text: "The boot drive cannot be found or accessed — often caused by incorrect storage controller mode in BIOS or corrupt drive", correct: true },
      { id: "c", text: "GPU driver conflict", correct: false },
      { id: "d", text: "Virus preventing Windows from loading", correct: false },
    ],
    explanation: "BSOD 0x0000007B (INACCESSIBLE_BOOT_DEVICE) means Windows cannot find or access its boot volume. Common causes: BIOS storage mode changed from AHCI to IDE (or vice versa) after Windows was installed; corrupt partition/boot record; failed or disconnected boot drive; drive controller driver issue. Fix: check BIOS storage controller mode matches what Windows was installed with; run bootrec /fixbcd; or check SATA cable connection.",
    triggerPhrase: "BSOD 0x7B INACCESSIBLE_BOOT_DEVICE = boot drive not found; check BIOS AHCI/IDE setting or cable",
    weaknessTags: ["bsod-codes", "boot-sequence"],
  },
  {
    id: "pd-42-06", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A Windows system displays BSOD stop code 0x0000000A (IRQL_NOT_LESS_OR_EQUAL). What are the MOST likely causes?",
    choices: [
      { id: "a", text: "Hard drive failure or file system corruption", correct: false },
      { id: "b", text: "Faulty or incompatible driver, or defective RAM", correct: true },
      { id: "c", text: "CPU overheating above thermal limit", correct: false },
      { id: "d", text: "Corrupted Windows boot loader", correct: false },
    ],
    explanation: "IRQL_NOT_LESS_OR_EQUAL (0x0000000A) means a kernel-mode driver or hardware attempted to access memory at an interrupt request level higher than allowed. This is most commonly caused by: incompatible or buggy device drivers (just installed a new driver?), faulty RAM (run MemTest86 overnight), or incompatible hardware. Troubleshoot: boot in Safe Mode (only essential drivers load), check Event Viewer for the faulting module, update or roll back recently changed drivers.",
    triggerPhrase: "BSOD 0x0A IRQL_NOT_LESS_OR_EQUAL = bad driver or faulty RAM (run MemTest86)",
    weaknessTags: ["bsod-codes"],
  },
  {
    id: "pd-42-07", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A user reports that their hard drive makes a repetitive clicking sound and the system is sluggish. What should the technician do FIRST?",
    choices: [
      { id: "a", text: "Run CHKDSK to repair the file system", correct: false },
      { id: "b", text: "Immediately back up all data before the drive fails completely", correct: true },
      { id: "c", text: "Defragment the hard drive to fix the clicking", correct: false },
      { id: "d", text: "Update the drive firmware", correct: false },
    ],
    explanation: "The 'click of death' — a repetitive clicking from an HDD — indicates the read/write head is failing or the actuator arm is hitting its stop. The drive is in imminent failure mode. DATA BACKUP is the absolute first priority before attempting any repairs. Running CHKDSK, defragging, or any write-heavy operation on a failing drive can accelerate failure. After backup, replace the drive. SSDs don't click but may give S.M.A.R.T. warnings.",
    triggerPhrase: "HDD clicking sound = imminent failure (click of death); back up data FIRST, then replace",
    weaknessTags: ["drive-health"],
  },
  {
    id: "pd-42-08", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "During boot, the BIOS displays a S.M.A.R.T. warning: 'Hard disk failure is imminent.' What action should a technician take?",
    choices: [
      { id: "a", text: "Ignore it; S.M.A.R.T. warnings are often false alarms", correct: false },
      { id: "b", text: "Back up all data immediately and replace the drive", correct: true },
      { id: "c", text: "Run a full format to refresh the drive sectors", correct: false },
      { id: "d", text: "Update the hard drive firmware to clear the warning", correct: false },
    ],
    explanation: "S.M.A.R.T. (Self-Monitoring, Analysis, and Reporting Technology) monitors internal drive health attributes (reallocated sectors, spin-up time, read error rate, etc.). A BIOS S.M.A.R.T. warning means multiple indicators have exceeded threshold values — the drive has already started failing. Studies show a S.M.A.R.T. warning is a strong predictor of imminent failure. Back up now, order a replacement drive, clone or restore from backup.",
    triggerPhrase: "S.M.A.R.T. warning = predictive failure alert; back up immediately and replace drive",
    weaknessTags: ["drive-health"],
  },
  {
    id: "pd-42-09", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A hard drive is visible in the BIOS but does not appear in Windows Explorer. What is the MOST likely explanation?",
    choices: [
      { id: "a", text: "The drive has failed and needs to be replaced", correct: false },
      { id: "b", text: "The drive has no partition or is unformatted; initialize it in Disk Management", correct: true },
      { id: "c", text: "The SATA driver is missing and needs to be installed", correct: false },
      { id: "d", text: "The drive is encrypted and needs to be decrypted first", correct: false },
    ],
    explanation: "A drive visible in BIOS confirms it is hardware-detected. It won't appear in Windows Explorer until it has a partition with a file system. Open Disk Management (diskmgmt.msc): the drive will show as 'Unallocated' or 'Not Initialized.' Right-click > Initialize Disk (choose GPT or MBR), then right-click the unallocated space > New Simple Volume to create a partition and format it. New drives from the factory are unformatted.",
    triggerPhrase: "Drive in BIOS but not in Explorer = unformatted/no partition; use Disk Management to initialize",
    weaknessTags: ["drive-health"],
  },
  {
    id: "pd-42-10", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A RAID 5 array with 4 drives loses one drive to failure. What is the status of the array and what is the risk?",
    choices: [
      { id: "a", text: "The array is completely failed and all data is lost", correct: false },
      { id: "b", text: "The array is degraded — data is accessible but a second drive failure will cause total data loss", correct: true },
      { id: "c", text: "The array automatically rebuilds using the parity data without any risk", correct: false },
      { id: "d", text: "The array switches to RAID 0 mode automatically", correct: false },
    ],
    explanation: "RAID 5 can tolerate one drive failure (uses distributed parity). With one failed drive the array operates in degraded mode — all data is accessible by reconstructing from parity. However, during this degraded state: no fault tolerance exists (one more failure = full data loss), and the rebuild process puts enormous stress on remaining drives, which can trigger failure in aging drives. Replace the failed drive ASAP and allow rebuild to complete. Monitor with S.M.A.R.T. during rebuild.",
    triggerPhrase: "RAID 5 one drive failed = degraded mode; data accessible but NO redundancy; replace drive immediately",
    weaknessTags: ["raid-rebuild"],
  },
  {
    id: "pd-42-11", domain: "5.0-troubleshooting", difficulty: "hard", type: "single", source: "drill",
    prompt: "What Windows Recovery Environment command repairs the Master Boot Record (MBR) on a Windows installation?",
    choices: [
      { id: "a", text: "bootrec /rebuildbcd", correct: false },
      { id: "b", text: "bootrec /fixmbr", correct: true },
      { id: "c", text: "diskpart /fixboot", correct: false },
      { id: "d", text: "sfc /scannow", correct: false },
    ],
    explanation: "bootrec commands in the Windows Recovery Environment: /fixmbr = rewrites the MBR code (does not touch the partition table); /fixboot = writes a new boot sector to the system partition; /rebuildbcd = scans for Windows installations and rebuilds the BCD (Boot Configuration Data) store; /scanos = scans for Windows installations. Use /fixmbr for a corrupted MBR (e.g., from a virus). SFC /scannow repairs Windows system files but runs from within Windows.",
    triggerPhrase: "bootrec /fixmbr = repair MBR; /fixboot = repair boot sector; /rebuildbcd = rebuild boot config",
    weaknessTags: ["boot-sequence", "bsod-codes"],
  },
  {
    id: "pd-42-12", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the command to check a Windows drive for file system errors and bad sectors?",
    choices: [
      { id: "a", text: "sfc /scannow", correct: false },
      { id: "b", text: "chkdsk C: /f /r", correct: true },
      { id: "c", text: "format C: /q", correct: false },
      { id: "d", text: "defrag C: /u", correct: false },
    ],
    explanation: "CHKDSK (Check Disk) examines the file system: /f = fix file system errors; /r = locate bad sectors and recover readable data (implies /f). For a drive with Windows installed, it runs at next reboot. CHKDSK on an SSD checks logical errors but cannot repair physical bad sectors (flash cells don't work like HDD sectors). SFC /scannow checks Windows system files for corruption. Format erases everything. Defrag optimizes file placement for HDDs (not recommended for SSDs).",
    triggerPhrase: "chkdsk C: /f /r = check file system errors + bad sectors; /f = fix, /r = recover bad sectors",
    weaknessTags: ["drive-health"],
  },
  {
    id: "pd-42-13", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A system randomly restarts or shuts down without warning, with no blue screen. What are the TWO most likely causes?",
    choices: [
      { id: "a", text: "Corrupt operating system and faulty GPU driver", correct: false },
      { id: "b", text: "CPU or system overheating, or a failing PSU unable to maintain stable voltage under load", correct: true },
      { id: "c", text: "Failing RAM and corrupt hard drive", correct: false },
      { id: "d", text: "Outdated BIOS firmware and incompatible USB device", correct: false },
    ],
    explanation: "Unexpected random shutdowns without a BSOD (which would require the OS to be running) usually indicate hardware-level issues: (1) Thermal shutdown — CPU/GPU temperature exceeds safe threshold, triggering hardware protection; check temps with HWMonitor. (2) PSU voltage instability — failing capacitors cause voltage rails to drop under load, triggering immediate shutdown. Check PSU with a multimeter or PSU tester. Bad RAM more typically causes BSODs. HDD failures typically cause file errors or BSODs.",
    triggerPhrase: "Random shutdown without BSOD = overheating (check temps) or failing PSU (voltage drop under load)",
    weaknessTags: ["psu-troubleshoot", "cooling-systems"],
  },
  {
    id: "pd-42-14", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "What voltage rails does a standard ATX PSU provide, and which rail powers the CPU and GPU?",
    choices: [
      { id: "a", text: "+3.3V, +5V, +12V, -12V, +5VSB; CPU and GPU primarily use +12V", correct: true },
      { id: "b", text: "+5V and +12V only; both CPU and GPU use +5V", correct: false },
      { id: "c", text: "+12V only; all components use the same rail", correct: false },
      { id: "d", text: "+3.3V and +5V; the +12V rail is only for fans", correct: false },
    ],
    explanation: "ATX PSU rails: +3.3V (system logic, RAM), +5V (older drives, USB, motherboard logic), +12V (CPU via VRM, GPU, motors, fan headers), -12V (legacy serial ports, tiny current), +5VSB (standby power for wake-on-LAN, USB charging when off). Modern systems are heavily +12V-centric. GPU transient loads can spike 500A on the +12V rail. PSU problems on the +12V rail manifest as system crashes under GPU load.",
    triggerPhrase: "ATX rails: 3.3V (RAM/logic), 5V (USB/legacy), 12V (CPU/GPU/fans); modern systems are 12V-dominant",
    weaknessTags: ["psu-troubleshoot"],
  },
  {
    id: "pd-42-15", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A RAID 1 array has one failed drive. After replacing the failed drive, what process must occur to restore full redundancy?",
    choices: [
      { id: "a", text: "The array automatically and immediately has full redundancy once the new drive is inserted", correct: false },
      { id: "b", text: "The RAID controller rebuilds the array by copying all data from the healthy drive to the replacement drive", correct: true },
      { id: "c", text: "A full backup restore must be performed from tape to the new drive", correct: false },
      { id: "d", text: "Both drives must be wiped and restored from backup to synchronize", correct: false },
    ],
    explanation: "RAID 1 (mirroring) rebuild: the RAID controller reads every sector from the surviving healthy drive and writes it to the new blank replacement drive. During rebuild, the array is degraded (one more failure = total loss). Rebuild time depends on drive capacity and load — can take hours. The system stays online during rebuild. RAID 5 rebuild is similar but more complex, reading from all remaining drives to reconstruct missing parity/data blocks.",
    triggerPhrase: "RAID 1 after drive replacement = controller rebuilds by copying healthy drive to new drive (takes hours)",
    weaknessTags: ["raid-rebuild"],
  },

  // -- 5.4 Wireless Networking Types -------------------------------------------
  {
    id: "wn-54-01", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "Which IEEE 802.11 wireless standard operates ONLY in the 5 GHz band and has a maximum theoretical speed of 54 Mbps?",
    choices: [
      { id: "a", text: "802.11b", correct: false },
      { id: "b", text: "802.11g", correct: false },
      { id: "c", text: "802.11a", correct: true },
      { id: "d", text: "802.11n", correct: false },
    ],
    explanation: "802.11a (1999): 5 GHz only, 54 Mbps max, OFDM modulation, 8 non-overlapping channels in the U.S., shorter range than 2.4 GHz (5 GHz doesn't penetrate walls as well). 802.11b (1999): 2.4 GHz, 11 Mbps, DSSS. 802.11g (2003): 2.4 GHz, 54 Mbps, OFDM, backward compatible with 802.11b. 802.11n (Wi-Fi 4): both bands, up to 600 Mbps with MIMO. The 5 GHz + 54 Mbps combination is unique to 802.11a.",
    triggerPhrase: "802.11a = 5 GHz only, 54 Mbps; 802.11b = 2.4 GHz, 11 Mbps; 802.11g = 2.4 GHz, 54 Mbps",
    weaknessTags: ["wifi-80211-standards"],
  },
  {
    id: "wn-54-02", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "Which early Wi-Fi standard operates on 2.4 GHz and was limited to 11 Mbps, but was notable for wide compatibility with older devices?",
    choices: [
      { id: "a", text: "802.11a", correct: false },
      { id: "b", text: "802.11b", correct: true },
      { id: "c", text: "802.11g", correct: false },
      { id: "d", text: "802.11n", correct: false },
    ],
    explanation: "802.11b (1999): 2.4 GHz, 11 Mbps max, uses DSSS (Direct Sequence Spread Spectrum). It was the first widely deployed Wi-Fi standard. 802.11g (2003) improved to 54 Mbps on the same 2.4 GHz band and was backward compatible with 802.11b (though having a b device on a g network slows all traffic). 802.11a appeared simultaneously with 802.11b but operated at 5 GHz and was not directly compatible with 802.11b.",
    triggerPhrase: "802.11b = 2.4 GHz, 11 Mbps, DSSS; 802.11g = 2.4 GHz, 54 Mbps, backward-compatible with b",
    weaknessTags: ["wifi-80211-standards"],
  },
  {
    id: "wn-54-03", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which Wi-Fi standard introduced MIMO (Multiple Input Multiple Output) antennas and was the first to support BOTH the 2.4 GHz and 5 GHz bands?",
    choices: [
      { id: "a", text: "802.11g", correct: false },
      { id: "b", text: "802.11a", correct: false },
      { id: "c", text: "802.11n (Wi-Fi 4)", correct: true },
      { id: "d", text: "802.11ac (Wi-Fi 5)", correct: false },
    ],
    explanation: "802.11n (Wi-Fi 4, 2009): introduced MIMO technology (up to 4 spatial streams), channel bonding (40 MHz channels), and dual-band operation (2.4 GHz and 5 GHz). Maximum theoretical speed: 600 Mbps (4 streams x 150 Mbps). 802.11ac (Wi-Fi 5) operates only on 5 GHz but added MU-MIMO and wider channels (80/160 MHz). 802.11ax (Wi-Fi 6) added OFDMA and supports both 2.4 and 5 GHz (plus 6 GHz for Wi-Fi 6E).",
    triggerPhrase: "802.11n (Wi-Fi 4) = first dual-band (2.4+5 GHz), MIMO, 600 Mbps; ac = 5 GHz only but faster",
    weaknessTags: ["wifi-80211-standards"],
  },
  {
    id: "wn-54-04", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Wi-Fi 6 (802.11ax) introduced OFDMA. What does OFDMA enable that improves performance in dense environments?",
    choices: [
      { id: "a", text: "It allows the access point to use multiple frequency bands simultaneously", correct: false },
      { id: "b", text: "It allows the AP to serve multiple clients simultaneously by dividing channels into smaller sub-carriers", correct: true },
      { id: "c", text: "It doubles the channel width from 80 MHz to 160 MHz", correct: false },
      { id: "d", text: "It eliminates the need for channel planning in the 2.4 GHz band", correct: false },
    ],
    explanation: "OFDMA (Orthogonal Frequency Division Multiple Access) divides each channel into sub-carriers called Resource Units (RUs). Wi-Fi 6 can assign different RUs to different clients simultaneously within a single transmission — like serving multiple lanes of traffic at once rather than one car at a time. This dramatically improves efficiency in dense environments (airports, stadiums, offices). Wi-Fi 5 MU-MIMO serves multiple clients but in separate full transmissions.",
    triggerPhrase: "OFDMA (Wi-Fi 6) = multiple clients share one channel simultaneously via sub-carriers; improves dense networks",
    weaknessTags: ["wifi-6-ax"],
  },
  {
    id: "wn-54-05", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is BSS Coloring in Wi-Fi 6 and how does it help with performance?",
    choices: [
      { id: "a", text: "It assigns different LED colors to access points for easy identification in a network diagram", correct: false },
      { id: "b", text: "It tags frames with a color (BSS ID) so overlapping APs can ignore frames from other networks and transmit more freely", correct: true },
      { id: "c", text: "It encrypts data with a color-coded key for each SSID", correct: false },
      { id: "d", text: "It changes channel frequency automatically based on interference color codes", correct: false },
    ],
    explanation: "BSS Coloring assigns a numeric color (1-63) to each Basic Service Set (BSS/AP). Wi-Fi 6 devices can tell if a detected signal is from their own BSS (same color) or a neighboring BSS (different color). If a frame from a different-colored BSS is below a threshold, the device can consider the channel clear and transmit without waiting. This reduces co-channel interference penalty in dense deployments where adjacent APs use the same channel.",
    triggerPhrase: "BSS Coloring (Wi-Fi 6) = tags frames by network; lets APs transmit even when overlapping neighbors are active",
    weaknessTags: ["wifi-6-ax"],
  },
  {
    id: "wn-54-06", domain: "2.0-networking", difficulty: "hard", type: "single", source: "drill",
    prompt: "Wi-Fi 7 (802.11be) introduces Multi-Link Operation (MLO). What does MLO enable?",
    choices: [
      { id: "a", text: "Multiple access points can serve as one logical AP in a mesh network", correct: false },
      { id: "b", text: "A single device can simultaneously transmit and receive across multiple bands and channels at the same time", correct: true },
      { id: "c", text: "Multiple SSIDs can share the same encryption key", correct: false },
      { id: "d", text: "Devices can connect to both the AP and the internet gateway simultaneously", correct: false },
    ],
    explanation: "Wi-Fi 7 (802.11be) MLO (Multi-Link Operation) allows a device to simultaneously communicate over multiple radio links — e.g., 2.4 GHz + 5 GHz + 6 GHz at the same time. This enables: higher aggregate throughput (combines bandwidth of all links), lower latency (packets take the fastest available path), and better reliability (if one link is congested, others compensate). Wi-Fi 7 also introduces 320 MHz channels (2x Wi-Fi 6) and 4K-QAM modulation.",
    triggerPhrase: "Wi-Fi 7 MLO = device uses multiple bands simultaneously; 320 MHz channels; 46 Gbps theoretical max",
    weaknessTags: ["wifi-7-be"],
  },
  {
    id: "wn-54-07", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which three channels in the 2.4 GHz band are non-overlapping in North America?",
    choices: [
      { id: "a", text: "Channels 1, 5, and 10", correct: false },
      { id: "b", text: "Channels 1, 6, and 11", correct: true },
      { id: "c", text: "Channels 1, 7, and 13", correct: false },
      { id: "d", text: "Channels 2, 6, and 10", correct: false },
    ],
    explanation: "In the 2.4 GHz band, each Wi-Fi channel is 22 MHz wide with 5 MHz spacing between center frequencies. To have completely non-overlapping channels (no interference), channels must be at least 5 apart. In North America: channels 1, 6, and 11 are the three non-overlapping channels. (Some European countries allow channel 13, giving three additional non-overlapping sets.) Setting all APs in an office to channels 1, 6, and 11 minimizes co-channel interference.",
    triggerPhrase: "2.4 GHz non-overlapping channels: 1, 6, 11 (North America); channels are 22 MHz wide, 5 MHz apart",
    weaknessTags: ["wifi-frequency", "wireless-channels"],
  },
  {
    id: "wn-54-08", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which statement BEST describes the tradeoffs between 2.4 GHz and 5 GHz Wi-Fi bands?",
    choices: [
      { id: "a", text: "2.4 GHz is always faster; 5 GHz is only for legacy devices", correct: false },
      { id: "b", text: "2.4 GHz has longer range and better wall penetration; 5 GHz has higher speed but shorter range and more susceptibility to obstacles", correct: true },
      { id: "c", text: "5 GHz is more susceptible to microwave interference; 2.4 GHz is interference-free", correct: false },
      { id: "d", text: "They offer identical performance in all environments", correct: false },
    ],
    explanation: "2.4 GHz: longer wavelength = better range and wall penetration (~300m open air), but only 3 non-overlapping channels, more interference from Bluetooth, microwaves, baby monitors, and neighbor networks. 5 GHz: shorter wavelength = shorter range (~100m open air), attenuated by walls more, but up to 23+ non-overlapping channels, less interference, and higher maximum speeds. Wi-Fi 6E and 7 add the 6 GHz band: even faster speeds but shortest range, least interference.",
    triggerPhrase: "2.4 GHz = longer range, more interference, 3 channels; 5 GHz = shorter range, faster, 23+ channels",
    weaknessTags: ["wifi-frequency"],
  },
  {
    id: "wn-54-09", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "Bluetooth 5.0 improved upon Bluetooth 4.x in which of the following ways?",
    choices: [
      { id: "a", text: "Increased range by 4x and doubled data rate to 2 Mbps", correct: true },
      { id: "b", text: "Added compatibility with Wi-Fi 5 GHz band", correct: false },
      { id: "c", text: "Eliminated pairing requirements for faster connections", correct: false },
      { id: "d", text: "Increased range but reduced data rate for IoT applications", correct: false },
    ],
    explanation: "Bluetooth 5.0 (2016): 4x range vs. BT 4.2 (up to 400m outdoors in line-of-sight vs. 100m), 2x speed (2 Mbps vs 1 Mbps), 8x data broadcasting capacity. Also introduced Bluetooth Mesh for many-to-many device networks. Bluetooth still operates in the 2.4 GHz ISM band (same as Wi-Fi). Pairing is still required for traditional connections (mesh is different). BT 5.0 is backward compatible with earlier versions.",
    triggerPhrase: "Bluetooth 5.0 vs 4.x: 4x range, 2x speed (2 Mbps), 8x broadcast capacity; still 2.4 GHz",
    weaknessTags: ["short-range-wireless"],
  },
  {
    id: "wn-54-10", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the maximum effective communication range of NFC (Near Field Communication)?",
    choices: [
      { id: "a", text: "10 meters", correct: false },
      { id: "b", text: "100 meters", correct: false },
      { id: "c", text: "4 centimeters (about 1.5 inches)", correct: true },
      { id: "d", text: "1 meter", correct: false },
    ],
    explanation: "NFC operates at 13.56 MHz with a maximum range of about 4 cm (some say 10 cm theoretical max, but practical 'tap' range is ~4 cm). Data rate: 106 to 424 kbps. Uses: contactless payments (Apple Pay, Google Pay), transit cards, hotel room keys, device pairing (tap to pair Bluetooth speakers). NFC is intentionally short-range for security — you must deliberately bring devices close together, making eavesdropping difficult.",
    triggerPhrase: "NFC: 13.56 MHz, 4 cm max range, 106-424 kbps; used for contactless payments and device pairing",
    weaknessTags: ["short-range-wireless"],
  },
  {
    id: "wn-54-11", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "RFID (Radio Frequency Identification) is used in multiple frequency ranges. Which frequency range is used for retail inventory management and supply chain tracking with the longest read range?",
    choices: [
      { id: "a", text: "Low Frequency (LF) 125 kHz — range up to 10 cm", correct: false },
      { id: "b", text: "High Frequency (HF) 13.56 MHz — range up to 1 meter", correct: false },
      { id: "c", text: "Ultra High Frequency (UHF) 860-960 MHz — range up to 12 meters", correct: true },
      { id: "d", text: "Microwave 2.4 GHz — range over 100 meters", correct: false },
    ],
    explanation: "RFID frequency ranges: LF (125-134 kHz): animal tags, access cards, 10 cm range. HF (13.56 MHz): smart cards, library books, passports, NFC, 1 meter range. UHF (860-960 MHz): retail/warehouse inventory (those plastic tags on clothes), supply chain, toll roads, up to 12 meters. Passive UHF tags have no battery — they harvest energy from the reader's RF field. UHF is the type used in store anti-theft systems.",
    triggerPhrase: "RFID: LF=animal tags/10cm, HF=smart cards/1m, UHF=retail inventory/12m (longest range)",
    weaknessTags: ["short-range-wireless"],
  },
  {
    id: "wn-54-12", domain: "2.0-networking", difficulty: "easy", type: "single", source: "drill",
    prompt: "A network administrator uses a Wi-Fi analyzer tool and sees that several SSIDs from neighboring businesses are all using channel 6 in the 2.4 GHz band. What should the administrator do?",
    choices: [
      { id: "a", text: "Switch to channel 6 as well so all APs can share the channel efficiently", correct: false },
      { id: "b", text: "Set the office AP to channel 1 or channel 11 to avoid co-channel interference", correct: true },
      { id: "c", text: "Reduce transmit power to below-minimum to avoid interfering", correct: false },
      { id: "d", text: "Upgrade to 802.11b to use different modulation", correct: false },
    ],
    explanation: "Wi-Fi analyzer tools (like WiFi Analyzer on Android or inSSIDer on Windows) show which channels are in use. If neighbors are all on channel 6, co-channel interference will degrade performance. Move to channel 1 or 11 (the other non-overlapping 2.4 GHz channels). Alternatively, move to 5 GHz (many more non-overlapping channels). Never use channels like 3, 4, 7, or 8 as primary channels — they overlap with multiple other channels simultaneously.",
    triggerPhrase: "Neighbors on channel 6: switch to 1 or 11 (the other non-overlapping 2.4 GHz channels)",
    weaknessTags: ["wireless-channels", "wifi-frequency"],
  },
  {
    id: "wn-54-13", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "Which security improvement does WPA3 provide over WPA2 for personal networks (PSK mode)?",
    choices: [
      { id: "a", text: "WPA3 uses AES-256 instead of AES-128", correct: false },
      { id: "b", text: "WPA3-Personal uses SAE (Simultaneous Authentication of Equals) instead of PSK, providing forward secrecy and brute-force resistance", correct: true },
      { id: "c", text: "WPA3 requires a RADIUS server for authentication", correct: false },
      { id: "d", text: "WPA3 disables backward compatibility with WPA2 for better security", correct: false },
    ],
    explanation: "WPA3-Personal replaces WPA2-PSK's Pre-Shared Key handshake with SAE (Dragonfly handshake). SAE provides: (1) Forward secrecy — past traffic cannot be decrypted even if the password is later compromised. (2) Brute-force resistance — each guess requires interacting with the AP (no offline dictionary attacks using captured handshakes). (3) Protects weak passwords better. WPA3-Enterprise uses 192-bit security suite. WPA3 uses CCMP-128 (same as WPA2) by default.",
    triggerPhrase: "WPA3-Personal = SAE replaces PSK; forward secrecy + brute-force resistance; stronger even with weak passwords",
    weaknessTags: ["wifi-80211-standards"],
  },
  {
    id: "wn-54-14", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "802.11ac (Wi-Fi 5) improved upon 802.11n in several ways. Which statement about 802.11ac is CORRECT?",
    choices: [
      { id: "a", text: "802.11ac supports both 2.4 GHz and 5 GHz bands", correct: false },
      { id: "b", text: "802.11ac operates exclusively on 5 GHz, supports up to 8 spatial streams, wider channels (up to 160 MHz), and MU-MIMO", correct: true },
      { id: "c", text: "802.11ac introduced OFDMA for improved dense-network performance", correct: false },
      { id: "d", text: "802.11ac max speed is 300 Mbps per stream", correct: false },
    ],
    explanation: "802.11ac (Wi-Fi 5, 2013): 5 GHz only (clients connect to 2.4 GHz via 802.11n legacy), up to 8 spatial streams (vs. 4 in 802.11n), 80 MHz standard / 160 MHz optional channels (vs. 40 MHz max in 802.11n), MU-MIMO downlink (serves multiple clients). Max theoretical: 6.93 Gbps (8 streams, 160 MHz, 256-QAM). OFDMA was introduced by 802.11ax (Wi-Fi 6), not 802.11ac. Real-world speeds are typically 300-900 Mbps for consumer routers.",
    triggerPhrase: "802.11ac (Wi-Fi 5) = 5 GHz only, MU-MIMO, 160 MHz channels; OFDMA was Wi-Fi 6's addition",
    weaknessTags: ["wifi-80211-standards", "wifi-6-ax"],
  },
  {
    id: "wn-54-15", domain: "2.0-networking", difficulty: "medium", type: "single", source: "drill",
    prompt: "When performing a wireless site survey for a new office Wi-Fi installation, what is the PRIMARY purpose?",
    choices: [
      { id: "a", text: "To configure SSID names and passwords for all access points", correct: false },
      { id: "b", text: "To map signal coverage, identify dead zones and interference sources, and determine optimal AP placement and channel assignment", correct: true },
      { id: "c", text: "To test internet speed from the ISP connection", correct: false },
      { id: "d", text: "To document the MAC addresses of all wireless devices in the building", correct: false },
    ],
    explanation: "A wireless site survey is performed before AP installation to: walk the site with a meter measuring signal strength and interference, identify physical obstacles (concrete, HVAC, metal) that block signals, locate existing sources of interference (neighboring Wi-Fi, microwave equipment), determine how many APs are needed and where to place them, and plan channel assignments to minimize co-channel interference. Tools: Ekahau, NetSpot, AirMagnet. A passive survey uses existing signals; an active survey uses a temporary AP.",
    triggerPhrase: "Wireless site survey = map signal strength/dead zones/interference BEFORE installing APs; determine AP placement",
    weaknessTags: ["wifi-80211-standards", "wifi-frequency"],
  },
];
'@
$result = $trimmed + $newQuestions
[System.IO.File]::WriteAllText($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Batch B done. Total lines: $((Get-Content $file).Count)"
