$file = "C:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$insertAt = $content.LastIndexOf('];')

$newQuestions = @'

  // === External Practice Questions Set 5 ===
  {
    id: "ext5-q01",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What issue does constant indicator LED activity on a computer imply?",
    choices: [
      { id: "a", text: "Connector fault", correct: false },
      { id: "b", text: "Faulty boot sector", correct: false },
      { id: "c", text: "Not enough system RAM", correct: true },
      { id: "d", text: "Mechanical problem", correct: false },
    ],
    explanation: "Constant (non-stop) hard drive activity LED means the OS is continuously reading and writing to the pagefile/swap file on disk. This happens when physical RAM is exhausted and the OS must use virtual memory on the drive, causing incessant disk I/O and a permanently lit activity LED. A connector fault or faulty boot sector would prevent the system from booting at all. A mechanical problem alone would not cause this specific continuous-activity pattern.",
    triggerPhrase: "Constant drive activity LED = out of RAM, OS is paging to disk",
    weaknessTags: ["drive-health", "memory-types"],
  },
  {
    id: "ext5-q02",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A company has a structured cable system installed by a technician. The technician uses a permanent cable that terminates to wall ports and patch panels. What is this mechanism called?",
    choices: [
      { id: "a", text: "T568A", correct: false },
      { id: "b", text: "Punchdown block", correct: true },
      { id: "c", text: "RJ11", correct: false },
      { id: "d", text: "RJ45", correct: false },
    ],
    explanation: "In structured cabling, permanent horizontal runs are terminated to wall outlet keystones and patch panels using punchdown connections (IDC - Insulation Displacement Connectors). The punchdown block forces each wire conductor into a slot that cuts through the insulation to make contact, without stripping the wire first. T568A is the wiring color-code standard for pin assignments. RJ45 is the modular plug crimped onto patch cable ends (not permanent runs). RJ11 is the smaller connector used for telephone lines.",
    triggerPhrase: "Permanent cable terminated to wall ports and patch panels = punchdown block",
    weaknessTags: ["copper-tools", "wiring-standards"],
  },
  {
    id: "ext5-q03",
    domain: "5.0-troubleshooting",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "To minimize cabling, audio and video can be sent over a single cable using HDMI or what other interface?",
    choices: [
      { id: "a", text: "VGA", correct: false },
      { id: "b", text: "DVI", correct: false },
      { id: "c", text: "DisplayPort", correct: true },
      { id: "d", text: "S-Video", correct: false },
    ],
    explanation: "Both HDMI and DisplayPort carry audio and video signals over a single cable, eliminating the need for a separate audio cable. VGA is an analog video-only signal (no audio). DVI carries video only (digital or analog) with no audio channel. S-Video is an older analog video-only format. DisplayPort additionally supports daisy-chaining multiple monitors from one port and can also carry USB data (USB-C/Thunderbolt variants).",
    triggerPhrase: "Single cable for audio + video = HDMI or DisplayPort (not VGA, not DVI)",
    weaknessTags: ["display-cables", "display-tech"],
  },
  {
    id: "ext5-q04",
    domain: "5.0-troubleshooting",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A flickering image on a display could be caused by the backlight starting to fail or what other component beginning to fail?",
    choices: [
      { id: "a", text: "GPU driver", correct: false },
      { id: "b", text: "Circuitry", correct: true },
      { id: "c", text: "Refresh rate setting", correct: false },
      { id: "d", text: "Display cable", correct: false },
    ],
    explanation: "Display flickering is caused by hardware failure: most commonly a dying backlight (fluorescent CCFL or LED strips) or failing internal display circuitry such as the inverter board (which drives CCFL backlights) or the timing controller (TCON) board. A GPU driver issue can cause flickering but is a software problem, not a component failing. A low refresh rate causes perceived flicker at the eye level but is a configuration setting, not a failing part. A display cable causing flickering would typically produce intermittent signal loss rather than a steady flicker.",
    triggerPhrase: "Flickering display = failing backlight OR failing display circuitry (inverter/TCON)",
    weaknessTags: ["display-tech", "laptop-display"],
  },
  {
    id: "ext5-q05",
    domain: "5.0-troubleshooting",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "When a projector makes a 'pop' sound during operation, this may be an indication of what?",
    choices: [
      { id: "a", text: "Loose power cable", correct: false },
      { id: "b", text: "Overheating fan failure", correct: false },
      { id: "c", text: "Burned-out bulb", correct: true },
      { id: "d", text: "HDMI signal loss", correct: false },
    ],
    explanation: "A 'pop' sound from a projector is a classic sign of a burned-out lamp. Projector lamps are high-pressure mercury or UHP bulbs that can fail suddenly with an audible pop as the pressurized glass envelope ruptures or the filament breaks. After the pop, the projector will go dark and display an error. Projector lamps are consumables with rated lifespans (typically 2,000-5,000 hours) and must be replaced. A loose power cable or fan failure would not produce a pop, and HDMI signal loss is a connection issue only.",
    triggerPhrase: "Projector 'pop' sound = burned-out lamp/bulb",
    weaknessTags: ["display-tech", "laser-maintenance"],
  },
  {
    id: "ext5-q06",
    domain: "3.0-hardware",
    difficulty: "hard",
    type: "single",
    source: "concept-builder",
    prompt: "A technician uses a U.2 interface on the motherboard that enables storage access and transport to deliver the highest throughput and fastest response time. What component is being used?",
    choices: [
      { id: "a", text: "SSD", correct: false },
      { id: "b", text: "HDD", correct: false },
      { id: "c", text: "mSATA", correct: false },
      { id: "d", text: "NVMe", correct: true },
    ],
    explanation: "U.2 (formerly SFF-8639) is an enterprise physical connector that interfaces NVMe (Non-Volatile Memory Express) drives directly to the PCIe bus, delivering the highest storage throughput and lowest latency of any current storage technology (sequential reads up to 7+ GB/s, latency under 20 microseconds). 'SSD' is too broad — it includes slower SATA SSDs. HDD uses SATA or SAS, not U.2. mSATA is a legacy compact form factor that uses the SATA protocol. NVMe over U.2 is the correct, specific answer.",
    triggerPhrase: "U.2 interface = enterprise NVMe (highest throughput + lowest latency)",
    weaknessTags: ["sata-interface", "m2-slots"],
  },
  {
    id: "ext5-q07",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A system administrator implemented a physical device that expedites cryptographic operations and manages cryptographic keys. What is this device?",
    choices: [
      { id: "a", text: "Boot options", correct: false },
      { id: "b", text: "TPM", correct: true },
      { id: "c", text: "Secure boot", correct: false },
      { id: "d", text: "HSM", correct: false },
    ],
    explanation: "A TPM (Trusted Platform Module) is a dedicated microprocessor chip embedded on the motherboard that generates, stores, and manages cryptographic keys while performing cryptographic operations such as disk encryption (BitLocker) and platform integrity verification. Secure boot is a UEFI firmware feature that verifies the boot process using keys stored in the TPM — it is a feature, not a device. Boot options are BIOS/UEFI startup settings. An HSM (Hardware Security Module) is a separate enterprise-grade appliance for bulk cryptographic processing, more commonly covered in Security+ rather than CompTIA A+.",
    triggerPhrase: "Chip on motherboard for cryptographic keys and operations = TPM",
    weaknessTags: ["boot-sequence", "boot-errors"],
  },
  {
    id: "ext5-q08",
    domain: "4.0-virtualization-cloud",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What is the typical use for virtual desktop platforms based on a guest OS hypervisor?",
    choices: [
      { id: "a", text: "Cross-platform virtualization", correct: true },
      { id: "b", text: "Legacy software/OS", correct: false },
      { id: "c", text: "Testing and development", correct: false },
      { id: "d", text: "Resource requirements", correct: false },
    ],
    explanation: "Guest OS hypervisors (Type 2 hypervisors) — such as VMware Workstation, VirtualBox, and Parallels Desktop — run on top of an existing host OS. Their primary/typical use is cross-platform virtualization: running a different operating system on the same hardware (e.g., running Windows on a Mac, or Linux inside Windows). Type 1 (bare-metal) hypervisors run directly on hardware and are used in server production environments. While Type 2 VMs are also used for testing/development and legacy software, cross-platform compatibility is the defining typical use case.",
    triggerPhrase: "Type 2 / guest OS hypervisor (VirtualBox, Parallels) = cross-platform virtualization",
    weaknessTags: ["multitenancy"],
  },
  {
    id: "ext5-q09",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A network administrator noticed that latency has been higher than their service-level agreement (SLA) covers for quite some time. What should they do?",
    choices: [
      { id: "a", text: "Check cabling and NICs.", correct: false },
      { id: "b", text: "Diagnose with a certifier.", correct: false },
      { id: "c", text: "Implement QoS.", correct: false },
      { id: "d", text: "Contact the ISP.", correct: true },
    ],
    explanation: "An SLA is a contract between the organization and their ISP guaranteeing specific performance metrics including maximum latency. When latency consistently exceeds the SLA threshold for an extended period, the correct action is to contact the ISP — they are in breach of the contractual agreement. QoS (Quality of Service) prioritizes traffic types but cannot reduce latency below the ISP's physical baseline. Internal troubleshooting (cables, NICs, certifier) would have been done already given the extended timeframe, and those are for internal network issues, not ISP-side latency.",
    triggerPhrase: "Latency consistently above SLA = contact the ISP (they are in breach of contract)",
    weaknessTags: ["jitter-vs-latency", "voip-tshooting"],
  },
  {
    id: "ext5-q10",
    domain: "1.0-mobile",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A developer uses a design that implements a system-on-chip (SoC) that controls video, sound, networking, and storage as part of the CPU. What is the developer using?",
    choices: [
      { id: "a", text: "Intel", correct: false },
      { id: "b", text: "ARM", correct: true },
      { id: "c", text: "AMD", correct: false },
      { id: "d", text: "M.2", correct: false },
    ],
    explanation: "ARM processors are built around the SoC (System-on-a-Chip) architecture, integrating the CPU, GPU, memory controller, audio, networking (Wi-Fi/Bluetooth), and storage controller onto a single chip die. This is the standard design for smartphones, tablets, and modern mobile devices (e.g., Apple M-series, Qualcomm Snapdragon). Intel and AMD traditionally use a multi-chip architecture with a separate chipset, though modern designs are increasingly integrated. M.2 is a physical storage form factor/slot, not a processor architecture.",
    triggerPhrase: "SoC (CPU + video + audio + networking + storage on one chip) = ARM",
    weaknessTags: ["motherboard-id", "expansion-bus"],
  },
'@

$newContent = $content.Substring(0, $insertAt) + $newQuestions + "`n];"
[System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Ext5 done. Total lines: $($newContent.Split("`n").Length)"
