$file = "c:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$trimmed = $content.TrimEnd().Substring(0, $content.TrimEnd().LastIndexOf('];'))
$newQuestions = @'

  // -- 10.2 Print Device Maintenance -------------------------------------------
  {
    id: "pm-102-01", domain: "3.0-hardware", difficulty: "hard", type: "single", source: "drill",
    prompt: "Place the seven steps of the laser printer imaging process in the correct order.",
    choices: [
      { id: "a", text: "Processing > Charging > Exposing > Developing > Transferring > Fusing > Cleaning", correct: true },
      { id: "b", text: "Charging > Processing > Exposing > Developing > Transferring > Fusing > Cleaning", correct: false },
      { id: "c", text: "Processing > Exposing > Charging > Developing > Fusing > Transferring > Cleaning", correct: false },
      { id: "d", text: "Cleaning > Charging > Exposing > Developing > Transferring > Fusing > Processing", correct: false },
    ],
    explanation: "Laser printer 7-step imaging process: (1) Processing: RIP (Raster Image Processor) converts document to bitmap. (2) Charging: primary charge roller (PCR) puts uniform negative charge (~-600V) on drum surface. (3) Exposing: laser beam discharges specific areas (~-100V) forming latent image. (4) Developing: negatively charged toner attracted to less-negative exposed areas. (5) Transferring: transfer roller/belt applies positive charge to paper, pulling toner onto paper. (6) Fusing: heat (~200°C) and pressure fuse toner to paper permanently. (7) Cleaning: cleaning blade removes residual toner from drum.",
    triggerPhrase: "Laser 7 steps: Processing > Charging > Exposing > Developing > Transferring > Fusing > Cleaning",
    weaknessTags: ["laser-imaging"],
  },
  {
    id: "pm-102-02", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "In a laser printer, what is the function of the primary charge roller (PCR)?",
    choices: [
      { id: "a", text: "It applies toner to the drum surface", correct: false },
      { id: "b", text: "It applies a uniform negative electrical charge to the photosensitive drum to prepare it for exposure", correct: true },
      { id: "c", text: "It transfers the toner image from the drum to the paper", correct: false },
      { id: "d", text: "It heats the toner to fuse it to the paper", correct: false },
    ],
    explanation: "The primary charge roller (PCR) — also called the primary corona wire in older printers — applies a uniform high-voltage negative charge (typically -600V) across the entire surface of the photosensitive drum. This prepares the drum for the exposure/writing step. After the laser exposes areas to ~-100V, the contrast between charged (-600V) and discharged (-100V) areas allows toner (also negatively charged) to adhere only to the less-negative exposed areas (opposite charges attract).",
    triggerPhrase: "PCR (Primary Charge Roller) = applies uniform -600V charge to drum; prepares drum for laser exposure",
    weaknessTags: ["laser-imaging"],
  },
  {
    id: "pm-102-03", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "At what step in the laser printing process does the laser beam play its role, and what does it physically do?",
    choices: [
      { id: "a", text: "Developing step — the laser heats toner particles to make them stick to the drum", correct: false },
      { id: "b", text: "Exposing step — the laser selectively discharges areas of the drum to create a latent electrostatic image", correct: true },
      { id: "c", text: "Charging step — the laser charges the drum surface to prepare it for toner", correct: false },
      { id: "d", text: "Transferring step — the laser directs toner onto the paper", correct: false },
    ],
    explanation: "In the Exposing (Writing) step, the laser beam scans across the rotating drum using a spinning mirror. Wherever the laser strikes the drum, it discharges that area from ~-600V to ~-100V. The discharged areas form the latent (invisible) electrostatic image of the text/graphics to be printed. The image exists only as a pattern of electrical charges on the drum at this point. No toner is involved until the Developing step.",
    triggerPhrase: "Exposing step: laser discharges specific drum areas from -600V to -100V, creating latent electrostatic image",
    weaknessTags: ["laser-imaging"],
  },
  {
    id: "pm-102-04", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "During the Developing step of laser printing, why does toner adhere to the exposed (laser-written) areas of the drum rather than the unexposed areas?",
    choices: [
      { id: "a", text: "The exposed areas are heated by the laser, causing toner to melt onto them", correct: false },
      { id: "b", text: "Toner is negatively charged; exposed areas are less negative (-100V) than unexposed areas (-600V), so toner is relatively attracted to the exposed areas", correct: true },
      { id: "c", text: "The toner is positively charged and attracted to the most negative areas", correct: false },
      { id: "d", text: "Toner sticks due to humidity from the paper feeding mechanism", correct: false },
    ],
    explanation: "Toner particles carry a negative charge. The drum surface is -600V (unexposed) and -100V (exposed by laser). Negatively charged toner is repelled by the highly negative -600V unexposed areas and relatively attracted to the less-negative -100V exposed areas. This is called 'charge area development' or 'write-black' mode (toner goes where laser wrote). The developing roller/magnetic brush continuously supplies charged toner to the drum surface.",
    triggerPhrase: "Toner is negative; sticks to laser-exposed areas (-100V) NOT unexposed areas (-600V); repelled by high negative charge",
    weaknessTags: ["laser-imaging"],
  },
  {
    id: "pm-102-05", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What does a laser printer maintenance kit typically include, and when should it be replaced?",
    choices: [
      { id: "a", text: "New toner cartridges; replace every 500 pages", correct: false },
      { id: "b", text: "Fuser, transfer roller, pickup rollers, and separation pads; replace based on page count (typically every 100,000-200,000 pages)", correct: true },
      { id: "c", text: "New laser/scanner unit and mirror assembly; replace annually", correct: false },
      { id: "d", text: "New power supply and main board; replace after 5 years", correct: false },
    ],
    explanation: "Laser printer maintenance kits contain the wear items that degrade with use: fuser assembly (heat element, pressure roller), transfer roller, pickup/feed rollers (one per tray), and separation pad. The printer's page count meter triggers a 'Perform Maintenance' warning at the kit's rated interval (e.g., 100K, 150K, or 200K pages depending on model). Replacing these items proactively prevents paper jams, poor print quality, and ghost images from developing. After installing the kit, reset the maintenance counter in the printer menu.",
    triggerPhrase: "Maintenance kit = fuser + transfer roller + pickup rollers; replace at rated page count (100-200K); reset counter after",
    weaknessTags: ["laser-maintenance"],
  },
  {
    id: "pm-102-06", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "Why is fuser temperature (~200°C) critical in a laser printer, and what happens if the fuser fails?",
    choices: [
      { id: "a", text: "The fuser charges the toner particles; if it fails, toner doesn't stick to the drum", correct: false },
      { id: "b", text: "The fuser melts and permanently bonds toner to paper; if it fails, toner smears or wipes off printed pages", correct: true },
      { id: "c", text: "The fuser sterilizes the paper before printing; if it fails, the paper feed mechanism jams", correct: false },
      { id: "d", text: "The fuser dries the ink on inkjet printers; laser printers don't have fusers", correct: false },
    ],
    explanation: "Toner is a plastic-based powder. The fuser assembly uses a heated roller (or flash fusing lamp) at ~180-220°C combined with pressure to melt the toner plastic into the paper fibers, permanently bonding them. This is why laser-printed pages feel slightly warm and are waterproof. If the fuser fails or temperature is wrong: toner wipes off pages (cold fuser), ghost/shadow images from previous pages appear (fuser not cleaning), or pages come out crinkled (excessive heat/pressure). 'Smear test': fresh print; run finger over text — if smears, fuser issue.",
    triggerPhrase: "Fuser = ~200°C heat + pressure melts toner into paper; fuser failure = toner smears off page",
    weaknessTags: ["laser-maintenance", "laser-imaging"],
  },
  {
    id: "pm-102-07", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What is the difference between thermal inkjet and piezoelectric inkjet printing technology?",
    choices: [
      { id: "a", text: "Thermal inkjet uses a laser for ink transfer; piezoelectric uses heat", correct: false },
      { id: "b", text: "Thermal inkjet uses heat bubbles to eject ink; piezoelectric uses electrically-controlled crystals to push ink through nozzles", correct: true },
      { id: "c", text: "Thermal inkjet is used in commercial printers; piezoelectric is only for home use", correct: false },
      { id: "d", text: "They are identical technologies with different manufacturer names", correct: false },
    ],
    explanation: "Thermal inkjet (most consumer printers — HP, Canon): a tiny heating element (resistor) in each nozzle rapidly heats ink to ~300°C, forming a vapor bubble that ejects a droplet. Heating/cooling degrades the nozzle over time (often built into cartridge so replaced with cartridge). Piezoelectric inkjet (Epson printers): a piezoelectric crystal deforms electrically to mechanically push ink out without heat. Advantages: longer-lived printhead, works with more ink types (dye, pigment, UV, solvent), more precise droplet control.",
    triggerPhrase: "Thermal inkjet = heat bubble ejects ink (HP/Canon); Piezoelectric = crystal deforms to push ink (Epson); no heat",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "pm-102-08", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "How should an inkjet printhead be maintained when print quality degrades (streaks, missing colors)?",
    choices: [
      { id: "a", text: "Replace the entire printer as inkjet printheads cannot be serviced", correct: false },
      { id: "b", text: "Run the printer's built-in printhead cleaning utility, then print an alignment/nozzle check page", correct: true },
      { id: "c", text: "Manually clean the printhead with acetone to dissolve dried ink", correct: false },
      { id: "d", text: "Update the printer driver to fix software-level color errors", correct: false },
    ],
    explanation: "Inkjet printhead maintenance: (1) Print a nozzle check pattern to identify clogged nozzles (missing rows = clogged). (2) Run the automatic cleaning cycle (printer utility) — this flushes ink through nozzles. May need 2-3 cleaning cycles. (3) Print alignment page to correct printhead alignment after cleaning. Manual cleaning (if automatic fails): dampen a lint-free cloth or cotton swab with distilled water or isopropyl alcohol, gently wipe nozzle plate. Never use acetone or abrasives. Preventive: print regularly (weekly) to prevent ink from drying in nozzles.",
    triggerPhrase: "Inkjet streaks/missing colors: run nozzle check > cleaning utility > alignment; print regularly to prevent clogs",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "pm-102-09", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "Thermal printers (like receipt printers) use special paper. What makes thermal paper work and what must be avoided?",
    choices: [
      { id: "a", text: "Thermal paper contains iron filings that align with a magnetic printhead", correct: false },
      { id: "b", text: "Thermal paper is coated with heat-sensitive chemicals that darken when heated; avoid sunlight, heat, and solvents which cause premature darkening", correct: true },
      { id: "c", text: "Thermal paper is pre-soaked with ink that is activated by the printhead pressure", correct: false },
      { id: "d", text: "Thermal paper contains UV-reactive ink; the printer exposes it with UV light", correct: false },
    ],
    explanation: "Thermal paper is coated with a layer of heat-sensitive chemicals (leuco dye + developer). When the thermal printhead heats specific areas, a chemical reaction produces the dark color (text/image). No ink, toner, or ribbon is required. Vulnerabilities: exposure to heat (car dashboard, sunlight), UV light, chemicals (receipt receipts in plastic bags with BPA plasticizers), hand lotions, or alcohol can cause the entire paper to darken or the image to fade. Store thermal paper away from heat and sunlight.",
    triggerPhrase: "Thermal paper = heat-sensitive chemical coating; no ink needed; avoid heat/sunlight/solvents which cause premature darkening",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "pm-102-10", domain: "3.0-hardware", difficulty: "easy", type: "single", source: "drill",
    prompt: "What type of printer is BEST suited for printing multipart carbon copy forms (NCR paper)?",
    choices: [
      { id: "a", text: "Laser printer", correct: false },
      { id: "b", text: "Inkjet printer", correct: false },
      { id: "c", text: "Impact/dot-matrix printer", correct: true },
      { id: "d", text: "Thermal printer", correct: false },
    ],
    explanation: "Impact (dot-matrix) printers use a printhead with pins that physically strike an inked ribbon against paper. This physical impact transfers ink and simultaneously presses through multiple layers of NCR (No Carbon Required) paper or actual carbon paper. Laser and inkjet printers only print on the top sheet. Thermal printers only work with special paper. Impact printers are still used in: automotive service (multi-part invoices), shipping/logistics, restaurants (kitchen tickets), banking, and any application requiring simultaneous multiple copies.",
    triggerPhrase: "Multi-part/carbon copy forms = impact/dot-matrix printer (pins physically strike through multiple layers)",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "pm-102-11", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "Comparing total cost of ownership (TCO), laser printers typically have higher upfront cost but lower per-page cost than inkjet printers. Why?",
    choices: [
      { id: "a", text: "Laser toner cartridges are cheaper to manufacture than ink cartridges", correct: false },
      { id: "b", text: "Toner cartridges yield thousands of pages vs. hundreds for ink cartridges, and toner does not dry out when unused", correct: true },
      { id: "c", text: "Laser printers use less electricity, reducing operating costs", correct: false },
      { id: "d", text: "Laser printers do not require maintenance kits, reducing long-term service costs", correct: false },
    ],
    explanation: "TCO comparison: Inkjet: low upfront cost ($50-200), but ink cartridges yield 200-500 pages and dry out when unused, requiring cleaning cycles. CPP (cost per page) can be $0.10-0.25 per page. Laser: higher upfront ($200-800+), but toner cartridges yield 2,000-25,000+ pages, toner doesn't dry out, faster printing, lower CPP ($0.01-0.05). For low-volume home users who print infrequently, inkjet may actually be cheaper despite higher CPP due to lower purchase price. For office use, laser wins on TCO.",
    triggerPhrase: "Laser TCO advantage: toner lasts thousands of pages + doesn't dry out; inkjet dries out + fewer pages per cartridge",
    weaknessTags: ["laser-maintenance"],
  },
  {
    id: "pm-102-12", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the purpose of the ozone filter in older laser printers, and what happens when it is not replaced?",
    choices: [
      { id: "a", text: "It filters dust from the paper to prevent drum contamination; when clogged it causes paper jams", correct: false },
      { id: "b", text: "It filters ozone gas produced by the corona wire; when clogged it allows ozone smell and can damage nearby materials", correct: true },
      { id: "c", text: "It removes toner particles from exhaust air; when clogged the printer overheats", correct: false },
      { id: "d", text: "It provides clean air to the fuser; when dirty it causes toner not to fuse properly", correct: false },
    ],
    explanation: "Older laser printers with corona wires (instead of charge rollers) produce ozone gas (O3) as a byproduct of the high-voltage electrical discharge. Ozone is a lung irritant and can degrade rubber and plastic components. The ozone filter (activated carbon) absorbs the ozone before it exits the printer. When the filter is saturated: you'll smell a sharp electrical/ozone odor near the printer. Replace the filter as part of routine maintenance (usually at the same interval as the maintenance kit). Modern printers use PCRs (lower voltage) and produce less ozone.",
    triggerPhrase: "Ozone filter = absorbs ozone from corona wire; replace regularly; smell of ozone = filter saturated",
    weaknessTags: ["laser-maintenance"],
  },
  {
    id: "pm-102-13", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "In the laser printer process, what component is responsible for removing residual toner from the drum surface after transfer?",
    choices: [
      { id: "a", text: "The fuser assembly", correct: false },
      { id: "b", text: "The cleaning blade", correct: true },
      { id: "c", text: "The primary charge roller", correct: false },
      { id: "d", text: "The transfer roller", correct: false },
    ],
    explanation: "The Cleaning step (7th step): after toner is transferred to paper, some residual toner remains on the drum. A cleaning blade (or sometimes a cleaning roller/brush) scrapes this residual toner off the drum surface. The waste toner is collected in a waste toner reservoir. This prepares the drum for the next print cycle. The cleaning assembly is usually part of the toner cartridge/drum unit. A worn cleaning blade causes 'ghost images' (faint repeating image from the previous page) or toner smears on the back of pages.",
    triggerPhrase: "Cleaning blade = removes residual toner from drum after transfer; worn blade causes ghost images",
    weaknessTags: ["laser-imaging", "laser-maintenance"],
  },
  {
    id: "pm-102-14", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "An impact dot-matrix printer produces faded output. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The printhead temperature is too low", correct: false },
      { id: "b", text: "The ink ribbon is worn out and needs to be replaced", correct: true },
      { id: "c", text: "The paper is too thick for impact printing", correct: false },
      { id: "d", text: "The toner cartridge is low", correct: false },
    ],
    explanation: "Impact dot-matrix printers use a fabric ribbon soaked with ink. The printhead pins strike the ribbon against the paper. As the ribbon is used, the ink depletes and strikes produce lighter output. Symptoms of a worn ribbon: faded, light, or inconsistent print across the page. Fix: replace the ribbon cartridge. Note: impact printers do not use toner or thermal paper. If output is missing specific rows of dots (not just faded), individual pins in the printhead may be stuck or broken — requires printhead replacement.",
    triggerPhrase: "Dot-matrix faded output = worn ink ribbon; replace ribbon; missing dot rows = broken printhead pins",
    weaknessTags: ["inkjet-thermal-impact"],
  },
  {
    id: "pm-102-15", domain: "3.0-hardware", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is the function of the transfer roller in a laser printer?",
    choices: [
      { id: "a", text: "It transfers toner from the supply hopper to the developing roller", correct: false },
      { id: "b", text: "It applies a positive electrical charge to the back of the paper, attracting the negatively charged toner from the drum onto the paper", correct: true },
      { id: "c", text: "It fuses the toner to the paper using heat and pressure", correct: false },
      { id: "d", text: "It feeds paper from the paper tray into the printer", correct: false },
    ],
    explanation: "The transfer roller applies a positive voltage to the underside of the paper as it passes between the drum and the roller. This positive charge attracts the negatively charged toner particles off the drum surface and onto the paper. At this point, the toner is only held by electrostatic attraction and can still be smudged. The fuser then permanently bonds the toner. The transfer roller is a wear item replaced in maintenance kits — a worn or contaminated transfer roller causes uneven toner transfer, light areas, or toner spots on the back of pages.",
    triggerPhrase: "Transfer roller = applies positive charge to paper's back, pulling toner from drum to paper; wear item in kit",
    weaknessTags: ["laser-imaging"],
  },

  // -- 10.3 Troubleshoot Print Devices -----------------------------------------
  {
    id: "tp-103-01", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer outputs pages with a faint, repeating ghost image of a previously printed page at regular intervals. What component is MOST likely causing this?",
    choices: [
      { id: "a", text: "The toner cartridge is low on toner", correct: false },
      { id: "b", text: "The drum unit or fuser assembly is not cleaning residual toner properly", correct: true },
      { id: "c", text: "The paper is too thin for the printer", correct: false },
      { id: "d", text: "The printer driver is sending duplicate print jobs", correct: false },
    ],
    explanation: "Ghost images (secondary images, shadowing): occur when residual toner from a previous print cycle is not fully removed or residual charge on the drum causes re-imaging. Causes: worn cleaning blade (doesn't scrape drum clean), worn/contaminated drum that retains charge patterns, or a cold fuser (toner not fully fused, remaining on the fuser rollers and transferring to subsequent pages). The interval of ghosting indicates the drum circumference (drum ghost) or fuser roller circumference. Replace drum unit or fuser based on interval measurement.",
    triggerPhrase: "Ghost/shadow image at regular intervals = worn drum (cleaning blade) or fuser contamination; interval = drum or fuser circumference",
    weaknessTags: ["print-quality-issues", "laser-maintenance"],
  },
  {
    id: "tp-103-02", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer produces output where the toner smears when you touch the page immediately after printing. What component has failed?",
    choices: [
      { id: "a", text: "The drum unit needs to be replaced", correct: false },
      { id: "b", text: "The fuser assembly is not reaching the correct temperature to melt and bond the toner", correct: true },
      { id: "c", text: "The wrong type of paper is being used", correct: false },
      { id: "d", text: "The transfer roller is applying too much voltage", correct: false },
    ],
    explanation: "Toner smearing/wiping off pages: in a correctly functioning laser printer, the fuser permanently bonds toner to paper using heat (~200°C) and pressure. If you can smear toner with your finger after printing, the fuser is not fusing properly. Causes: fuser temperature sensor failed (fuser running cold), fuser heating element burned out, wrong paper type (heavy cardstock may need more fusing time), or a cold printer startup printing before fuser reaches temperature. Replace the fuser assembly. Verify paper type setting in printer driver matches actual paper.",
    triggerPhrase: "Toner smears off page = fuser failure (not hot enough to bond toner); replace fuser assembly",
    weaknessTags: ["print-quality-issues", "laser-maintenance"],
  },
  {
    id: "tp-103-03", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer has vertical white streaks running down pages. What are the TWO most likely causes?",
    choices: [
      { id: "a", text: "Paper jam debris blocking a fuser roller, or incorrect paper orientation", correct: false },
      { id: "b", text: "Low or unevenly distributed toner, or a scratch/gouge on the photosensitive drum", correct: true },
      { id: "c", text: "Transfer roller applying too much voltage, or drum over-charged", correct: false },
      { id: "d", text: "Driver sending incorrect data, or firmware corruption", correct: false },
    ],
    explanation: "Vertical white streaks (parallel to paper travel direction): Toner cause: the toner cartridge is low and has an uneven distribution of toner — shake the cartridge gently side to side to redistribute toner (temporary fix), then replace. Drum cause: a scratch, gouge, or contamination on the drum surface prevents toner from adhering at that point, creating a consistent white line on every page. Drum damage is usually permanent — replace drum unit. Distinguish from horizontal lines (across the page, perpendicular to travel) which indicate drum rotation frequency damage.",
    triggerPhrase: "Vertical white streaks = low/uneven toner (shake cartridge) OR drum scratch; horizontal bands = drum rotation damage",
    weaknessTags: ["print-quality-issues"],
  },
  {
    id: "tp-103-04", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer outputs completely blank pages. The printer shows no errors. What should be checked FIRST?",
    choices: [
      { id: "a", text: "Replace the fuser assembly immediately", correct: false },
      { id: "b", text: "Check if the toner cartridge sealing tape was removed, and verify the transfer roller is working", correct: true },
      { id: "c", text: "Reinstall the printer driver on the computer", correct: false },
      { id: "d", text: "Check the paper type settings in the driver", correct: false },
    ],
    explanation: "Blank pages from a laser printer: New toner cartridge: check if the sealing/protective tape strip was pulled out before installation — the tape blocks toner from reaching the drum. No tape = check transfer roller (if transfer roller is not applying charge, toner stays on drum and never reaches paper). Also: disconnected drum (drum not making contact), or a communication issue (data not reaching the printer — check if test page from the printer's menu prints; if yes, it's a driver/software issue).",
    triggerPhrase: "Blank laser pages: check sealing tape removed from new cartridge; then transfer roller; then test page from printer menu",
    weaknessTags: ["print-quality-issues"],
  },
  {
    id: "tp-103-05", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer has repeated paper jams. The jams always occur in the same location. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The document being printed is too complex for the printer's processor", correct: false },
      { id: "b", text: "Worn pickup rollers, separation pad, or a physical obstruction (paper fragment) at the jam location", correct: true },
      { id: "c", text: "The toner cartridge is incompatible with the paper type", correct: false },
      { id: "d", text: "The driver is sending pages in the wrong orientation", correct: false },
    ],
    explanation: "Location-specific paper jams indicate a mechanical issue at that point in the paper path: Input tray jams: worn pickup rollers (can't grab paper consistently) or worn separation pad (feeds multiple sheets, which jam). Fuser area jams: worn fuser rollers can't move paper through. Output area jams: worn exit rollers. Also: check for paper fragment remnants from a previous jam — even a tiny piece of torn paper can cause repeated jams. Verify correct paper type/weight for the printer. Never pull jammed paper backward — always in the direction of paper travel.",
    triggerPhrase: "Jams always at same location = worn rollers/separation pad or paper fragment at that point; check and replace",
    weaknessTags: ["print-feed-issues"],
  },
  {
    id: "tp-103-06", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A printer feeds multiple sheets of paper at once (double-feeding), causing jams and misprints. What component is MOST likely worn?",
    choices: [
      { id: "a", text: "The fuser pressure roller", correct: false },
      { id: "b", text: "The separation pad (or separation roller)", correct: true },
      { id: "c", text: "The main board of the printer", correct: false },
      { id: "d", text: "The toner cartridge", correct: false },
    ],
    explanation: "Double-feeding (multiple sheets picked at once) is caused by a worn separation pad or separation roller. The separation pad/roller works against the pickup roller to ensure only one sheet is fed at a time — the pickup roller moves sheets forward while the separation pad applies friction to hold back the sheets beneath. When the pad is worn smooth, friction is reduced and multiple sheets slide through together. The separation pad is typically included in maintenance kits and is relatively inexpensive to replace.",
    triggerPhrase: "Double-feed (multiple sheets at once) = worn separation pad; part of maintenance kit; replace to restore single-sheet pickup",
    weaknessTags: ["print-feed-issues"],
  },
  {
    id: "tp-103-07", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "A network printer shows as offline in Windows, but the printer's display panel shows it is ready. What should be checked FIRST?",
    choices: [
      { id: "a", text: "Replace the printer's network card", correct: false },
      { id: "b", text: "Check that the Print Spooler service is running and restart it if stopped", correct: true },
      { id: "c", text: "Reinstall the printer driver with administrator privileges", correct: false },
      { id: "d", text: "Check if the printer is out of toner", correct: false },
    ],
    explanation: "Printer offline in Windows while physically ready: First check: Open Services.msc, find 'Print Spooler,' verify it is Running. If stopped, start it. The spooler manages the print queue — if it crashes, Windows shows the printer offline. Also check: right-click the printer in Settings > Printers > uncheck 'Use Printer Offline' (Windows sometimes sets this). Verify TCP/IP port settings (the IP address configured in the printer port should match the printer's current IP). Check network connectivity (ping the printer IP).",
    triggerPhrase: "Printer offline despite being ready: restart Print Spooler service; uncheck 'Use Printer Offline'; verify IP in port settings",
    weaknessTags: ["printer-connectivity"],
  },
  {
    id: "tp-103-08", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A print job is stuck in the Windows print queue and cannot be cancelled. How should a technician clear the stuck print job?",
    choices: [
      { id: "a", text: "Restart the printer and wait for the queue to clear automatically", correct: false },
      { id: "b", text: "Stop the Print Spooler service, delete files from the spool folder, then restart the Print Spooler service", correct: true },
      { id: "c", text: "Uninstall and reinstall the printer driver", correct: false },
      { id: "d", text: "Disconnect and reconnect the USB cable to reset the connection", correct: false },
    ],
    explanation: "Clearing a stuck print job: (1) Open Services.msc > Stop the Print Spooler service. (2) Navigate to C:\\Windows\\System32\\spool\\PRINTERS\\ — delete all files in this folder (these are the spool files for queued jobs). (3) Return to Services.msc > Start the Print Spooler service. The queue will be empty. Alternatively: net stop spooler > del /Q /F /S \"%systemroot%\\System32\\spool\\PRINTERS\\*.*\" > net start spooler (as administrator in command prompt). Never delete the PRINTERS folder itself, only the files inside it.",
    triggerPhrase: "Stuck print job: stop Spooler > delete C:\\Windows\\System32\\spool\\PRINTERS\\*.* > start Spooler",
    weaknessTags: ["printer-connectivity", "print-feed-issues"],
  },
  {
    id: "tp-103-09", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "An inkjet printer produces prints with incorrect or missing colors. The cyan is missing in all prints. What should be done FIRST?",
    choices: [
      { id: "a", text: "Replace the printer entirely as color inkjet printers cannot be repaired", correct: false },
      { id: "b", text: "Run a nozzle check print, then run the printhead cleaning utility for the cyan nozzles", correct: true },
      { id: "c", text: "Update the printer driver for correct color output", correct: false },
      { id: "d", text: "Change the color profile in the print dialog", correct: false },
    ],
    explanation: "Missing color in inkjet prints: Print a nozzle check pattern (available in printer utility) — it shows all color nozzles; missing rows for cyan confirm clogged/blocked cyan nozzles. Run the automatic printhead cleaning utility (this flushes ink through nozzles under pressure). May need 2-3 cleaning cycles. If cleaning doesn't restore cyan: check if the cyan cartridge is empty; reseat the cartridge; if the cartridge has the printhead built in (HP style), replace the cartridge. If printhead is separate (Epson style), the printhead may need professional cleaning or replacement.",
    triggerPhrase: "Inkjet missing color: nozzle check > cleaning utility (repeat 2-3x) > check cartridge > reseat/replace cartridge",
    weaknessTags: ["print-quality-issues", "inkjet-thermal-impact"],
  },
  {
    id: "tp-103-10", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A user can ping a network printer successfully, but printing fails. The printer shows online with no errors. What should be checked next?",
    choices: [
      { id: "a", text: "The physical network cable between the printer and the switch", correct: false },
      { id: "b", text: "The printer driver, port configuration (IP address/port number in driver), and printer spooler on the computer", correct: true },
      { id: "c", text: "The DHCP server to ensure the printer has a valid IP", correct: false },
      { id: "d", text: "The paper tray to ensure paper is loaded correctly", correct: false },
    ],
    explanation: "Can ping but cannot print: network connectivity is confirmed (ping works). Problem is in the software/driver layer: (1) Wrong port: check the printer port settings (Devices and Printers > Printer Properties > Ports tab) — IP address must match the printer's current IP; port 9100 (RAW/JetDirect) is standard. (2) Wrong or corrupt driver: uninstall and reinstall correct model driver. (3) Print spooler: verify it's running. (4) Firewall: Windows Firewall or security software may block printer traffic. (5) Try printing a test page directly from the printer's built-in web interface (EWS).",
    triggerPhrase: "Ping works but can't print: check port IP in driver settings (port 9100), reinstall driver, check spooler/firewall",
    weaknessTags: ["printer-connectivity"],
  },
  {
    id: "tp-103-11", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "A laser printer is producing prints that become progressively lighter until they are barely visible. Replacing the toner cartridge did not fix the issue. What should be investigated next?",
    choices: [
      { id: "a", text: "The drum unit is worn out and needs replacement", correct: true },
      { id: "b", text: "The fuser assembly temperature is too high", correct: false },
      { id: "c", text: "The paper type setting is incorrect", correct: false },
      { id: "d", text: "The printer driver resolution setting is too low", correct: false },
    ],
    explanation: "Progressive fading after toner replacement: if a new toner cartridge still produces faded output, the issue is not the toner supply. The photosensitive drum degrades over time — the photosensitive coating wears away, reducing its ability to hold and release toner correctly. Symptoms of a worn drum: overall light output, reduced contrast, or fogging. Drum units have a page count rating (often 12,000-25,000 pages for separate drum units). Replace the drum unit. Many low-cost printers combine toner and drum in one cartridge — in that case, a new cartridge includes a new drum.",
    triggerPhrase: "Fading despite new toner = worn drum unit; drum coating degrades over time; replace drum separately or as part of cartridge",
    weaknessTags: ["print-quality-issues", "laser-maintenance"],
  },
  {
    id: "tp-103-12", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "Paper comes out of a laser printer skewed (at an angle) or consistently misaligned on one side. What is the MOST likely cause?",
    choices: [
      { id: "a", text: "The document margins are set incorrectly in the application", correct: false },
      { id: "b", text: "Worn pickup rollers or paper not loaded squarely against the guides in the tray", correct: true },
      { id: "c", text: "The fuser is applying uneven pressure across the page width", correct: false },
      { id: "d", text: "The printer is not connected to the network properly", correct: false },
    ],
    explanation: "Paper skew (output at an angle): Load issue: paper not properly aligned against the side guides in the tray — paper should be snug against the guides (not too loose, not too tight). Ensure the stack is not too large. Roller issue: uneven wear on pickup or feed rollers causes one side to advance paper faster, skewing it. Clean rollers with a damp lint-free cloth (distilled water); replace if worn. Also check for debris in the paper path. Verify paper type matches tray settings and is within spec for the printer.",
    triggerPhrase: "Paper skew = paper not aligned in tray OR worn/uneven rollers; align guides, clean/replace rollers",
    weaknessTags: ["print-feed-issues"],
  },
  {
    id: "tp-103-13", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "What is secure print (also called PIN printing or pull printing), and what problem does it solve?",
    choices: [
      { id: "a", text: "Secure print encrypts the print job over the network; solves eavesdropping on network printers", correct: false },
      { id: "b", text: "Secure print holds the job in the printer's memory until the user authenticates at the printer, preventing sensitive documents from sitting uncollected in the output tray", correct: true },
      { id: "c", text: "Secure print limits printing to authorized users by requiring domain login on the computer; solves unauthorized printing", correct: false },
      { id: "d", text: "Secure print watermarks documents automatically; solves document tracking for compliance", correct: false },
    ],
    explanation: "Secure/PIN/hold print: the print job is sent to the printer and held in memory (not printed yet). The user walks to the printer and enters their PIN (or swipes a badge/card) to release the job. The printer then prints it immediately while the user is present. Solves: confidential documents (HR, legal, financial) left uncollected in the output tray where anyone can see them. Also reduces waste (user can cancel at printer if they change their mind). Requires a printer with sufficient memory and a PIN/badge authentication interface.",
    triggerPhrase: "Secure/PIN print = holds job until user authenticates at printer; prevents sensitive docs left in output tray",
    weaknessTags: ["printer-connectivity", "print-quality-issues"],
  },
  {
    id: "tp-103-14", domain: "5.0-troubleshooting", difficulty: "easy", type: "single", source: "drill",
    prompt: "An impact (dot-matrix) printer is powered on and receives print jobs, but produces no output at all. What is the FIRST component to check?",
    choices: [
      { id: "a", text: "Replace the printhead immediately as it has burned out", correct: false },
      { id: "b", text: "Check if the ink ribbon cartridge is installed and properly seated", correct: true },
      { id: "c", text: "Update the printer driver to the latest version", correct: false },
      { id: "d", text: "Check if the printer is set to bidirectional printing mode", correct: false },
    ],
    explanation: "Impact dot-matrix printer no output: if the printer powers on, accepts jobs, and the printhead moves across the paper but produces nothing, the ribbon is likely absent, improperly installed, or completely used up. Check: (1) Is the ribbon cartridge installed? (2) Is it seated correctly in its guides? (3) Is the ribbon depleted (appears dry, no ink remains)? Replace the ribbon cartridge. If the ribbon is fine and the printhead moves but nothing prints, individual pins may be stuck/broken — examine if the problem is complete no output vs. missing dots.",
    triggerPhrase: "Dot-matrix no output = check ribbon cartridge installed + properly seated; if ribbon is fine, check printhead pins",
    weaknessTags: ["print-quality-issues", "inkjet-thermal-impact"],
  },
  {
    id: "tp-103-15", domain: "5.0-troubleshooting", difficulty: "medium", type: "single", source: "drill",
    prompt: "Horizontal lines appear at regular, evenly-spaced intervals across laser-printed pages. What does the interval of these lines indicate?",
    choices: [
      { id: "a", text: "The print resolution is set too low in the driver", correct: false },
      { id: "b", text: "The interval corresponds to the circumference of a damaged drum or fuser roller, identifying the faulty component", correct: true },
      { id: "c", text: "The paper is feeding at irregular speed due to a motor fault", correct: false },
      { id: "d", text: "The laser is firing at an incorrect frequency", correct: false },
    ],
    explanation: "Regular horizontal lines (across the page, perpendicular to paper travel) that repeat at consistent intervals are caused by a damaged, contaminated, or defective rotating component. The interval equals the component's circumference. How to diagnose: measure the distance between repeating defects. Compare to the drum circumference and fuser roller circumference for that printer model (found in service manual). If interval = drum circumference → replace drum unit. If interval = fuser roller circumference → replace fuser. Contamination (toner buildup) on rollers also causes this pattern.",
    triggerPhrase: "Horizontal lines at regular intervals = damage on rotating component; measure interval vs drum/fuser circumference to identify which",
    weaknessTags: ["print-quality-issues", "laser-maintenance"],
  },
];
'@
$result = $trimmed + $newQuestions
[System.IO.File]::WriteAllText($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Batch E done. Total lines: $((Get-Content $file).Count)"
