$file = "C:\Users\mcgil\Downloads\aplus-study-gilly\aplus-app\data\questions\index.ts"
$content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
$insertAt = $content.LastIndexOf('];')

$newQuestions = @'

  // === External Practice Questions Set 4 ===
  {
    id: "ext4-q01",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "multi",
    source: "concept-builder",
    prompt: "The 802.11n standard was introduced as an improvement over 802.11a/b/g standards. What characteristics of the 802.11n standard show improved connectivity and performance? (Select three.)",
    choices: [
      { id: "a", text: "It can work only over the 5 GHz band.", correct: false },
      { id: "b", text: "It features the introduction of MIMO.", correct: true },
      { id: "c", text: "The nominal data rate is 64 Mbps per stream or 150 Mbps per stream for a 40 MHz bonded channel.", correct: true },
      { id: "d", text: "It can work over both 2.4 GHz and 5 GHz bands.", correct: true },
    ],
    explanation: "802.11n (Wi-Fi 4) introduced three key improvements: (1) MIMO (Multiple Input, Multiple Output) using multiple antennas to send/receive simultaneous spatial streams; (2) dual-band operation supporting both 2.4 GHz and 5 GHz; (3) channel bonding that doubles the channel width to 40 MHz, achieving up to ~150 Mbps per stream. '5 GHz only' describes 802.11a or 802.11ac, NOT 802.11n.",
    triggerPhrase: "802.11n = MIMO + dual-band (2.4 AND 5 GHz) + 40 MHz bonding",
    weaknessTags: ["wifi-80211-standards", "wifi-frequency"],
  },
  {
    id: "ext4-q02",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A remote support technician is speaking with a new rural business client who has issues with their internet connection. As the remote technician gathers information for a local technician to visit the site, the user mentions that the local tech referred to their connection as the 'local loop' and the 'last mile.' What device would the remote technician conclude that they use to connect to the internet?",
    choices: [
      { id: "a", text: "Optical network terminal", correct: false },
      { id: "b", text: "DSL modem", correct: true },
      { id: "c", text: "Wi-Fi access points", correct: false },
      { id: "d", text: "Cable modem", correct: false },
    ],
    explanation: "The 'local loop' and 'last mile' are telecommunications terms for the copper wire connection between the telephone company's central office (CO) and the customer's premises. DSL (Digital Subscriber Line) runs over this existing telephone copper wire, making 'DSL modem' the correct device. An optical network terminal (ONT) is used for fiber-optic connections. A cable modem uses coaxial cable infrastructure. Wi-Fi access points are local wireless devices, not WAN connection devices.",
    triggerPhrase: "Local loop / last mile = copper telephone wire = DSL modem",
    weaknessTags: ["internet-conn-types", "dsl-types"],
  },
  {
    id: "ext4-q03",
    domain: "1.0-mobile",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A company offers a bring your own device (BYOD) program at work. Several users approach the company in an effort to receive reimbursement for changing personal phones to the company's carrier. This will be done by swapping out a subscriber identity module (SIM) card in devices with which network type?",
    choices: [
      { id: "a", text: "LTE", correct: true },
      { id: "b", text: "HSPA", correct: false },
      { id: "c", text: "CDMA", correct: false },
      { id: "d", text: "NFC", correct: false },
    ],
    explanation: "LTE (Long-Term Evolution, 4G) is the dominant mobile network standard that uses SIM (Subscriber Identity Module) cards to identify subscribers and enable carrier switching. CDMA networks (historically Verizon, Sprint) do NOT use SIM cards - they identify devices by ESN/MEID, making carrier switching difficult. HSPA (3G) also uses SIM cards but is older technology. NFC is short-range communication, not a cellular network standard.",
    triggerPhrase: "SIM card swap for carrier change = LTE (CDMA does NOT use SIM cards)",
    weaknessTags: ["cellular-data", "short-range-wireless"],
  },
  {
    id: "ext4-q04",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "multi",
    source: "concept-builder",
    prompt: "A technician is identifying storage devices from least volatile to most volatile and must determine which require external power to retain stored data. Which of the following storage devices require power to retain their stored data? (Select two.)",
    choices: [
      { id: "a", text: "mSATA SSD", correct: false },
      { id: "b", text: "2.5\" HDD", correct: false },
      { id: "c", text: "USB stick", correct: false },
      { id: "d", text: "CPU cache", correct: true },
      { id: "e", text: "RAM", correct: true },
    ],
    explanation: "Volatile storage loses data when power is removed. CPU cache (SRAM) and RAM (DRAM) are volatile - they require continuous power to retain data, making them the most volatile. mSATA SSDs, HDDs, and USB flash drives are non-volatile (persistent storage) - they retain data without power. From least to most volatile: mSATA SSD and HDD (equally persistent), then USB stick, then CPU cache, then RAM.",
    triggerPhrase: "Volatile (needs power) = CPU Cache + RAM; Non-volatile = SSD, HDD, USB flash",
    weaknessTags: ["cache-hierarchy", "memory-types"],
  },
  {
    id: "ext4-q05",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What would cause a central processing unit (CPU) to make only minor changes to the CPU internals that significantly improve performance and increase speed?",
    choices: [
      { id: "a", text: "Multicore", correct: false },
      { id: "b", text: "Multithreading", correct: true },
      { id: "c", text: "Multisocket", correct: false },
      { id: "d", text: "Single core", correct: false },
    ],
    explanation: "Multithreading (Intel's Hyper-Threading / AMD's SMT) allows a single physical core to present two logical cores to the OS by duplicating certain internal pipeline registers. This is a minor architectural change that significantly boosts throughput for multi-threaded workloads. Multicore requires physically adding more cores, which is a more significant design change. Multisocket requires a different motherboard with multiple CPU slots. Single core is a limitation, not an improvement.",
    triggerPhrase: "Minor CPU change, big performance gain = Multithreading (Hyper-Threading/SMT)",
    weaknessTags: ["cache-hierarchy", "motherboard-id"],
  },
  {
    id: "ext4-q06",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "multi",
    source: "concept-builder",
    prompt: "What characteristics of Wi-Fi 5 (802.11ac) allow for increased bandwidth and support for modern networks? (Select three.)",
    choices: [
      { id: "a", text: "Designed to work in both the 2.4 GHz and 5 GHz bands", correct: false },
      { id: "b", text: "Designed to work only in the 5 GHz band", correct: true },
      { id: "c", text: "Typically supports up to four simultaneous clients", correct: true },
      { id: "d", text: "Downlink MU-MIMO", correct: true },
    ],
    explanation: "802.11ac (Wi-Fi 5) key characteristics: (1) operates ONLY in the 5 GHz band (not 2.4 GHz - dual-band routers use 802.11n for the 2.4 GHz radio); (2) introduced Downlink MU-MIMO (Multi-User MIMO), allowing the AP to simultaneously transmit to multiple clients on the downlink; (3) supports up to four simultaneous MU-MIMO clients. Routers advertised as 'dual-band AC' combine 802.11n (2.4 GHz) + 802.11ac (5 GHz) - 802.11ac itself is 5 GHz only.",
    triggerPhrase: "802.11ac (Wi-Fi 5) = 5 GHz ONLY + Downlink MU-MIMO + up to 4 simultaneous clients",
    weaknessTags: ["wifi-80211-standards", "wifi-frequency"],
  },
  {
    id: "ext4-q07",
    domain: "5.0-troubleshooting",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A printer allows connection to a network through the infrastructure mode. Which of the following connections is the printer most likely using when referring to an infrastructure mode connection?",
    choices: [
      { id: "a", text: "Duplex unit", correct: false },
      { id: "b", text: "Ethernet", correct: false },
      { id: "c", text: "Wireless", correct: true },
      { id: "d", text: "USB", correct: false },
    ],
    explanation: "Infrastructure mode is a Wi-Fi networking configuration where wireless clients (including printers) connect through a central wireless access point (WAP/AP), which routes traffic to the network. This is in contrast to ad-hoc (peer-to-peer) wireless mode. A printer using 'infrastructure mode' is connecting wirelessly through an AP. Ethernet, USB, and duplex are not associated with infrastructure mode - duplex refers to the printer's two-sided printing unit.",
    triggerPhrase: "Infrastructure mode = wireless (Wi-Fi through an AP, not direct/ad-hoc)",
    weaknessTags: ["printer-connectivity", "printer-sharing"],
  },
  {
    id: "ext4-q08",
    domain: "4.0-virtualization-cloud",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A cloud service provider (CSP) works with several organizations to establish new cloud deployments that best match their needs. Each organization has similar security needs and is open to sharing resources with other organizations to save money. Which cloud deployment model sounds best for the CSP's new customers?",
    choices: [
      { id: "a", text: "Hybrid cloud", correct: false },
      { id: "b", text: "Public cloud", correct: false },
      { id: "c", text: "Community cloud", correct: true },
      { id: "d", text: "Private cloud", correct: false },
    ],
    explanation: "A community cloud is shared infrastructure used by several organizations with common concerns such as security requirements, compliance obligations, or mission. The organizations share costs while maintaining more control than a fully public cloud. Hybrid cloud combines private and public cloud. Public cloud is open to any customer. Private cloud is dedicated to a single organization. The key indicator here is 'similar security needs' + 'sharing resources' across multiple organizations.",
    triggerPhrase: "Multiple orgs + similar security needs + sharing = Community cloud",
    weaknessTags: ["multitenancy"],
  },
  {
    id: "ext4-q09",
    domain: "5.0-troubleshooting",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "What does the Microsoft Windows 'Programs and Features' applet allow the user to manage?",
    choices: [
      { id: "a", text: "Security requirements", correct: false },
      { id: "b", text: "Test development", correct: false },
      { id: "c", text: "Resource requirements", correct: false },
      { id: "d", text: "Legacy software/OS", correct: true },
    ],
    explanation: "The Programs and Features Control Panel applet allows users to view, uninstall, change, or repair installed software on a Windows system. This is particularly useful for managing older and legacy applications that may not appear in the modern Settings > Apps interface. From it you can also turn Windows features on/off. Security requirements are managed via Security Center/Windows Defender. Resource requirements are system specifications, not managed here.",
    triggerPhrase: "Programs and Features = manage installed software including legacy applications",
    weaknessTags: ["boot-sequence"],
  },
  {
    id: "ext4-q10",
    domain: "5.0-troubleshooting",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "A student borrows an external hard drive from a friend but cannot see the drive in Windows Explorer. The friend's computer is a Mac. What is the problem?",
    choices: [
      { id: "a", text: "Incompatible file structures", correct: true },
      { id: "b", text: "Faulty boot sector", correct: false },
      { id: "c", text: "Bad sectors", correct: false },
      { id: "d", text: "Faulty connectors", correct: false },
    ],
    explanation: "A Mac typically formats drives using HFS+ (Mac OS Extended) or APFS, which Windows cannot read natively. When plugged into a Windows PC, the drive may appear in Disk Management as an unrecognized volume but will not show in File Explorer (Windows Explorer). The solution is to reformat the drive as exFAT or FAT32 (cross-platform) or NTFS (Windows), or use third-party software to read Mac formats. Bad sectors/faulty boot sector/faulty connectors would affect the drive on any OS.",
    triggerPhrase: "Mac drive invisible in Windows = incompatible file system (HFS+/APFS vs NTFS)",
    weaknessTags: ["drive-health", "sata-interface"],
  },
  {
    id: "ext4-q11",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A technician uses an adapter card that supplies power over the bus, resulting in no need for a separate power cable. Because this adapter can vary in different widths and lengths, the technician should check to ensure that the adapter fits on the motherboard. What type of adapter has these specifications?",
    choices: [
      { id: "a", text: "SSD", correct: false },
      { id: "b", text: "M.2", correct: true },
      { id: "c", text: "mSATA", correct: false },
      { id: "d", text: "HDD", correct: false },
    ],
    explanation: "M.2 modules are identified by a form factor code that encodes both width and length (e.g., 2230 = 22mm wide x 30mm long, 2242, 2260, 2280, 22110). They draw power directly from the M.2 slot with no separate power cable. Because motherboards support specific M.2 lengths, technicians must verify compatibility. mSATA also draws bus power, but it varies mainly in length (standard vs. half-size), not in multiple widths. HDDs require a separate SATA power connector. SSD is a broad category, not a form factor.",
    triggerPhrase: "Bus-powered + varies in width AND length = M.2 (form factor code = width x length)",
    weaknessTags: ["m2-slots", "sata-interface"],
  },
'@

$newContent = $content.Substring(0, $insertAt) + $newQuestions + "`n];"
[System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Ext4 done. Total lines: $($newContent.Split("`n").Length)"
