// scripts/append-ext6.js
// Appends 40 image-quiz questions (ext6-q01..q40) to data/questions/index.ts
// Topics: Connectors (q01-10), Display Types (q11-20), Cable Categories (q21-30), T568A/B (q31-40)

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'data', 'questions', 'index.ts');
const content = fs.readFileSync(filePath, 'utf8');

const insertAt = content.lastIndexOf('];');
if (insertAt === -1) {
  console.error('Could not find ]; in index.ts');
  process.exit(1);
}

const newQuestions = `
  // ── EXT6: Image Quiz Questions ── Connectors / Displays / Cable Categories / T568A-B ──

  // ── CONNECTORS (q01-q10) ── image: /diagrams/11_connector_types.svg ──
  {
    id: "ext6-q01",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which connector has 8 positions and 8 contacts (8P8C) and is used to terminate Ethernet cables?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "RJ45", correct: true },
      { id: "b", text: "RJ11", correct: false },
      { id: "c", text: "BNC", correct: false },
      { id: "d", text: "F-type", correct: false },
    ],
    explanation: "RJ45 (8P8C) is the standard 8-contact connector used for Ethernet (Cat 5/5e/6/6A). RJ11 has 6 positions and 4 active contacts and is used for telephone connections. BNC uses a bayonet twist-lock for coaxial cable, and F-type uses a threaded barrel for cable TV.",
    triggerPhrase: "8P8C Ethernet connector",
    weaknessTags: ["ports", "wiring-standards"],
  },
  {
    id: "ext6-q02",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which telephone connector has 6 positions and 4 active contacts (6P4C) and is noticeably smaller than an Ethernet connector?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "RJ11", correct: true },
      { id: "b", text: "RJ45", correct: false },
      { id: "c", text: "LC", correct: false },
      { id: "d", text: "BNC", correct: false },
    ],
    explanation: "RJ11 (6P4C) is the smaller telephone connector with 6 positions and 4 active contacts. It is used for telephone lines and modems. RJ45 is the larger Ethernet connector with 8 contacts. LC and BNC are entirely different connector families.",
    triggerPhrase: "6P4C telephone connector",
    weaknessTags: ["ports"],
  },
  {
    id: "ext6-q03",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which coaxial connector uses a threaded barrel and is found on cable TV wall outlets and set-top boxes?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "F-type", correct: true },
      { id: "b", text: "BNC", correct: false },
      { id: "c", text: "RJ11", correct: false },
      { id: "d", text: "ST", correct: false },
    ],
    explanation: "F-type connectors use a threaded barrel to secure the coaxial cable and are the standard for cable TV (DOCSIS), satellite, and CATV wall plates. BNC also connects coaxial cable but uses a bayonet quarter-turn twist-lock instead of threads. ST is a fiber optic connector.",
    triggerPhrase: "threaded barrel coaxial cable TV",
    weaknessTags: ["coax-cabling", "ports"],
  },
  {
    id: "ext6-q04",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which coaxial connector uses a bayonet quarter-turn twist-lock and was used in 10BASE-2 (ThinNet) legacy Ethernet networks?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "BNC", correct: true },
      { id: "b", text: "F-type", correct: false },
      { id: "c", text: "ST", correct: false },
      { id: "d", text: "LC", correct: false },
    ],
    explanation: "BNC (Bayonet Neill-Concelman) connectors use a quarter-turn bayonet twist-lock mechanism to secure coaxial cable. They were the standard connector for 10BASE-2 ThinNet Ethernet. F-type uses a threaded barrel and is for cable TV. ST and LC are fiber optic connectors.",
    triggerPhrase: "BNC bayonet twist-lock 10BASE-2",
    weaknessTags: ["coax-cabling", "ports"],
  },
  {
    id: "ext6-q05",
    domain: "1.0-mobile",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which USB connector is fully reversible (works either way up) and supports USB 3.1, USB4, and Thunderbolt 3/4?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "USB-C", correct: true },
      { id: "b", text: "USB-A", correct: false },
      { id: "c", text: "USB-B", correct: false },
      { id: "d", text: "Micro-USB", correct: false },
    ],
    explanation: "USB-C has a small oval shape and is fully reversible -- you can plug it in either orientation. It supports USB 3.1, USB 3.2, USB4, and Thunderbolt 3/4 over the same port. USB-A (flat rectangular), USB-B (square), and Micro-USB are all orientation-specific and do not support Thunderbolt.",
    triggerPhrase: "USB-C reversible Thunderbolt",
    weaknessTags: ["usb-standards", "thunderbolt"],
  },
  {
    id: "ext6-q06",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which display connector has a 19-pin trapezoidal shape and carries both audio and video signals to televisions and monitors?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "HDMI", correct: true },
      { id: "b", text: "VGA", correct: false },
      { id: "c", text: "DVI", correct: false },
      { id: "d", text: "DisplayPort", correct: false },
    ],
    explanation: "HDMI (High-Definition Multimedia Interface) uses a 19-pin trapezoidal connector and transmits both audio and video digitally. VGA uses a 15-pin D-sub and carries only analog video. DVI carries digital video (no audio). DisplayPort has a notched corner and supports daisy-chaining.",
    triggerPhrase: "HDMI 19-pin trapezoid audio video",
    weaknessTags: ["display-cables"],
  },
  {
    id: "ext6-q07",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which display connector has a distinctive notched corner on one side, supports daisy-chaining multiple monitors, and uses a latch clip to secure the connection?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "DisplayPort", correct: true },
      { id: "b", text: "HDMI", correct: false },
      { id: "c", text: "VGA", correct: false },
      { id: "d", text: "DVI", correct: false },
    ],
    explanation: "DisplayPort has a rectangular shape with one notched corner, making it physically asymmetric and easy to identify. It supports daisy-chaining multiple monitors through Multi-Stream Transport (MST) and uses a latch clip. HDMI is trapezoidal. VGA is a D-sub with thumbscrews. DVI is a large rectangular connector.",
    triggerPhrase: "DisplayPort notched corner daisy-chain",
    weaknessTags: ["display-cables"],
  },
  {
    id: "ext6-q08",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which 15-pin D-sub connector carries ONLY analog video (no audio) and is secured using thumbscrews on both sides?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "VGA", correct: true },
      { id: "b", text: "DVI-D", correct: false },
      { id: "c", text: "HDMI", correct: false },
      { id: "d", text: "DisplayPort", correct: false },
    ],
    explanation: "VGA (Video Graphics Array) uses a 15-pin D-subminiature (DB-15) connector arranged in three rows. It transmits only analog video -- no audio. The connector is secured with thumbscrews on each side. DVI-D carries digital video. HDMI and DisplayPort carry digital audio and video without thumbscrews.",
    triggerPhrase: "VGA 15-pin D-sub analog video only",
    weaknessTags: ["display-cables", "display-tech"],
  },
  {
    id: "ext6-q09",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which fiber optic connector is half the size of an SC, uses an RJ-style clip latch, and is the most popular connector in modern data centers?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "LC", correct: true },
      { id: "b", text: "ST", correct: false },
      { id: "c", text: "SC", correct: false },
      { id: "d", text: "FC", correct: false },
    ],
    explanation: "LC (Lucent Connector) is a small form-factor fiber connector that is half the size of an SC. It uses a retaining clip similar to an RJ45/RJ11 latch. Its small size allows higher port density, making it the most common fiber connector in data centers. ST uses a bayonet twist-lock. SC is a large square push-pull connector. FC uses a threaded barrel.",
    triggerPhrase: "LC fiber connector data center",
    weaknessTags: ["fiber-connectors"],
  },
  {
    id: "ext6-q10",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A fiber patch panel uses large square-bodied push-pull connectors. What connector type is this?",
    image: "/diagrams/11_connector_types.svg",
    imageAlt: "Common connector types visual identification chart",
    choices: [
      { id: "a", text: "SC", correct: true },
      { id: "b", text: "ST", correct: false },
      { id: "c", text: "LC", correct: false },
      { id: "d", text: "FC", correct: false },
    ],
    explanation: "SC (Subscriber Connector) has a large square body and uses a simple push-pull mechanism to insert and remove. It does not rotate or clip -- you just push to connect and pull to disconnect. ST uses a bayonet twist-lock. LC is a small form-factor clip connector. FC uses a threaded barrel.",
    triggerPhrase: "SC fiber square push-pull connector",
    weaknessTags: ["fiber-connectors"],
  },

  // ── DISPLAY TYPES (q11-q20) ── image: /diagrams/09_display_types.svg ──
  {
    id: "ext6-q11",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which display technology uses organic compounds that emit their own light and therefore requires NO backlight?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "OLED", correct: true },
      { id: "b", text: "TN LCD", correct: false },
      { id: "c", text: "IPS LCD", correct: false },
      { id: "d", text: "VA LCD", correct: false },
    ],
    explanation: "OLED (Organic Light-Emitting Diode) pixels produce their own light using organic compounds, eliminating the need for a separate backlight. TN, IPS, and VA are all LCD technologies that require a backlight shining through liquid crystal layers to produce an image.",
    triggerPhrase: "OLED self-emitting no backlight",
    weaknessTags: ["display-tech", "laptop-display"],
  },
  {
    id: "ext6-q12",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which LCD panel type is the original/oldest LCD technology, known for having the fastest response times, making it ideal for gaming?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "TN (Twisted Nematic)", correct: true },
      { id: "b", text: "IPS", correct: false },
      { id: "c", text: "VA", correct: false },
      { id: "d", text: "OLED", correct: false },
    ],
    explanation: "TN (Twisted Nematic) is the original LCD panel technology. Its primary advantage is the fastest pixel response time among LCD types, which reduces motion blur in fast-paced games. Its drawbacks include poor viewing angles and color shifting when viewed off-axis. It is also typically the least expensive LCD option.",
    triggerPhrase: "TN fastest response gaming LCD",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q13",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which LCD technology offers excellent color accuracy and wide viewing angles but costs more to produce than TN panels?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "IPS (In-Plane Switching)", correct: true },
      { id: "b", text: "TN", correct: false },
      { id: "c", text: "VA", correct: false },
      { id: "d", text: "OLED", correct: false },
    ],
    explanation: "IPS (In-Plane Switching) LCD panels align their liquid crystals horizontally, providing excellent color reproduction and consistent color when viewed from wide angles. The trade-off is higher manufacturing cost compared to TN panels. IPS is commonly used in professional monitors, photo editing displays, and high-quality laptop screens.",
    triggerPhrase: "IPS wide viewing angles color accuracy",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q14",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which LCD panel type is described as a compromise between TN and IPS -- offering good color and contrast but slower response than TN?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "VA (Vertical Alignment)", correct: true },
      { id: "b", text: "TN", correct: false },
      { id: "c", text: "IPS", correct: false },
      { id: "d", text: "OLED", correct: false },
    ],
    explanation: "VA (Vertical Alignment) panels align liquid crystals vertically when unpowered, producing good contrast ratios. They offer better color than TN and better contrast than IPS, but their response times are typically slower than TN panels. VA sits between TN and IPS in the cost-vs-quality spectrum.",
    triggerPhrase: "VA compromise between TN IPS",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q15",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A user reports that colors shift and the image looks washed out when viewing their monitor from a slight angle. Which LCD panel type most likely causes this?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "TN", correct: true },
      { id: "b", text: "IPS", correct: false },
      { id: "c", text: "VA", correct: false },
      { id: "d", text: "OLED", correct: false },
    ],
    explanation: "TN (Twisted Nematic) panels are notorious for poor off-axis viewing angles. Colors shift and the image appears washed out or inverted when viewed from an angle. IPS panels maintain consistent color from wide viewing angles, making them preferred for shared-screen environments. VA and OLED also handle viewing angles better than TN.",
    triggerPhrase: "color shift off-axis viewing TN",
    weaknessTags: ["display-tech", "laptop-display"],
  },
  {
    id: "ext6-q16",
    domain: "1.0-mobile",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which display technology enables flexible, glass-free screens found in smartphones, tablets, and smart watches?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "OLED", correct: true },
      { id: "b", text: "TN", correct: false },
      { id: "c", text: "IPS", correct: false },
      { id: "d", text: "VA", correct: false },
    ],
    explanation: "OLED technology can be manufactured on flexible substrates, enabling bendable and rollable displays. Because OLED does not require a rigid glass backlight assembly (since each pixel self-emits), the display can be made very thin and flexible. TN, IPS, and VA all require a backlight and rigid panel construction.",
    triggerPhrase: "OLED flexible phone tablet watch",
    weaknessTags: ["display-tech", "laptop-display"],
  },
  {
    id: "ext6-q17",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What is the primary advantage of TN LCD panels compared to IPS and VA?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "Fastest response time (lowest motion blur)", correct: true },
      { id: "b", text: "Better color accuracy", correct: false },
      { id: "c", text: "Wider viewing angles", correct: false },
      { id: "d", text: "No backlight required", correct: false },
    ],
    explanation: "The primary advantage of TN panels is their very fast pixel response time, which reduces ghosting and motion blur. This makes TN panels popular for competitive gaming. IPS has better color accuracy and wider viewing angles. VA has better contrast. OLED is the only technology that requires no backlight (each pixel self-emits).",
    triggerPhrase: "TN advantage fastest response time",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q18",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which display type achieves true black pixels because individual pixels can be completely turned off?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "OLED", correct: true },
      { id: "b", text: "TN", correct: false },
      { id: "c", text: "IPS", correct: false },
      { id: "d", text: "VA", correct: false },
    ],
    explanation: "OLED pixels are individually controlled and can be completely turned off to produce true black -- no backlight leaks through. LCD technologies (TN, IPS, VA) all use a backlight that shines constantly; black pixels are created by blocking light with the liquid crystal layer, which never achieves perfect black (some backlight bleeds through).",
    triggerPhrase: "OLED true black pixels off",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q19",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "An IPS LCD costs more to produce than which other LCD panel technology?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "TN", correct: true },
      { id: "b", text: "VA", correct: false },
      { id: "c", text: "OLED", correct: false },
      { id: "d", text: "Mini-LED LCD", correct: false },
    ],
    explanation: "IPS panels cost more to produce than TN panels. TN is the oldest and simplest LCD technology and remains the least expensive to manufacture. IPS requires more complex liquid crystal alignment. VA falls in between. OLED is generally more expensive than all LCD types.",
    triggerPhrase: "IPS more expensive than TN",
    weaknessTags: ["display-tech"],
  },
  {
    id: "ext6-q20",
    domain: "3.0-hardware",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which LCD panel type stands for 'Vertical Alignment' and offers a middle-ground option between TN and IPS performance?",
    image: "/diagrams/09_display_types.svg",
    imageAlt: "Display panel technology comparison: TN, IPS, VA, OLED",
    choices: [
      { id: "a", text: "VA", correct: true },
      { id: "b", text: "TN", correct: false },
      { id: "c", text: "IPS", correct: false },
      { id: "d", text: "OLED", correct: false },
    ],
    explanation: "VA stands for Vertical Alignment. VA panels vertically align liquid crystals in their natural state, allowing better light blocking (higher contrast ratio) than TN or IPS. They are considered a middle-ground between TN (fastest, worst angles) and IPS (best color, best angles) in terms of overall performance and cost.",
    triggerPhrase: "VA Vertical Alignment middle-ground",
    weaknessTags: ["display-tech"],
  },

  // ── CABLE CATEGORIES (q21-q30) ── image: /diagrams/10_cable_categories.svg ──
  {
    id: "ext6-q21",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What Ethernet standard do both Category 5 and Category 5e support at their maximum distance of 100 meters?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "1000BASE-T (Gigabit Ethernet)", correct: true },
      { id: "b", text: "10BASE-T", correct: false },
      { id: "c", text: "100BASE-TX (Fast Ethernet)", correct: false },
      { id: "d", text: "10GBASE-T", correct: false },
    ],
    explanation: "Both Cat 5 and Cat 5e support 1000BASE-T (Gigabit Ethernet) at up to 100 meters. Cat 5e is 'enhanced' over Cat 5 primarily through reduced near-end crosstalk (NEXT), improving reliability at Gigabit speeds. Neither supports 10GBASE-T.",
    triggerPhrase: "Cat 5 Cat 5e 1000BASE-T",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q22",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which cable category supports 10GBASE-T at a full 100 meters WITHOUT requiring shielding?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Category 6A (Augmented)", correct: true },
      { id: "b", text: "Category 5e", correct: false },
      { id: "c", text: "Category 6", correct: false },
      { id: "d", text: "Category 7", correct: false },
    ],
    explanation: "Category 6A (Augmented) supports 10GBASE-T at up to 100 meters without requiring shielding. Cat 6 unshielded is limited to 55 meters for 10GbE. Cat 5e does not support 10GBASE-T. Category 7 is not an IEEE standard and uses proprietary connectors.",
    triggerPhrase: "Cat 6A 10GBASE-T 100 meters unshielded",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q23",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What is the maximum distance for an UNSHIELDED Category 6 cable when running 10GBASE-T?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "55 meters", correct: true },
      { id: "b", text: "100 meters", correct: false },
      { id: "c", text: "75 meters", correct: false },
      { id: "d", text: "10 meters", correct: false },
    ],
    explanation: "Unshielded Category 6 cable is limited to 55 meters for 10GBASE-T due to alien crosstalk at 10 Gbps frequencies. Shielded Cat 6 achieves 100 meters. Cat 6A (augmented) achieves 100 meters even without shielding. 100 meters is only achieved with Cat 6 if the cable is shielded (STP/FTP).",
    triggerPhrase: "unshielded Cat 6 55 meters 10GbE",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q24",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "What does the 'A' stand for in Category 6A cable?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Augmented", correct: true },
      { id: "b", text: "Advanced", correct: false },
      { id: "c", text: "Amplified", correct: false },
      { id: "d", text: "Asymmetric", correct: false },
    ],
    explanation: "The 'A' in Category 6A stands for Augmented. Cat 6A is an augmented version of Cat 6, designed to support 10GBASE-T over the full 100-meter distance. It achieves this through tighter specifications for alien crosstalk and reduced interference compared to standard Cat 6.",
    triggerPhrase: "6A augmented category cable",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q25",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A building needs to run 10GbE with cable runs up to 100 meters. What is the MINIMUM cable category that meets this requirement WITHOUT shielding?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Category 6A", correct: true },
      { id: "b", text: "Category 5e", correct: false },
      { id: "c", text: "Category 6", correct: false },
      { id: "d", text: "Category 7", correct: false },
    ],
    explanation: "Category 6A is the minimum cable category that supports 10GBASE-T over 100 meters without shielding. Cat 5e does not support 10GbE at all. Cat 6 unshielded is limited to 55 meters for 10GbE. Cat 7 exceeds the requirement but uses non-standard connectors and is generally not recommended for structured cabling.",
    triggerPhrase: "minimum category 10GbE 100 meters no shielding",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q26",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Category 5 cable supports which maximum Ethernet speed at 100 meters?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "1 Gbps (1000BASE-T)", correct: true },
      { id: "b", text: "10 Mbps (10BASE-T)", correct: false },
      { id: "c", text: "100 Mbps (100BASE-TX)", correct: false },
      { id: "d", text: "10 Gbps (10GBASE-T)", correct: false },
    ],
    explanation: "Category 5 cable supports 1000BASE-T (Gigabit Ethernet) at up to 100 meters. While Cat 5 is technically rated for 1 Gbps, it is more susceptible to crosstalk than Cat 5e. Cat 5e (enhanced) reduces near-end crosstalk for more reliable Gigabit operation. Neither Cat 5 nor Cat 5e supports 10GBASE-T.",
    triggerPhrase: "Cat 5 maximum speed 1000BASE-T",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q27",
    domain: "2.0-networking",
    difficulty: "hard",
    type: "single",
    source: "concept-builder",
    prompt: "An 80-meter Cat 6 run is needed for 10GBASE-T. What is required to make this work?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Use shielded Cat 6 (STP/FTP)", correct: true },
      { id: "b", text: "Use unshielded Cat 6 -- 80m is under the 100m limit", correct: false },
      { id: "c", text: "Cat 6 cannot support 10GBASE-T at any distance", correct: false },
      { id: "d", text: "Use Cat 5e -- it supports longer distances", correct: false },
    ],
    explanation: "Unshielded Cat 6 is limited to 55 meters for 10GBASE-T. At 80 meters you must use shielded Cat 6 (STP or FTP) to achieve 100 meters. Shielding reduces alien crosstalk at 10 Gbps frequencies. Cat 5e does not support 10GBASE-T at any distance. Cat 6A would also work and eliminates the shielding requirement.",
    triggerPhrase: "Cat 6 shielded 10GbE over 55 meters",
    weaknessTags: ["cat-ratings", "emi-shielding"],
  },
  {
    id: "ext6-q28",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Category 5e is 'enhanced' over Category 5. What does this enhancement primarily improve?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Reduced near-end crosstalk (NEXT) for more reliable Gigabit", correct: true },
      { id: "b", text: "Supports 10GBASE-T where Cat 5 cannot", correct: false },
      { id: "c", text: "Supports longer maximum distances than Cat 5", correct: false },
      { id: "d", text: "Supports fiber optic transmission", correct: false },
    ],
    explanation: "The 'enhanced' in Cat 5e refers primarily to improved near-end crosstalk (NEXT) specifications. This makes Cat 5e more reliable for Gigabit Ethernet (1000BASE-T) than Cat 5, though both support 1 Gbps at 100 meters. Neither Cat 5 nor Cat 5e supports 10GBASE-T, and both share the same 100-meter maximum distance.",
    triggerPhrase: "Cat 5e enhanced crosstalk NEXT",
    weaknessTags: ["cat-ratings", "crosstalk"],
  },
  {
    id: "ext6-q29",
    domain: "2.0-networking",
    difficulty: "easy",
    type: "single",
    source: "concept-builder",
    prompt: "Which two cable categories both support 1000BASE-T (Gigabit Ethernet) at 100 meters?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "Category 5 and Category 5e", correct: true },
      { id: "b", text: "Category 6 and Category 6A", correct: false },
      { id: "c", text: "Category 5e and Category 6", correct: false },
      { id: "d", text: "Category 5 and Category 6", correct: false },
    ],
    explanation: "Both Category 5 and Category 5e support 1000BASE-T at 100 meters. Category 6 and 6A also support 1000BASE-T, but they are specified for 10GBASE-T in the exam objectives. The key distinction on the A+ exam is: Cat 5/5e = 1 GbE standard, Cat 6/6A = 10 GbE standard.",
    triggerPhrase: "Cat 5 5e both support 1000BASE-T",
    weaknessTags: ["cat-ratings"],
  },
  {
    id: "ext6-q30",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What is the maximum distance for a SHIELDED Category 6 cable when running 10GBASE-T?",
    image: "/diagrams/10_cable_categories.svg",
    imageAlt: "Copper cable categories and maximum distances table",
    choices: [
      { id: "a", text: "100 meters", correct: true },
      { id: "b", text: "55 meters", correct: false },
      { id: "c", text: "75 meters", correct: false },
      { id: "d", text: "150 meters", correct: false },
    ],
    explanation: "Shielded Category 6 (STP or FTP) achieves the full 100-meter run for 10GBASE-T because shielding reduces alien crosstalk at 10 Gbps frequencies. Unshielded Cat 6 is limited to 55 meters for 10GbE. Adding shielding essentially bridges the gap between unshielded Cat 6 and Cat 6A for 10GbE deployments.",
    triggerPhrase: "shielded Cat 6 100 meters 10GbE",
    weaknessTags: ["cat-ratings", "emi-shielding"],
  },

  // ── T568A / T568B WIRING (q31-q40) ── image: /diagrams/07_wiring_standards.svg ──
  {
    id: "ext6-q31",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 1 on a T568B wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "White/Orange", correct: true },
      { id: "b", text: "White/Green", correct: false },
      { id: "c", text: "Orange", correct: false },
      { id: "d", text: "Green", correct: false },
    ],
    explanation: "In T568B wiring: Pin 1 = White/Orange, Pin 2 = Orange, Pin 3 = White/Green, Pin 4 = Blue, Pin 5 = White/Blue, Pin 6 = Green, Pin 7 = White/Brown, Pin 8 = Brown. Pin 1 in T568A is White/Green. The orange pair occupies pins 1 and 2 in T568B but pins 3 and 6 in T568A.",
    triggerPhrase: "T568B pin 1 color",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q32",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 1 on a T568A wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "White/Green", correct: true },
      { id: "b", text: "White/Orange", correct: false },
      { id: "c", text: "Orange", correct: false },
      { id: "d", text: "Green", correct: false },
    ],
    explanation: "In T568A wiring: Pin 1 = White/Green, Pin 2 = Green, Pin 3 = White/Orange, Pin 4 = Blue, Pin 5 = White/Blue, Pin 6 = Orange, Pin 7 = White/Brown, Pin 8 = Brown. In T568B, pin 1 is White/Orange. The green pair is on pins 1 and 2 in T568A but on pins 3 and 6 in T568B.",
    triggerPhrase: "T568A pin 1 color white green",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q33",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 2 on a T568A wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Green", correct: true },
      { id: "b", text: "White/Green", correct: false },
      { id: "c", text: "Orange", correct: false },
      { id: "d", text: "White/Orange", correct: false },
    ],
    explanation: "In T568A: Pin 1 = White/Green, Pin 2 = Green. The green pair occupies pins 1 (White/Green) and 2 (Green) in T568A. In T568B, pin 2 is Orange -- this is one of the key differences between the two standards. The stripe/solid pattern always follows: pin 1 is the striped wire, pin 2 is the solid wire of the same pair.",
    triggerPhrase: "T568A pin 2 Green",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q34",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 6 on a T568B wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Green", correct: true },
      { id: "b", text: "Orange", correct: false },
      { id: "c", text: "White/Orange", correct: false },
      { id: "d", text: "White/Green", correct: false },
    ],
    explanation: "In T568B: Pin 6 = Green (solid). The green pair is split across pins 3 (White/Green) and 6 (Green) in T568B -- this is the same position as in T568A. Note that the green pair location (pins 3 and 6) is the same in BOTH standards; what differs is the orange pair position (pins 1/2 in T568B vs pins 3/6 for T568A's orange).",
    triggerPhrase: "T568B pin 6 Green",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q35",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 3 on a T568B wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "White/Green", correct: true },
      { id: "b", text: "White/Orange", correct: false },
      { id: "c", text: "Orange", correct: false },
      { id: "d", text: "Green", correct: false },
    ],
    explanation: "In T568B: Pin 3 = White/Green. The green pair occupies pins 3 and 6 in T568B. In T568A, pin 3 is White/Orange. Pins 3 and 6 are the critical 'swapped' positions between T568A and T568B, along with pins 1 and 2. The blue pair (pins 4 and 5) and brown pair (pins 7 and 8) are identical in both standards.",
    triggerPhrase: "T568B pin 3 White Green",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q36",
    domain: "2.0-networking",
    difficulty: "hard",
    type: "single",
    source: "concept-builder",
    prompt: "Which pin positions DIFFER between T568A and T568B wiring standards?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Pins 1, 2, 3, and 6", correct: true },
      { id: "b", text: "Pins 1, 3, 5, and 7", correct: false },
      { id: "c", text: "Pins 2, 4, 6, and 8", correct: false },
      { id: "d", text: "Pins 4, 5, 7, and 8", correct: false },
    ],
    explanation: "Only pins 1, 2, 3, and 6 differ between T568A and T568B. Specifically: In T568A, pins 1/2 = White/Green and Green; pins 3/6 = White/Orange and Orange. In T568B, pins 1/2 = White/Orange and Orange; pins 3/6 = White/Green and Green. The orange and green pairs are essentially swapped. Pins 4/5 (blue pair) and pins 7/8 (brown pair) are identical in both standards.",
    triggerPhrase: "T568A 568B difference pins 1 2 3 6",
    weaknessTags: ["t568a-568b-crossover"],
  },
  {
    id: "ext6-q37",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "A patch cable has T568A wiring on one end and T568B wiring on the other end. What type of cable is this?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Crossover cable", correct: true },
      { id: "b", text: "Straight-through cable", correct: false },
      { id: "c", text: "Rollover/console cable", correct: false },
      { id: "d", text: "Loopback cable", correct: false },
    ],
    explanation: "A crossover cable has T568A on one end and T568B on the other end. This causes transmit pins on one device to connect to receive pins on the other device, allowing two similar devices (PC-to-PC, switch-to-switch) to communicate directly without a hub or switch. A straight-through cable uses the same standard (both T568A or both T568B) on both ends.",
    triggerPhrase: "crossover cable T568A one end T568B other",
    weaknessTags: ["t568a-568b-crossover"],
  },
  {
    id: "ext6-q38",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 6 on a T568A wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Orange", correct: true },
      { id: "b", text: "Green", correct: false },
      { id: "c", text: "White/Green", correct: false },
      { id: "d", text: "White/Orange", correct: false },
    ],
    explanation: "In T568A: Pin 6 = Orange (solid). The orange pair occupies pins 3 (White/Orange) and 6 (Orange) in T568A. In T568B, pin 6 is Green. This is one of the four pin positions that differ between T568A and T568B. Remembering that T568A has green on pins 1/2 and orange on pins 3/6 helps distinguish the two standards.",
    triggerPhrase: "T568A pin 6 Orange",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q39",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "Which wiring standard is most commonly used in commercial and enterprise Ethernet installations in the United States?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "T568B", correct: true },
      { id: "b", text: "T568A", correct: false },
      { id: "c", text: "Both are used equally", correct: false },
      { id: "d", text: "T568C", correct: false },
    ],
    explanation: "T568B is the most commonly used wiring standard in commercial and enterprise environments in the United States. T568A is recommended by the US government (TIA) and is preferred in residential installations. T568C does not exist as a standard. The most important rule: use the same standard on BOTH ends of a straight-through patch cable.",
    triggerPhrase: "T568B most common enterprise US",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
  {
    id: "ext6-q40",
    domain: "2.0-networking",
    difficulty: "medium",
    type: "single",
    source: "concept-builder",
    prompt: "What color is pin 2 on a T568B wired Ethernet cable?",
    image: "/diagrams/07_wiring_standards.svg",
    imageAlt: "T568A and T568B wiring standards pin color diagram",
    choices: [
      { id: "a", text: "Orange", correct: true },
      { id: "b", text: "White/Orange", correct: false },
      { id: "c", text: "Green", correct: false },
      { id: "d", text: "White/Green", correct: false },
    ],
    explanation: "In T568B: Pin 1 = White/Orange, Pin 2 = Orange. The orange pair occupies the first two pins in T568B. In T568A, pin 2 is Green (the green pair occupies pins 1 and 2 in T568A). This pin-2 difference (Orange in T568B vs Green in T568A) is a quick way to identify which standard a cable follows.",
    triggerPhrase: "T568B pin 2 Orange",
    weaknessTags: ["t568a-568b-crossover", "wiring-standards"],
  },
`;

const newContent = content.substring(0, insertAt) + newQuestions + '\n];';
fs.writeFileSync(filePath, newContent, 'utf8');

const lineCount = newContent.split('\n').length;
console.log(`Done! File now has ${lineCount} lines.`);
console.log(`Appended 40 questions (ext6-q01 through ext6-q40).`);
